//! The C/C++ (extern "C" ABI) template grid — one language's projection of the
//! op shapes into a stable C ABI, plus the C header and C++ RAII wrapper.
//!
//! straitjacket-allow-file:duplication — the per-language generators are
//! DELIBERATELY parallel: the (language × shape) template grid is the design
//! (see /translation.md); the truly shared pieces live in the parent module.
//!
//! Three artifacts share this module's crossing classifier so the Rust export
//! layer ([`cpp_binding`]), the C header ([`super::cpp_header::cpp_header`]) and
//! the C++ wrapper ([`super::cpp_hpp::cpp_hpp`]) agree on every signature:
//!   * `cpp_binding`  — the Rust `extern "C"` layer, compiled INTO the cdylib.
//!   * `cpp_header`   — the plain-C `.h` (opaque handles + prototypes).
//!   * `cpp_hpp`      — the C++ `.hpp` RAII wrapper (throws `fluessig::Error`).
//!
//! The full ABI is documented in the design spec that ships with this backend.

use crate::api::{ApiDoc, ApiOp, ApiType, Shape};

use super::*;

// The C header and C++ wrapper are generated by the sibling modules; re-export
// them here so `crate::bindgen::{cpp_binding, cpp_header, cpp_hpp}` all resolve
// through `cpp::` (one re-export line in `mod.rs`, additive alongside the other
// backends).
pub use super::cpp_header::cpp_header;
pub use super::cpp_hpp::cpp_hpp;

/// This backend's language slug — the key it reads out of every symbol's
/// `bindings` map via the shared [`pinned_name`] resolver. C has no namespacing,
/// so an op pin replaces the op segment of the flat `<Iface>_<op>` symbol.
pub(super) const LANG: &str = "cpp";

// ── name helpers (shared across the three artifacts) ─────────────────────────

/// The C enum type name for a real (int-backed) enum: `Flavor` → `FlFlavor`.
pub(super) fn c_enum_name(name: &str) -> String {
    format!("Fl{}", pascal(name))
}

/// The C struct type name for a DTO model: `Chunk` → `FlChunk`.
pub(super) fn c_model_name(name: &str) -> String {
    format!("Fl{}", pascal(name))
}

/// The opaque cursor handle type name for a stream op: `Svc` + `watch` →
/// `SvcWatchStream`.
pub(super) fn c_stream_name(iface: &str, op: &ApiOp) -> String {
    format!("{iface}{}Stream", pascal(&op.name))
}

/// The per-list struct type name for an element token: `String` → `FlStringList`.
pub(super) fn c_list_name(elem_token: &str) -> String {
    format!("Fl{elem_token}List")
}

/// The op's flat C symbol: `<Iface>_<op>`, honoring an op-name pin (which
/// replaces the op segment).
pub(super) fn op_symbol(iface: &str, op: &ApiOp) -> String {
    let opname = pinned_name(&op.bindings, LANG).unwrap_or_else(|| snake(&op.name));
    format!("{iface}_{opname}")
}

/// A field's C member name, honoring a field pin.
pub(super) fn field_name(f: &crate::api::ApiField) -> String {
    pinned_name(&f.bindings, LANG).unwrap_or_else(|| snake(&f.name))
}

// ── the crossing classifier ──────────────────────────────────────────────────

/// How a return/param/field type crosses the C ABI. Shared by all three
/// artifacts so the Rust extern signature, the C prototype, and the C++ wrapper
/// agree by construction.
#[derive(Clone)]
pub(super) enum Cross {
    Void,
    I32,
    I64,
    U8,
    U16,
    U32,
    F32,
    F64,
    Bool,
    /// UTF-8 string (also the `Json` / date-time / unknown-scalar carrier).
    Str,
    /// Bulk bytes (`FlBytes` OUT, `const uint8_t*,size_t` IN).
    Bytes,
    /// A real int-backed enum (Rust ident carried for `from_c`/`as i32`).
    Enum(String),
    /// A value-carrying enum projected as a string (mirrors `is_string_enum`).
    StrEnum,
    /// A DTO model (`Fl<Model>` C struct).
    Model(String),
    /// A tagged union — crosses as its JSON envelope text (a `Str` carrier).
    Union,
    List(Box<Cross>),
    Nullable(Box<Cross>),
}

/// Classify an [`ApiType`] into its C-ABI [`Cross`].
pub(super) fn classify(api: &ApiDoc, t: &ApiType) -> Cross {
    match t {
        ApiType::Scalar(s) => match s.as_str() {
            "void" => Cross::Void,
            "int32" => Cross::I32,
            "int64" => Cross::I64,
            "uint8" => Cross::U8,
            "uint16" => Cross::U16,
            "uint32" => Cross::U32,
            "float32" => Cross::F32,
            "float64" | "float" => Cross::F64,
            "boolean" => Cross::Bool,
            "bytes" => Cross::Bytes,
            // `string`/`Json` and every other scalar (utcDateTime, ArrowBatch,
            // …) ride the UTF-8 string carrier — the honest default for a scalar
            // the C ABI has no dedicated representation for.
            _ => Cross::Str,
        },
        ApiType::Model { model } => Cross::Model(model.clone()),
        ApiType::Enum { r#enum } => {
            if is_string_enum(api, r#enum) {
                Cross::StrEnum
            } else {
                Cross::Enum(r#enum.clone())
            }
        }
        ApiType::List { list } => Cross::List(Box::new(classify(api, list))),
        ApiType::Nullable { nullable } => Cross::Nullable(Box::new(classify(api, nullable))),
        ApiType::Union { .. } => Cross::Union,
        // A truly-foreign type has no dedicated C-ABI representation; it rides the
        // UTF-8 string carrier (the honest default the scalar catchall also uses).
        // The typed opaque handle is a rust-core concern (see `rust_core`).
        ApiType::Foreign { .. } => Cross::Str,
        // cpp callback lowering is a follow-up (see notes/callback-function-types.md);
        // no committed fixture feeds cpp a callback, so the string carrier is a
        // reachable-only-in-future placeholder that keeps `classify` total.
        ApiType::Callback { .. } => Cross::Str,
    }
}

/// Classify a param, folding an `optional` marker into a [`Cross::Nullable`] so
/// the core call receives an `Option`, matching the shared [`param_sig`].
pub(super) fn classify_param(api: &ApiDoc, p: &crate::api::ApiParam) -> Cross {
    let c = classify(api, &p.ty);
    if p.optional == Some(true) {
        Cross::Nullable(Box::new(c))
    } else {
        c
    }
}

/// The element token used in list type names (`FlStringList`, `FlInt32List`, …).
pub(super) fn list_elem_token(c: &Cross) -> String {
    match c {
        Cross::I32 => "Int32".into(),
        Cross::I64 => "Int64".into(),
        Cross::U8 => "Uint8".into(),
        Cross::U16 => "Uint16".into(),
        Cross::U32 => "Uint32".into(),
        Cross::F32 => "Float32".into(),
        Cross::F64 => "Float64".into(),
        Cross::Bool => "Bool".into(),
        Cross::Str | Cross::StrEnum | Cross::Union => "String".into(),
        Cross::Bytes => "Bytes".into(),
        Cross::Enum(_) => "Int32".into(),
        Cross::Model(m) => pascal(m),
        Cross::List(inner) => format!("{}List", list_elem_token(inner)),
        Cross::Nullable(inner) => list_elem_token(inner),
        Cross::Void => "Void".into(),
    }
}

/// Collect every distinct list element crossing used anywhere in the api, keyed
/// by its list-name token (`String`, `Int32`, `FooModel`, …), in first-seen
/// order. The single source of truth for which `Fl<T>List` structs, helpers, and
/// free functions the three artifacts must agree on. Only top-level list
/// elements are visited (nested `list<list<T>>` is a documented gap — matching
/// the flat token the C header emits).
pub(super) fn collect_list_elems(api: &ApiDoc) -> Vec<(String, Cross)> {
    let mut seen = std::collections::BTreeSet::new();
    let mut out: Vec<(String, Cross)> = Vec::new();
    let mut visit = |c: &Cross, out: &mut Vec<(String, Cross)>| {
        if let Cross::List(inner) = c {
            let token = list_elem_token(inner);
            if seen.insert(token.clone()) {
                out.push((token, (**inner).clone()));
            }
        }
    };
    for m in &api.models {
        for f in &m.fields {
            visit(&classify(api, &f.ty), &mut out);
        }
    }
    for i in &api.interfaces {
        for op in &i.ops {
            visit(&classify(api, &op.returns), &mut out);
            for p in &op.params {
                visit(&classify_param(api, p), &mut out);
            }
        }
    }
    out
}

/// The core-facing Rust element type for a list element crossing (`Vec<Elem>`).
fn list_elem_rust(elem: &Cross) -> String {
    match elem {
        Cross::I32 => "i32".into(),
        Cross::I64 => "i64".into(),
        Cross::U8 => "u8".into(),
        Cross::U16 => "u16".into(),
        Cross::U32 => "u32".into(),
        Cross::F32 => "f32".into(),
        Cross::F64 => "f64".into(),
        Cross::Bool => "bool".into(),
        Cross::Str | Cross::StrEnum | Cross::Union => "String".into(),
        Cross::Bytes => "Bytes".into(),
        Cross::Enum(e) => e.clone(),
        Cross::Model(m) => m.clone(),
        // nested list / nullable elements aren't marshalled (documented gap)
        _ => "String".into(),
    }
}

/// Read one list element from a `p: *const <elem_c>` into its Rust value.
fn list_in_elem(elem: &Cross) -> String {
    match elem {
        Cross::I32
        | Cross::I64
        | Cross::U8
        | Cross::U16
        | Cross::U32
        | Cross::F32
        | Cross::F64
        | Cross::Bool => "*p".into(),
        Cross::Str | Cross::StrEnum | Cross::Union => "fl_str_in(*p)".into(),
        Cross::Enum(e) => format!("{e}::from_c(*p)"),
        Cross::Model(m) => format!("{}_from_c(&*p)", snake(m)),
        Cross::Bytes => "fl_bytes_in((*p).data, (*p).len)".into(),
        _ => "fl_str_in(*p)".into(),
    }
}

/// Move one Rust list element `x: <elem_rust>` into its owned C value `<elem_c>`.
fn list_out_elem(elem: &Cross) -> String {
    match elem {
        Cross::I32
        | Cross::I64
        | Cross::U8
        | Cross::U16
        | Cross::U32
        | Cross::F32
        | Cross::F64
        | Cross::Bool => "x".into(),
        Cross::Str | Cross::StrEnum | Cross::Union => "fl_str_out(x)".into(),
        Cross::Enum(_) => "x as i32".into(),
        Cross::Model(m) => format!("{}_to_c(x)", snake(m)),
        Cross::Bytes => "fl_bytes_out(x)".into(),
        _ => "fl_str_out(x)".into(),
    }
}

/// Free one owned C list element bound as `e: <elem_c>`; `None` when the element
/// owns no heap (plain scalars / enums cross by value).
fn list_free_elem(elem: &Cross) -> Option<String> {
    match elem {
        Cross::Str | Cross::StrEnum | Cross::Union => Some("fl_string_free(e);".into()),
        Cross::Bytes => Some("{ let mut e = e; fl_bytes_free(&mut e); }".into()),
        Cross::Model(m) => Some(format!(
            "{{ let mut e = e; fl_{}_free(&mut e); }}",
            snake(m)
        )),
        _ => None,
    }
}

/// The `#[repr(C)] Fl<T>List` struct + its in/out/free helpers, for every list
/// element the api uses. Emitted only when the api has at least one list, so a
/// list-free schema stays byte-identical to the pre-list generator.
fn emit_rust_list_support(elems: &[(String, Cross)]) -> String {
    let mut s = String::new();
    for (token, elem) in elems {
        let list_ty = c_list_name(token);
        let elem_c = rust_c_member_type(elem);
        let elem_rust = list_elem_rust(elem);
        let sn = snake(token);
        s.push_str(&format!(
            "/// The `list<{elem_rust}>` carrier across the C ABI (free with `fl_{sn}_list_free`).\n"
        ));
        s.push_str("#[repr(C)]\n");
        s.push_str(&format!(
            "pub struct {list_ty} {{\n    pub data: *mut {elem_c},\n    pub len: usize,\n}}\n\n"
        ));
        // An empty-list Default so the nullable-list write paths have a zero value.
        s.push_str(&format!(
            "impl Default for {list_ty} {{\n    fn default() -> Self {{\n        {list_ty} {{ data: std::ptr::null_mut(), len: 0 }}\n    }}\n}}\n\n"
        ));
        // in: const <elem_c>* + len → Vec<elem_rust>
        s.push_str(&format!(
            "unsafe fn {sn}_list_in(ptr: *const {elem_c}, len: usize) -> Vec<{elem_rust}> {{\n    if ptr.is_null() {{\n        return Vec::new();\n    }}\n    (0..len)\n        .map(|i| {{\n            let p = ptr.add(i);\n            {}\n        }})\n        .collect()\n}}\n\n",
            list_in_elem(elem)
        ));
        // out: Vec<elem_rust> → owned Fl<T>List
        s.push_str(&format!(
            "fn {sn}_list_out(v: Vec<{elem_rust}>) -> {list_ty} {{\n    let mut items: Vec<{elem_c}> = v.into_iter().map(|x| {}).collect();\n    items.shrink_to_fit();\n    let len = items.len();\n    let data = items.as_mut_ptr();\n    std::mem::forget(items);\n    {list_ty} {{ data, len }}\n}}\n\n",
            list_out_elem(elem)
        ));
        // free
        s.push_str(&format!(
            "#[no_mangle]\npub unsafe extern \"C\" fn fl_{sn}_list_free(p: *mut {list_ty}) {{\n    if p.is_null() {{\n        return;\n    }}\n    let p = &mut *p;\n    if !p.data.is_null() {{\n        let items = Vec::from_raw_parts(p.data, p.len, p.len);\n"
        ));
        match list_free_elem(elem) {
            Some(free) => s.push_str(&format!(
                "        for e in items {{\n            {free}\n        }}\n"
            )),
            None => s.push_str("        drop(items);\n"),
        }
        s.push_str("        p.data = std::ptr::null_mut();\n        p.len = 0;\n    }\n}\n");
    }
    s
}

// ── the C-side type mappers (consumed by cpp_header) ─────────────────────────

/// The C by-value type for a scalar-ish crossing (struct members, stream item
/// type, by-value returns). Compound types return their `Fl…` name.
pub(super) fn c_value_type(c: &Cross) -> String {
    match c {
        Cross::Void => "void".into(),
        Cross::I32 => "int32_t".into(),
        Cross::I64 => "int64_t".into(),
        Cross::U8 => "uint8_t".into(),
        Cross::U16 => "uint16_t".into(),
        Cross::U32 => "uint32_t".into(),
        Cross::F32 => "float".into(),
        Cross::F64 => "double".into(),
        Cross::Bool => "bool".into(),
        Cross::Str | Cross::StrEnum | Cross::Union => "char*".into(),
        Cross::Bytes => "FlBytes".into(),
        Cross::Enum(e) => c_enum_name(e),
        Cross::Model(m) => c_model_name(m),
        Cross::List(inner) => c_list_name(&list_elem_token(inner)),
        // A struct member that is nullable rides the inner value type; the flag
        // (`has_<name>`) is emitted alongside by the member renderer.
        Cross::Nullable(inner) => c_value_type(inner),
    }
}

// ── the C++-side type mappers (consumed by cpp_hpp) ──────────────────────────

/// The idiomatic C++ value type for a crossing (std::string / std::vector / …).
pub(super) fn cpp_value_type(c: &Cross) -> String {
    match c {
        Cross::Void => "void".into(),
        Cross::I32 => "int32_t".into(),
        Cross::I64 => "int64_t".into(),
        Cross::U8 => "uint8_t".into(),
        Cross::U16 => "uint16_t".into(),
        Cross::U32 => "uint32_t".into(),
        Cross::F32 => "float".into(),
        Cross::F64 => "double".into(),
        Cross::Bool => "bool".into(),
        // strings, string-enums and unions (JSON) all surface as std::string.
        Cross::Str | Cross::StrEnum | Cross::Union => "std::string".into(),
        Cross::Bytes => "std::vector<uint8_t>".into(),
        Cross::Enum(e) => c_enum_name(e),
        Cross::Model(m) => c_model_name(m),
        Cross::List(inner) => format!("std::vector<{}>", cpp_value_type(inner)),
        Cross::Nullable(inner) => format!("std::optional<{}>", cpp_value_type(inner)),
    }
}

// ── the Rust extern "C" export layer ─────────────────────────────────────────

/// Convert an incoming C string to an owned `String` (empty on NULL).
const RUST_MARSHAL_PRELUDE: &str = r#"/// Convert an incoming C string (UTF-8, NUL-terminated) into an owned `String`.
unsafe fn fl_str_in(p: *const c_char) -> String {
    if p.is_null() {
        String::new()
    } else {
        CStr::from_ptr(p).to_string_lossy().into_owned()
    }
}

/// Hand an owned string back to C (the caller frees it with `fl_string_free`).
fn fl_str_out(s: String) -> *mut c_char {
    CString::new(s).unwrap_or_default().into_raw()
}

/// Free a string (or error message) handed out across the ABI.
#[no_mangle]
pub unsafe extern "C" fn fl_string_free(p: *mut c_char) {
    if !p.is_null() {
        drop(CString::from_raw(p));
    }
}

/// Free an error message handed out through a trailing `err_out`.
#[no_mangle]
pub unsafe extern "C" fn fl_error_free(p: *mut c_char) {
    if !p.is_null() {
        drop(CString::from_raw(p));
    }
}
"#;

/// The `FlBytes` carrier + its in/out helpers + free fn (gated on bytes usage).
const RUST_BYTES_PRELUDE: &str = r#"/// Bulk bytes crossing the C ABI: an owned buffer the caller frees with
/// `fl_bytes_free`.
#[repr(C)]
pub struct FlBytes {
    pub data: *mut u8,
    pub len: usize,
}

/// Type alias so the generated core trait speaks one `Bytes` name (as the other
/// backends' preludes do); across the C ABI bytes are a plain `Vec<u8>`.
pub type Bytes = Vec<u8>;

unsafe fn fl_bytes_in(ptr: *const u8, len: usize) -> Bytes {
    if ptr.is_null() {
        Vec::new()
    } else {
        std::slice::from_raw_parts(ptr, len).to_vec()
    }
}

fn fl_bytes_out(mut v: Bytes) -> FlBytes {
    v.shrink_to_fit();
    let len = v.len();
    let data = v.as_mut_ptr();
    std::mem::forget(v);
    FlBytes { data, len }
}

#[no_mangle]
pub unsafe extern "C" fn fl_bytes_free(b: *mut FlBytes) {
    if b.is_null() {
        return;
    }
    let b = &mut *b;
    if !b.data.is_null() {
        drop(Vec::from_raw_parts(b.data, b.len, b.len));
        b.data = std::ptr::null_mut();
        b.len = 0;
    }
}
"#;

/// The `FlPoll` C enum mirroring the pull-cursor poll result.
const RUST_POLL_ENUM: &str = r#"/// The pull-cursor poll result across the C ABI (mirrors `Poll<T>`).
#[repr(C)]
pub enum FlPoll {
    Item = 0,
    Idle = 1,
    Closed = 2,
    Failed = 3,
}
"#;

/// Generate the Rust `extern "C"` binding: plain enums + DTO structs (the core
/// speaks these), the `Fl…` C-repr structs + conversions, the `<Iface>Core`
/// traits, and one `#[no_mangle] pub extern "C"` function per op shape with the
/// stable ABI documented in the design spec.
pub fn cpp_binding(api: &ApiDoc, enums: &[EnumDesc], banner_note: Option<&str>) -> String {
    // A `single_threaded` interface is a thread-confined `!Send` handle — node-only
    // today. Split it out (emit nothing for it) + append an honest skip-note rather
    // than a silent handle. None ⇒ empty note, output byte-identical.
    let (api_owned, st_note) = crate::bindgen::split_single_threaded(api, "cpp");
    let api = &api_owned;
    let uses_bytes = api_uses_bytes(api);
    let runtime_import = RUNTIME_STREAM_IMPORT.render();
    let mut s = String::new();

    // ── prelude ──
    s.push_str("// The fixed prelude — generated code uses fully-qualified paths elsewhere.\n");
    s.push_str("use std::ffi::{CStr, CString};\n");
    s.push_str("use std::os::raw::{c_char, c_int};\n");
    s.push_str("use std::time::Duration;\n");
    s.push_str(
        "// The shared streaming contract — Poll/PollStream live in the fluessig-runtime crate.\n",
    );
    s.push_str(&runtime_import);
    s.push('\n');
    s.push('\n');
    s.push_str(RUST_MARSHAL_PRELUDE);
    s.push('\n');
    s.push_str(RUST_POLL_ENUM);
    if uses_bytes {
        s.push('\n');
        s.push_str(RUST_BYTES_PRELUDE);
    }

    // ── enums: plain Rust (int-backed) with from_c/wire (the core speaks these;
    // the C ABI carries the discriminant, `is_string_enum` enums cross as text) ──
    for (name, variants) in enums {
        if is_string_enum(api, name) {
            continue;
        }
        s.push('\n');
        s.push_str(&emit_rust_enum(name, variants));
    }

    // ── DTO models: the plain Rust struct (core-facing), the `Fl…` C-repr
    // struct, and the two conversions + owning free ──
    for m in &api.models {
        s.push('\n');
        s.push_str(&emit_rust_dto(api, m));
        s.push('\n');
        s.push_str(&emit_c_repr_struct(api, m));
        s.push('\n');
        s.push_str(&emit_dto_conversions(api, m));
    }

    // ── list carriers: the `Fl<T>List` structs + in/out/free helpers (emitted
    // only when the api uses a list, so a list-free schema stays byte-identical
    // to the pre-list generator) ──
    let list_elems = collect_list_elems(api);
    if !list_elems.is_empty() {
        s.push('\n');
        s.push_str(&emit_rust_list_support(&list_elems));
    }

    // ── the shared core traits (one spine every backend drives) ──
    let mut ct: rust::Tokens = quote!();
    emit_core_traits(&mut ct, api);
    s.push('\n');
    s.push_str(&ct.to_file_string().expect("core traits render"));

    // ── per-interface extern "C" surface ──
    for i in &api.interfaces {
        s.push('\n');
        s.push_str(&emit_interface(api, i));
    }

    let src = api.source.as_deref().unwrap_or("the fluessig catalog");
    let out = crate::rustfmt::format(format!(
        "//! GENERATED by fluessig bindgen from {src} (C ABI export layer). Do not edit.\n{}#![allow(clippy::all)]\n#![allow(dead_code)]\n#![allow(unused_imports)]\n\n{s}",
        note_line(banner_note)
    ));
    format!("{out}{st_note}")
}

/// A plain int-backed Rust enum with `from_c` (C int → variant) — the core-facing
/// type the DTO fields and op signatures reference.
fn emit_rust_enum(name: &str, variants: &[EnumVariant]) -> String {
    let mut s = String::new();
    s.push_str("#[derive(Clone, Copy, PartialEq)]\n");
    s.push_str("#[repr(i32)]\n");
    s.push_str(&format!("pub enum {name} {{\n"));
    for (idx, v) in variants.iter().enumerate() {
        s.push_str(&format!("    {} = {idx},\n", pascal(&v.name)));
    }
    s.push_str("}\n");
    s.push_str(&format!("impl {name} {{\n"));
    s.push_str("    /// The variant for a C ABI discriminant (falls back to the first variant).\n");
    s.push_str("    pub fn from_c(v: i32) -> Self {\n");
    s.push_str("        match v {\n");
    for (idx, v) in variants.iter().enumerate() {
        if idx == 0 {
            continue;
        }
        s.push_str(&format!(
            "            {idx} => Self::{},\n",
            pascal(&v.name)
        ));
    }
    let first = variants
        .first()
        .map(|v| pascal(&v.name))
        .unwrap_or_else(|| "Unknown".into());
    s.push_str(&format!("            _ => Self::{first},\n"));
    s.push_str("        }\n");
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}

/// The Rust field type for a DTO field (the core-facing type, `Option<…>` when
/// nullable) — the same mapping php uses.
fn rust_field_type(api: &ApiDoc, f: &crate::api::ApiField) -> String {
    let (r, _) = ty(api, &f.ty);
    if f.nullable {
        format!("Option<{r}>")
    } else {
        r
    }
}

/// The plain core-facing DTO struct (`pub struct Chunk { pub seq: i32, … }`).
fn emit_rust_dto(api: &ApiDoc, m: &crate::api::ApiModel) -> String {
    let mut s = String::new();
    if let Some(doc) = &m.doc {
        for line in doc.lines() {
            s.push_str(&format!("/// {line}\n"));
        }
    }
    s.push_str("#[derive(Clone)]\n");
    s.push_str(&format!("pub struct {} {{\n", m.name));
    for f in &m.fields {
        s.push_str(&format!(
            "    pub {}: {},\n",
            snake(&f.name),
            rust_field_type(api, f)
        ));
    }
    s.push_str("}\n");
    s
}

/// The Rust extern repr of a C struct member for a crossing.
fn rust_c_member_type(c: &Cross) -> String {
    match c {
        Cross::Void => "()".into(),
        Cross::I32 | Cross::Enum(_) => "i32".into(),
        Cross::I64 => "i64".into(),
        Cross::U8 => "u8".into(),
        Cross::U16 => "u16".into(),
        Cross::U32 => "u32".into(),
        Cross::F32 => "f32".into(),
        Cross::F64 => "f64".into(),
        Cross::Bool => "bool".into(),
        Cross::Str | Cross::StrEnum | Cross::Union => "*mut c_char".into(),
        Cross::Bytes => "FlBytes".into(),
        Cross::Model(m) => c_model_name(m),
        Cross::List(inner) => c_list_name(&list_elem_token(inner)),
        Cross::Nullable(inner) => rust_c_member_type(inner),
    }
}

/// The `#[repr(C)] pub struct Fl<Model>` mirroring the DTO across the ABI. A
/// nullable scalar member becomes `has_<name>: bool` + the value; a nullable
/// pointer-carrying member (string/model/union/bytes) uses NULL = absent.
fn emit_c_repr_struct(api: &ApiDoc, m: &crate::api::ApiModel) -> String {
    let mut s = String::new();
    s.push_str("#[repr(C)]\n");
    s.push_str(&format!("pub struct {} {{\n", c_model_name(&m.name)));
    for f in &m.fields {
        let name = field_name(f);
        let mut c = classify(api, &f.ty);
        if f.nullable {
            c = Cross::Nullable(Box::new(c));
        }
        if let Cross::Nullable(inner) = &c {
            if member_is_pointer(inner) {
                s.push_str(&format!("    pub {name}: {},\n", rust_c_member_type(inner)));
            } else {
                s.push_str(&format!("    pub has_{name}: bool,\n"));
                s.push_str(&format!("    pub {name}: {},\n", rust_c_member_type(inner)));
            }
        } else {
            s.push_str(&format!("    pub {name}: {},\n", rust_c_member_type(&c)));
        }
    }
    s.push_str("}\n");
    s
}

/// Does this crossing already carry NULL-as-absent through a pointer (so a
/// nullable of it needs no separate `has_` flag)?
fn member_is_pointer(c: &Cross) -> bool {
    matches!(
        c,
        Cross::Str | Cross::StrEnum | Cross::Union | Cross::Model(_)
    )
}

/// The two conversions (`<m>_to_c` / `<m>_from_c`) plus the owning `fl_<m>_free`
/// when the model holds heap members.
fn emit_dto_conversions(api: &ApiDoc, m: &crate::api::ApiModel) -> String {
    let cname = c_model_name(&m.name);
    let snake_m = snake(&m.name);
    let mut owns_heap = false;
    let mut s = String::new();

    // to_c
    s.push_str(&format!(
        "/// Move a core `{}` into its owned C repr `{cname}`.\n",
        m.name
    ));
    s.push_str(&format!("fn {snake_m}_to_c(v: {}) -> {cname} {{\n", m.name));
    s.push_str(&format!("    {cname} {{\n"));
    for f in &m.fields {
        let name = field_name(f);
        let src = format!("v.{}", snake(&f.name));
        let mut c = classify(api, &f.ty);
        if f.nullable {
            c = Cross::Nullable(Box::new(c));
        }
        if member_owns_heap(&c) {
            owns_heap = true;
        }
        s.push_str(&member_to_c(&c, &name, &src));
    }
    s.push_str("    }\n");
    s.push_str("}\n\n");

    // from_c
    s.push_str(&format!(
        "/// Read a `{cname}` back into a core `{}` (borrowing, no ownership taken).\n",
        m.name
    ));
    s.push_str(&format!(
        "unsafe fn {snake_m}_from_c(c: &{cname}) -> {} {{\n",
        m.name
    ));
    s.push_str(&format!("    {} {{\n", m.name));
    for f in &m.fields {
        let name = field_name(f);
        let mut c = classify(api, &f.ty);
        if f.nullable {
            c = Cross::Nullable(Box::new(c));
        }
        s.push_str(&member_from_c(&c, &name, &snake(&f.name)));
    }
    s.push_str("    }\n");
    s.push_str("}\n");

    if owns_heap {
        s.push('\n');
        s.push_str(&format!(
            "/// Free the heap members an owning `{cname}` holds.\n"
        ));
        s.push_str(&format!(
            "#[no_mangle]\npub unsafe extern \"C\" fn fl_{snake_m}_free(p: *mut {cname}) {{\n"
        ));
        s.push_str("    if p.is_null() {\n        return;\n    }\n");
        s.push_str("    let p = &mut *p;\n");
        for f in &m.fields {
            let name = field_name(f);
            let mut c = classify(api, &f.ty);
            if f.nullable {
                c = Cross::Nullable(Box::new(c));
            }
            if let Some(free) = member_free(&c, &name) {
                s.push_str(&free);
            }
        }
        s.push_str("}\n");
    }
    s
}

/// Does a crossing own heap that a free fn must reclaim?
fn member_owns_heap(c: &Cross) -> bool {
    match c {
        Cross::Str | Cross::StrEnum | Cross::Union | Cross::Bytes => true,
        Cross::Model(_) => true,
        Cross::List(_) => true,
        Cross::Nullable(inner) => member_owns_heap(inner),
        _ => false,
    }
}

/// One `to_c` field initializer line(s), given the C member name and the Rust
/// source expression.
fn member_to_c(c: &Cross, name: &str, src: &str) -> String {
    match c {
        Cross::I32
        | Cross::I64
        | Cross::U8
        | Cross::U16
        | Cross::U32
        | Cross::F32
        | Cross::F64
        | Cross::Bool => {
            format!("        {name}: {src},\n")
        }
        Cross::Enum(_) => format!("        {name}: {src} as i32,\n"),
        Cross::Str | Cross::StrEnum | Cross::Union => {
            format!("        {name}: fl_str_out({src}),\n")
        }
        Cross::Bytes => format!("        {name}: fl_bytes_out({src}),\n"),
        Cross::Model(m) => format!("        {name}: {}_to_c({src}),\n", snake(m)),
        Cross::List(inner) => {
            let token = list_elem_token(inner);
            format!("        {name}: {}_list_out({src}),\n", snake(&token))
        }
        Cross::Nullable(inner) => {
            if member_is_pointer(inner) {
                let some = match inner.as_ref() {
                    Cross::Model(m) => format!("{}_to_c(x)", snake(m)),
                    _ => "fl_str_out(x)".to_string(),
                };
                format!(
                    "        {name}: match {src} {{ Some(x) => {some}, None => std::ptr::null_mut() }},\n"
                )
            } else {
                let val = match inner.as_ref() {
                    Cross::Enum(_) => "x as i32",
                    _ => "x",
                };
                format!(
                    "        has_{name}: {src}.is_some(),\n        {name}: match {src} {{ Some(x) => {val}, None => Default::default() }},\n"
                )
            }
        }
        Cross::Void => String::new(),
    }
}

/// One `from_c` field initializer line, given the C member name and the Rust
/// field name.
fn member_from_c(c: &Cross, cname: &str, rname: &str) -> String {
    match c {
        Cross::I32
        | Cross::I64
        | Cross::U8
        | Cross::U16
        | Cross::U32
        | Cross::F32
        | Cross::F64
        | Cross::Bool => {
            format!("        {rname}: c.{cname},\n")
        }
        Cross::Enum(e) => format!("        {rname}: {e}::from_c(c.{cname}),\n"),
        Cross::Str | Cross::StrEnum | Cross::Union => {
            format!("        {rname}: fl_str_in(c.{cname}),\n")
        }
        Cross::Bytes => format!("        {rname}: fl_bytes_in(c.{cname}.data, c.{cname}.len),\n"),
        Cross::Model(m) => format!("        {rname}: {}_from_c(&c.{cname}),\n", snake(m)),
        Cross::List(inner) => {
            let token = list_elem_token(inner);
            format!(
                "        {rname}: {}_list_in(c.{cname}.data, c.{cname}.len),\n",
                snake(&token)
            )
        }
        Cross::Nullable(inner) => {
            if member_is_pointer(inner) {
                let some = match inner.as_ref() {
                    Cross::Model(m) => format!("{}_from_c(&*c.{cname})", snake(m)),
                    _ => format!("fl_str_in(c.{cname})"),
                };
                format!(
                    "        {rname}: if c.{cname}.is_null() {{ None }} else {{ Some({some}) }},\n"
                )
            } else {
                let some = match inner.as_ref() {
                    Cross::Enum(e) => format!("{e}::from_c(c.{cname})"),
                    _ => format!("c.{cname}"),
                };
                format!("        {rname}: if c.has_{cname} {{ Some({some}) }} else {{ None }},\n")
            }
        }
        Cross::Void => String::new(),
    }
}

/// The free statement(s) for one heap-owning member, or `None`.
fn member_free(c: &Cross, name: &str) -> Option<String> {
    match c {
        Cross::Str | Cross::StrEnum | Cross::Union => {
            Some(format!("    fl_string_free(p.{name});\n"))
        }
        Cross::Bytes => Some(format!("    fl_bytes_free(&mut p.{name});\n")),
        Cross::Model(m) => Some(format!("    fl_{}_free(&mut p.{name});\n", snake(m))),
        Cross::List(inner) => {
            let token = list_elem_token(inner);
            Some(format!(
                "    fl_{}_list_free(&mut p.{name});\n",
                snake(&token)
            ))
        }
        Cross::Nullable(inner) => {
            if member_is_pointer(inner) {
                match inner.as_ref() {
                    Cross::Model(m) => Some(format!(
                        "    if !p.{name}.is_null() {{ fl_{}_free(p.{name}); }}\n",
                        snake(m)
                    )),
                    _ => Some(format!(
                        "    if !p.{name}.is_null() {{ fl_string_free(p.{name}); }}\n"
                    )),
                }
            } else {
                None
            }
        }
        _ => None,
    }
}

// ── the Rust extern parameter / return renderers ─────────────────────────────

/// Render an op's IN params: the Rust extern decls, the C→Rust conversion
/// statements, and the ordered call-site names.
fn rust_in_params(api: &ApiDoc, op: &ApiOp) -> (Vec<String>, Vec<String>, Vec<String>) {
    let mut decls = Vec::new();
    let mut conv = Vec::new();
    let mut names = Vec::new();
    for p in &op.params {
        let name = snake(&p.name);
        let c = classify_param(api, p);
        rust_in_one(&c, &name, &mut decls, &mut conv);
        names.push(name);
    }
    (decls, conv, names)
}

fn rust_in_one(c: &Cross, name: &str, decls: &mut Vec<String>, conv: &mut Vec<String>) {
    match c {
        Cross::I32 => decls.push(format!("{name}: i32")),
        Cross::I64 => decls.push(format!("{name}: i64")),
        Cross::U8 => decls.push(format!("{name}: u8")),
        Cross::U16 => decls.push(format!("{name}: u16")),
        Cross::U32 => decls.push(format!("{name}: u32")),
        Cross::F32 => decls.push(format!("{name}: f32")),
        Cross::F64 => decls.push(format!("{name}: f64")),
        Cross::Bool => decls.push(format!("{name}: bool")),
        Cross::Str | Cross::StrEnum | Cross::Union => {
            decls.push(format!("{name}: *const c_char"));
            conv.push(format!("let {name} = fl_str_in({name});"));
        }
        Cross::Bytes => {
            decls.push(format!("{name}_ptr: *const u8"));
            decls.push(format!("{name}_len: usize"));
            conv.push(format!("let {name} = fl_bytes_in({name}_ptr, {name}_len);"));
        }
        Cross::Enum(e) => {
            decls.push(format!("{name}: i32"));
            conv.push(format!("let {name} = {e}::from_c({name});"));
        }
        Cross::Model(m) => {
            decls.push(format!("{name}: *const {}", c_model_name(m)));
            conv.push(format!("let {name} = {}_from_c(&*{name});", snake(m)));
        }
        Cross::List(inner) => {
            let token = list_elem_token(inner);
            let elem_c = rust_c_member_type(inner);
            decls.push(format!("{name}_ptr: *const {elem_c}"));
            decls.push(format!("{name}_len: usize"));
            conv.push(format!(
                "let {name} = {}_list_in({name}_ptr, {name}_len);",
                snake(&token)
            ));
        }
        Cross::Nullable(inner) => {
            match inner.as_ref() {
                Cross::I32
                | Cross::I64
                | Cross::U8
                | Cross::U16
                | Cross::U32
                | Cross::F32
                | Cross::F64
                | Cross::Bool => {
                    let t = rust_c_member_type(inner);
                    decls.push(format!("{name}: *const {t}"));
                    conv.push(format!(
                        "let {name} = if {name}.is_null() {{ None }} else {{ Some(*{name}) }};"
                    ));
                }
                Cross::Enum(e) => {
                    decls.push(format!("{name}: *const i32"));
                    conv.push(format!(
                        "let {name} = if {name}.is_null() {{ None }} else {{ Some({e}::from_c(*{name})) }};"
                    ));
                }
                Cross::Str | Cross::StrEnum | Cross::Union => {
                    decls.push(format!("{name}: *const c_char"));
                    conv.push(format!(
                        "let {name} = if {name}.is_null() {{ None }} else {{ Some(fl_str_in({name})) }};"
                    ));
                }
                Cross::Model(m) => {
                    decls.push(format!("{name}: *const {}", c_model_name(m)));
                    conv.push(format!(
                        "let {name} = if {name}.is_null() {{ None }} else {{ Some({}_from_c(&*{name})) }};",
                        snake(m)
                    ));
                }
                _ => {
                    decls.push(format!("{name}: *const c_char"));
                    conv.push(format!(
                        "let {name} = if {name}.is_null() {{ None }} else {{ Some(fl_str_in({name})) }};"
                    ));
                }
            };
        }
        Cross::Void => {}
    }
}

/// Render the OUT params for a return crossing: the Rust extern decls plus the
/// write statement given a value binding `v`.
fn rust_out(c: &Cross) -> (Vec<String>, String) {
    match c {
        Cross::Void => (Vec::new(), String::new()),
        Cross::I32
        | Cross::I64
        | Cross::U8
        | Cross::U16
        | Cross::U32
        | Cross::F32
        | Cross::F64
        | Cross::Bool => (
            vec![format!("out: *mut {}", rust_c_member_type(c))],
            "*out = v;".into(),
        ),
        Cross::Enum(_) => (vec!["out: *mut i32".into()], "*out = v as i32;".into()),
        Cross::Str | Cross::StrEnum | Cross::Union => (
            vec!["out: *mut *mut c_char".into()],
            "*out = fl_str_out(v);".into(),
        ),
        Cross::Bytes => (
            vec!["out: *mut FlBytes".into()],
            "*out = fl_bytes_out(v);".into(),
        ),
        Cross::Model(m) => (
            vec![format!("out: *mut {}", c_model_name(m))],
            format!("*out = {}_to_c(v);", snake(m)),
        ),
        Cross::List(inner) => {
            let token = list_elem_token(inner);
            (
                vec![format!("out: *mut {}", c_list_name(&token))],
                format!("*out = {}_list_out(v);", snake(&token)),
            )
        }
        Cross::Nullable(inner) => {
            let (inner_decls, inner_write) = rust_out(inner);
            let mut decls = vec!["has_out: *mut bool".to_string()];
            decls.extend(inner_decls);
            let write = format!(
                "match v {{ Some(v) => {{ *has_out = true; {inner_write} }} None => {{ *has_out = false; }} }}"
            );
            (decls, write)
        }
    }
}

// ── per-interface emission ───────────────────────────────────────────────────

fn emit_interface(api: &ApiDoc, i: &crate::api::ApiInterface) -> String {
    let has_ctor = i.ops.iter().any(|o| o.shape == Shape::Ctor);
    let trait_name = format!("{}Core", i.name);
    let impl_path = format!("crate::core_impl::{}Impl", i.name);
    let mut s = String::new();

    if let Some(doc) = &i.doc {
        for line in doc.lines() {
            s.push_str(&format!("/// {line}\n"));
        }
    }

    // stream cursor wrappers + next/close (one per stream op)
    for op in i.ops.iter().filter(|o| o.shape == Shape::Stream) {
        s.push_str(&emit_stream(api, &i.name, op));
        s.push('\n');
    }

    if has_ctor {
        // opaque handle typedef comment + new/free + methods
        s.push_str(&format!(
            "// Stateful `{0}` handle → `Box<{impl_path}>` behind a raw pointer.\n",
            i.name
        ));
        for op in &i.ops {
            match op.shape {
                Shape::Ctor => s.push_str(&emit_ctor(api, &i.name, op, &impl_path, &trait_name)),
                Shape::Unary => {
                    s.push_str(&emit_unary(api, &i.name, op, &impl_path, &trait_name, true))
                }
                Shape::Stream => s.push_str(&emit_stream_open(api, &i.name, op, &impl_path)),
                // Full Subscription (register/unsubscribe) lowering is deferred to a
                // follow-up PR for cpp; emit a skip-note so the op is recorded but
                // not auto-bound, keeping the crate compiling.
                Shape::Subscription => s.push_str(&format!(
                    "// subscription {}::{} — register/unsubscribe lowering deferred (node/python only today).\n",
                    i.name, op.name
                )),
                Shape::Manual => s.push_str(&format!(
                    "// @manual {}::{} — hand-written by the consumer.\n",
                    i.name, op.name
                )),
            }
            s.push('\n');
        }
        // free
        s.push_str(&format!(
            "/// Release the `{0}` handle.\n#[no_mangle]\npub unsafe extern \"C\" fn {0}_free(p: *mut {impl_path}) {{\n    if !p.is_null() {{\n        drop(Box::from_raw(p));\n    }}\n}}\n",
            i.name
        ));
    } else {
        // stateless: free functions (static calls through the core trait)
        s.push_str(&format!("// Stateless `{0}` — free functions.\n", i.name));
        for op in &i.ops {
            match op.shape {
                Shape::Unary => s.push_str(&emit_unary(
                    api,
                    &i.name,
                    op,
                    &impl_path,
                    &trait_name,
                    false,
                )),
                Shape::Stream => s.push_str(&emit_stream_open(api, &i.name, op, &impl_path)),
                // Subscription lowering deferred to a follow-up PR for cpp (a
                // subscription op is `&self` on a stateful interface, so it never
                // reaches this stateless arm — recorded for completeness).
                Shape::Subscription => s.push_str(&format!(
                    "// subscription {}::{} — register/unsubscribe lowering deferred (node/python only today).\n",
                    i.name, op.name
                )),
                Shape::Manual => s.push_str(&format!(
                    "// @manual {}::{} — hand-written by the consumer.\n",
                    i.name, op.name
                )),
                Shape::Ctor => {}
            }
            s.push('\n');
        }
    }
    s
}

/// The stream cursor wrapper struct + `_next` + `_close`.
fn emit_stream(api: &ApiDoc, iface: &str, op: &ApiOp) -> String {
    let cursor = c_stream_name(iface, op);
    let (item_rust, _) = ty(api, &op.returns);
    let item_c = classify(api, &op.returns);
    let item_c_ty = c_value_type_rust(&item_c);
    let write = stream_item_write(&item_c);
    let mut s = String::new();
    s.push_str(&format!(
        "/// Poll-based cursor for `{iface}.{}` — call `_next` until it reports Closed.\n",
        op.name
    ));
    s.push_str(&format!(
        "pub struct {cursor}(Box<dyn PollStream<{item_rust}>>);\n\n"
    ));
    s.push_str("/// Pull the next item. On ITEM sets `*item_out`; on FAILED sets `*err_out`.\n");
    s.push_str(&format!(
        "#[no_mangle]\npub unsafe extern \"C\" fn {cursor}_next(s: *mut {cursor}, timeout_ms: u32, item_out: *mut {item_c_ty}, err_out: *mut *mut c_char) -> FlPoll {{\n"
    ));
    s.push_str("    let s = &*s;\n");
    s.push_str("    match s.0.poll(Duration::from_millis(timeout_ms as u64)) {\n");
    s.push_str(&format!(
        "        Poll::Item(v) => {{ {write} FlPoll::Item }}\n"
    ));
    s.push_str("        Poll::Idle => FlPoll::Idle,\n");
    s.push_str("        Poll::Closed => FlPoll::Closed,\n");
    s.push_str("        Poll::Failed(e) => { if !err_out.is_null() { *err_out = fl_str_out(e); } FlPoll::Failed }\n");
    s.push_str("    }\n}\n\n");
    s.push_str(&format!(
        "/// Close and free the cursor.\n#[no_mangle]\npub unsafe extern \"C\" fn {cursor}_close(s: *mut {cursor}) {{\n    if !s.is_null() {{\n        let s = Box::from_raw(s);\n        s.0.close();\n    }}\n}}\n"
    ));
    s
}

/// The Rust extern type for a stream `item_out` pointer target.
fn c_value_type_rust(c: &Cross) -> String {
    match c {
        Cross::I32 | Cross::Enum(_) => "i32".into(),
        Cross::I64 => "i64".into(),
        Cross::U8 => "u8".into(),
        Cross::U16 => "u16".into(),
        Cross::U32 => "u32".into(),
        Cross::F32 => "f32".into(),
        Cross::F64 => "f64".into(),
        Cross::Bool => "bool".into(),
        Cross::Str | Cross::StrEnum | Cross::Union => "*mut c_char".into(),
        Cross::Bytes => "FlBytes".into(),
        Cross::Model(m) => c_model_name(m),
        Cross::List(inner) => c_list_name(&list_elem_token(inner)),
        Cross::Nullable(inner) => c_value_type_rust(inner),
        Cross::Void => "()".into(),
    }
}

/// The write statement for a stream item (`v` in scope, `item_out` the target).
fn stream_item_write(c: &Cross) -> String {
    match c {
        Cross::I32
        | Cross::I64
        | Cross::U8
        | Cross::U16
        | Cross::U32
        | Cross::F32
        | Cross::F64
        | Cross::Bool => "*item_out = v;".into(),
        Cross::Enum(_) => "*item_out = v as i32;".into(),
        Cross::Str | Cross::StrEnum | Cross::Union => "*item_out = fl_str_out(v);".into(),
        Cross::Bytes => "*item_out = fl_bytes_out(v);".into(),
        Cross::Model(m) => format!("*item_out = {}_to_c(v);", snake(m)),
        _ => "*item_out = Default::default();".into(),
    }
}

/// A ctor: `<Iface>_new(<in>, out, err_out) -> c_int`.
fn emit_ctor(api: &ApiDoc, iface: &str, op: &ApiOp, impl_path: &str, trait_name: &str) -> String {
    let (decls, conv, names) = rust_in_params(api, op);
    let mut sig = decls.join(", ");
    if !sig.is_empty() {
        sig.push_str(", ");
    }
    let mut s = String::new();
    if let Some(doc) = &op.doc {
        for line in doc.lines() {
            s.push_str(&format!("/// {line}\n"));
        }
    }
    s.push_str(&format!(
        "/// Construct a `{iface}` (ctor `{}`).\n",
        op.name
    ));
    s.push_str(&format!(
        "#[no_mangle]\npub unsafe extern \"C\" fn {iface}_new({sig}out: *mut *mut {impl_path}, err_out: *mut *mut c_char) -> c_int {{\n"
    ));
    for c in &conv {
        s.push_str(&format!("    {c}\n"));
    }
    s.push_str(&format!(
        "    match <{impl_path} as {trait_name}>::{}({}) {{\n",
        snake(&op.name),
        names.join(", ")
    ));
    s.push_str("        Ok(v) => {\n            *out = Box::into_raw(Box::new(v));\n            if !err_out.is_null() { *err_out = std::ptr::null_mut(); }\n            0\n        }\n");
    s.push_str("        Err(e) => {\n            if !err_out.is_null() { *err_out = fl_str_out(e.to_string()); }\n            1\n        }\n");
    s.push_str("    }\n}\n");
    s
}

/// A unary op — fallible (`int` + `err_out`) or infallible (value direct). The
/// `stateful` flag adds the `self_` receiver and routes through the boxed core.
fn emit_unary(
    api: &ApiDoc,
    iface: &str,
    op: &ApiOp,
    impl_path: &str,
    trait_name: &str,
    stateful: bool,
) -> String {
    let sym = op_symbol(iface, op);
    let (decls, conv, names) = rust_in_params(api, op);
    let ret = classify(api, &op.returns);
    let (out_decls, out_write) = rust_out(&ret);

    let mut s = String::new();
    if let Some(doc) = &op.doc {
        for line in doc.lines() {
            s.push_str(&format!("/// {line}\n"));
        }
    }
    if op.is_async {
        s.push_str("// The C ABI is synchronous; this op's `async` label is a no-op here (the core is sync).\n");
    }

    // The receiver + call target.
    let (recv_decl, call) = if stateful {
        (
            "self_: *mut ".to_string() + impl_path + ", ",
            format!("this.{}", snake(&op.name)),
        )
    } else {
        (
            String::new(),
            format!("<{impl_path} as {trait_name}>::{}", snake(&op.name)),
        )
    };
    let bind_this = if stateful {
        "    let this = &*self_;\n"
    } else {
        ""
    };

    let mut in_sig = decls.join(", ");
    if !in_sig.is_empty() {
        in_sig.push_str(", ");
    }

    if op.infallible {
        // TODO(#69): an infallible op returns its value directly — NO status,
        // NO err_out. This is the sync/infallible axis from PR #69.
        s.push_str("// TODO(#69): infallible op — value returned directly, no err_out.\n");
        match &ret {
            Cross::Void => {
                s.push_str(&format!(
                    "#[no_mangle]\npub unsafe extern \"C\" fn {sym}({recv_decl}{}) {{\n",
                    decls.join(", ")
                ));
                s.push_str(bind_this);
                for c in &conv {
                    s.push_str(&format!("    {c}\n"));
                }
                s.push_str(&format!("    {call}({});\n", names.join(", ")));
                s.push_str("}\n");
            }
            Cross::I32
            | Cross::I64
            | Cross::U8
            | Cross::U16
            | Cross::U32
            | Cross::F32
            | Cross::F64
            | Cross::Bool
            | Cross::Enum(_)
            | Cross::Str
            | Cross::StrEnum
            | Cross::Union => {
                let (rty, wrap) = infallible_scalar_return(&ret);
                s.push_str(&format!(
                    "#[no_mangle]\npub unsafe extern \"C\" fn {sym}({recv_decl}{}) -> {rty} {{\n",
                    decls.join(", ")
                ));
                s.push_str(bind_this);
                for c in &conv {
                    s.push_str(&format!("    {c}\n"));
                }
                s.push_str(&format!(
                    "    let v = {call}({});\n    {wrap}\n",
                    names.join(", ")
                ));
                s.push_str("}\n");
            }
            _ => {
                // infallible non-void compound → single out-param, void return.
                s.push_str(&format!(
                    "#[no_mangle]\npub unsafe extern \"C\" fn {sym}({recv_decl}{in_sig}{}) {{\n",
                    out_decls.join(", ")
                ));
                s.push_str(bind_this);
                for c in &conv {
                    s.push_str(&format!("    {c}\n"));
                }
                s.push_str(&format!(
                    "    let v = {call}({});\n    {out_write}\n",
                    names.join(", ")
                ));
                s.push_str("}\n");
            }
        }
        return s;
    }

    // Fallible: `int` status + trailing `err_out`, non-void through out-params.
    let mut out_sig = out_decls.join(", ");
    if !out_sig.is_empty() {
        out_sig.push_str(", ");
    }
    s.push_str(&format!(
        "#[no_mangle]\npub unsafe extern \"C\" fn {sym}({recv_decl}{in_sig}{out_sig}err_out: *mut *mut c_char) -> c_int {{\n"
    ));
    s.push_str(bind_this);
    for c in &conv {
        s.push_str(&format!("    {c}\n"));
    }
    s.push_str(&format!("    match {call}({}) {{\n", names.join(", ")));
    if matches!(ret, Cross::Void) {
        s.push_str("        Ok(()) => {\n            if !err_out.is_null() { *err_out = std::ptr::null_mut(); }\n            0\n        }\n");
    } else {
        s.push_str(&format!(
            "        Ok(v) => {{\n            {out_write}\n            if !err_out.is_null() {{ *err_out = std::ptr::null_mut(); }}\n            0\n        }}\n"
        ));
    }
    s.push_str("        Err(e) => {\n            if !err_out.is_null() { *err_out = fl_str_out(e.to_string()); }\n            1\n        }\n");
    s.push_str("    }\n}\n");
    s
}

/// The Rust return type + wrap expression for an infallible scalar/string return.
fn infallible_scalar_return(c: &Cross) -> (String, String) {
    match c {
        Cross::I32 => ("i32".into(), "v".into()),
        Cross::I64 => ("i64".into(), "v".into()),
        Cross::U8 => ("u8".into(), "v".into()),
        Cross::U16 => ("u16".into(), "v".into()),
        Cross::U32 => ("u32".into(), "v".into()),
        Cross::F32 => ("f32".into(), "v".into()),
        Cross::F64 => ("f64".into(), "v".into()),
        Cross::Bool => ("bool".into(), "v".into()),
        Cross::Enum(_) => ("i32".into(), "v as i32".into()),
        _ => ("*mut c_char".into(), "fl_str_out(v)".into()),
    }
}

/// A stream-open op: `<Iface>_<op>(self_, <in>, out: **Cursor, err_out) -> c_int`.
fn emit_stream_open(api: &ApiDoc, iface: &str, op: &ApiOp, impl_path: &str) -> String {
    let sym = op_symbol(iface, op);
    let cursor = c_stream_name(iface, op);
    let (decls, conv, names) = rust_in_params(api, op);
    let stateful = api
        .interfaces
        .iter()
        .find(|i| i.name == iface)
        .map(|i| i.ops.iter().any(|o| o.shape == Shape::Ctor))
        .unwrap_or(false);
    let (recv_decl, call) = if stateful {
        (
            "self_: *mut ".to_string() + impl_path + ", ",
            format!("this.{}", snake(&op.name)),
        )
    } else {
        (
            String::new(),
            format!("<{impl_path} as {iface}Core>::{}", snake(&op.name)),
        )
    };
    let bind_this = if stateful {
        "    let this = &*self_;\n"
    } else {
        ""
    };
    let mut in_sig = decls.join(", ");
    if !in_sig.is_empty() {
        in_sig.push_str(", ");
    }
    let mut s = String::new();
    if let Some(doc) = &op.doc {
        for line in doc.lines() {
            s.push_str(&format!("/// {line}\n"));
        }
    }
    s.push_str(&format!(
        "/// Open the `{iface}.{}` stream (returns a cursor handle).\n",
        op.name
    ));
    s.push_str(&format!(
        "#[no_mangle]\npub unsafe extern \"C\" fn {sym}({recv_decl}{in_sig}out: *mut *mut {cursor}, err_out: *mut *mut c_char) -> c_int {{\n"
    ));
    s.push_str(bind_this);
    for c in &conv {
        s.push_str(&format!("    {c}\n"));
    }
    s.push_str(&format!("    match {call}({}) {{\n", names.join(", ")));
    s.push_str(&format!(
        "        Ok(stream) => {{\n            *out = Box::into_raw(Box::new({cursor}(stream)));\n            if !err_out.is_null() {{ *err_out = std::ptr::null_mut(); }}\n            0\n        }}\n"
    ));
    s.push_str("        Err(e) => {\n            if !err_out.is_null() { *err_out = fl_str_out(e.to_string()); }\n            1\n        }\n");
    s.push_str("    }\n}\n");
    s
}
