//! The C++ RAII wrapper (`.hpp`) — `#include`s the C header, wraps opaque
//! handles in move-only classes, maps `std::string`/`std::vector`, and throws
//! `fluessig::Error` on fallible failure. NOT Rust; not run through rustfmt.
//!
//! straitjacket-allow-file:duplication — the per-language generators are
//! DELIBERATELY parallel: the (language × shape) template grid is the design
//! (see /translation.md); the truly shared pieces live in the parent module.

use crate::api::{ApiDoc, ApiOp, Shape};

use super::cpp::{
    c_model_name, c_stream_name, classify, classify_param, cpp_value_type, op_symbol, Cross,
};
use super::*;

/// The C++ value type a return/param crossing surfaces as.
fn cpp_ty(c: &Cross) -> String {
    cpp_value_type(c)
}

/// Convert a C++ argument expression `name` into the C call argument(s).
fn cpp_arg(c: &Cross, name: &str) -> String {
    match c {
        Cross::Str | Cross::StrEnum | Cross::Union => format!("{name}.c_str()"),
        Cross::Bytes => format!("FlBytes{{const_cast<uint8_t*>({name}.data()), {name}.size()}}"),
        Cross::Model(_) => format!("&{name}"),
        Cross::List(_) => format!("{name}.data(), {name}.size()"),
        Cross::Nullable(inner) => match inner.as_ref() {
            Cross::Str | Cross::StrEnum | Cross::Union => {
                format!("{name} ? {name}->c_str() : nullptr")
            }
            Cross::Model(_) => format!("{name} ? &*{name} : nullptr"),
            _ => format!("{name} ? &*{name} : nullptr"),
        },
        _ => name.to_string(),
    }
}

/// Generate the C++ header string.
pub fn cpp_hpp(api: &ApiDoc, _enums: &[EnumDesc], banner_note: Option<&str>) -> String {
    let src = api.source.as_deref().unwrap_or("fluessig");
    let guard = format!(
        "FLUESSIG_{}_HPP",
        src.chars()
            .map(|c| if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            })
            .collect::<String>()
    );
    let header = src
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect::<String>();

    let mut s = String::new();
    s.push_str(&format!(
        "// GENERATED by fluessig bindgen from {src} (C++ wrapper). Do not edit.\n"
    ));
    if let Some(n) = banner_note {
        s.push_str(&format!("// {n}\n"));
    }
    s.push_str(&format!("#ifndef {guard}\n#define {guard}\n\n"));
    s.push_str(&format!("#include \"{header}.h\"\n"));
    s.push_str("#include <string>\n#include <vector>\n#include <optional>\n#include <stdexcept>\n#include <utility>\n\n");
    s.push_str("namespace fluessig {\n\n");

    // ── Error ──
    s.push_str("/// A fallible-op failure. Carries the C error message; the C\n");
    s.push_str("/// buffer is freed once copied into this exception.\n");
    s.push_str("struct Error : std::runtime_error {\n");
    s.push_str("    explicit Error(char* msg)\n");
    s.push_str("        : std::runtime_error(msg ? std::string(msg) : std::string()) {\n");
    s.push_str("        if (msg) { fl_error_free(msg); }\n");
    s.push_str("    }\n};\n\n");

    // ── Poll status mirror ──
    s.push_str("/// The pull-cursor poll status (mirrors FlPoll).\n");
    s.push_str("enum class Poll { Item = FL_POLL_ITEM, Idle = FL_POLL_IDLE, Closed = FL_POLL_CLOSED, Failed = FL_POLL_FAILED };\n\n");
    s.push_str(
        "// Unions cross as their JSON envelope text — the C++ surface exposes std::string.\n\n",
    );

    // ── stream cursor classes ──
    for i in &api.interfaces {
        for op in i.ops.iter().filter(|o| o.shape == Shape::Stream) {
            s.push_str(&emit_cursor_class(api, &i.name, op));
            s.push('\n');
        }
    }

    // ── per-interface class / free-function surface ──
    for i in &api.interfaces {
        let has_ctor = i.ops.iter().any(|o| o.shape == Shape::Ctor);
        if has_ctor {
            s.push_str(&emit_handle_class(api, i));
        } else {
            s.push_str(&emit_stateless(api, i));
        }
        s.push('\n');
    }

    s.push_str("} // namespace fluessig\n\n");
    s.push_str(&format!("#endif // {guard}\n"));
    s
}

/// A move-only `Cursor` wrapping the C stream handle.
fn emit_cursor_class(api: &ApiDoc, iface: &str, op: &ApiOp) -> String {
    let cur = c_stream_name(iface, op);
    let item = classify(api, &op.returns);
    let item_c = c_item_type(&item);
    let item_cpp = cpp_ty(&item);
    let mut s = String::new();
    s.push_str(&format!(
        "/// RAII pull cursor for `{iface}.{}`.\n",
        op.name
    ));
    s.push_str(&format!("class {cur}Cursor {{\npublic:\n"));
    s.push_str(&format!(
        "    explicit {cur}Cursor(::{cur}* h) : h_(h) {{}}\n"
    ));
    s.push_str(&format!(
        "    {cur}Cursor({cur}Cursor&& o) noexcept : h_(o.h_) {{ o.h_ = nullptr; }}\n"
    ));
    s.push_str(&format!("    {cur}Cursor(const {cur}Cursor&) = delete;\n"));
    s.push_str(&format!(
        "    {cur}Cursor& operator=(const {cur}Cursor&) = delete;\n"
    ));
    s.push_str(&format!(
        "    ~{cur}Cursor() {{ if (h_) {{ ::{cur}_close(h_); }} }}\n\n"
    ));
    // poll: returns Poll status, sets out on ITEM
    s.push_str(&format!(
        "    Poll poll({item_cpp}& out, uint32_t timeout_ms) {{\n"
    ));
    s.push_str(&format!("        {item_c} item{{}};\n"));
    s.push_str("        char* err = nullptr;\n");
    s.push_str(&format!(
        "        FlPoll p = ::{cur}_next(h_, timeout_ms, &item, &err);\n"
    ));
    s.push_str("        if (p == FL_POLL_FAILED) { throw Error(err); }\n");
    s.push_str(&format!(
        "        if (p == FL_POLL_ITEM) {{ out = {}; }}\n",
        item_from_c(&item)
    ));
    s.push_str("        return static_cast<Poll>(p);\n    }\n\n");
    // next: optional sugar
    s.push_str(&format!(
        "    std::optional<{item_cpp}> next(uint32_t timeout_ms = 500) {{\n"
    ));
    s.push_str(&format!("        {item_cpp} out{{}};\n"));
    s.push_str("        Poll p = poll(out, timeout_ms);\n");
    s.push_str("        if (p == Poll::Item) { return out; }\n");
    s.push_str("        return std::nullopt; // Idle or Closed\n    }\n\n");
    s.push_str("private:\n");
    s.push_str(&format!("    ::{cur}* h_;\n}};\n"));
    s
}

/// The C item type used in the cursor's `_next` out-param.
fn c_item_type(c: &Cross) -> String {
    match c {
        Cross::I32 | Cross::Enum(_) => "int32_t".into(),
        Cross::I64 => "int64_t".into(),
        Cross::F64 => "double".into(),
        Cross::Bool => "bool".into(),
        Cross::Str | Cross::StrEnum | Cross::Union => "char*".into(),
        Cross::Bytes => "FlBytes".into(),
        Cross::Model(m) => c_model_name(m),
        _ => "int32_t".into(),
    }
}

/// Expression converting a C stream item `item` into the C++ value.
fn item_from_c(c: &Cross) -> String {
    match c {
        Cross::Str | Cross::StrEnum | Cross::Union => {
            "[&]{ std::string r(item ? item : \"\"); fl_string_free(item); return r; }()".into()
        }
        _ => "item".into(),
    }
}

/// A move-only class wrapping a stateful interface's opaque handle.
fn emit_handle_class(api: &ApiDoc, i: &crate::api::ApiInterface) -> String {
    let iface = &i.name;
    let mut s = String::new();
    if let Some(doc) = &i.doc {
        for line in doc.lines() {
            s.push_str(&format!("/// {line}\n"));
        }
    }
    s.push_str(&format!("class {iface} {{\npublic:\n"));

    // constructor from the ctor op
    if let Some(ctor) = i.ops.iter().find(|o| o.shape == Shape::Ctor) {
        let params = cpp_params(api, ctor);
        let args = cpp_call_args(api, ctor);
        let arg_sep = if args.is_empty() { "" } else { ", " };
        s.push_str(&format!("    explicit {iface}({params}) {{\n"));
        s.push_str("        char* err = nullptr;\n");
        s.push_str(&format!(
            "        if (::{iface}_new({args}{arg_sep}&h_, &err)) {{ throw Error(err); }}\n"
        ));
        s.push_str("    }\n");
    }
    // lifecycle
    s.push_str(&format!(
        "    {iface}({iface}&& o) noexcept : h_(o.h_) {{ o.h_ = nullptr; }}\n"
    ));
    s.push_str(&format!("    {iface}(const {iface}&) = delete;\n"));
    s.push_str(&format!(
        "    {iface}& operator=(const {iface}&) = delete;\n"
    ));
    s.push_str(&format!(
        "    ~{iface}() {{ if (h_) {{ ::{iface}_free(h_); }} }}\n\n"
    ));

    // methods
    for op in &i.ops {
        match op.shape {
            Shape::Ctor => {}
            Shape::Manual => s.push_str(&format!(
                "    // @manual {iface}::{} — hand-written by the consumer.\n",
                op.name
            )),
            Shape::Stream => s.push_str(&emit_stream_method(api, iface, op, true)),
            Shape::Unary => s.push_str(&emit_unary_method(api, iface, op, true)),
        }
    }

    s.push_str("\nprivate:\n");
    s.push_str(&format!("    ::{iface}* h_ = nullptr;\n}};\n"));
    s
}

/// A stateless interface → a namespace of free functions.
fn emit_stateless(api: &ApiDoc, i: &crate::api::ApiInterface) -> String {
    let iface = &i.name;
    let mut s = String::new();
    if let Some(doc) = &i.doc {
        for line in doc.lines() {
            s.push_str(&format!("/// {line}\n"));
        }
    }
    s.push_str(&format!("namespace {} {{\n", snake(iface)));
    for op in &i.ops {
        match op.shape {
            Shape::Manual => s.push_str(&format!(
                "// @manual {iface}::{} — hand-written by the consumer.\n",
                op.name
            )),
            Shape::Stream => s.push_str(&emit_stream_method(api, iface, op, false)),
            Shape::Unary => s.push_str(&emit_unary_method(api, iface, op, false)),
            Shape::Ctor => {}
        }
    }
    s.push_str(&format!("}} // namespace {}\n", snake(iface)));
    s
}

/// The C++ parameter list for an op.
fn cpp_params(api: &ApiDoc, op: &ApiOp) -> String {
    op.params
        .iter()
        .map(|p| format!("{} {}", cpp_ty(&classify_param(api, p)), snake(&p.name)))
        .collect::<Vec<_>>()
        .join(", ")
}

/// The C call arguments (C++ values converted to C) for an op.
fn cpp_call_args(api: &ApiDoc, op: &ApiOp) -> String {
    op.params
        .iter()
        .map(|p| cpp_arg(&classify_param(api, p), &snake(&p.name)))
        .collect::<Vec<_>>()
        .join(", ")
}

/// A unary method — throws `Error` on failure (fallible) or returns directly
/// (infallible). `member` toggles the `::<Iface>_<op>(h_, …)` receiver.
fn emit_unary_method(api: &ApiDoc, iface: &str, op: &ApiOp, member: bool) -> String {
    let sym = op_symbol(iface, op);
    let ret = classify(api, &op.returns);
    let rty = cpp_ty(&ret);
    let params = cpp_params(api, op);
    let args = cpp_call_args(api, op);
    let recv = if member {
        "h_".to_string()
    } else {
        String::new()
    };
    let mut call_args = Vec::new();
    if member {
        call_args.push(recv);
    }
    if !args.is_empty() {
        call_args.push(args);
    }
    let lead = call_args.join(", ");
    let sep = if lead.is_empty() { "" } else { ", " };
    let kw = if member { "    " } else { "inline " };
    let name = snake(&op.name);
    let mut s = String::new();
    if let Some(doc) = &op.doc {
        for line in doc.lines() {
            s.push_str(&format!("{kw}/// {line}\n"));
        }
    }

    if op.infallible {
        // TODO(#69): infallible op — value returned directly, no err channel.
        match &ret {
            Cross::Void => {
                s.push_str(&format!("{kw}void {name}({params}) {{\n"));
                s.push_str(&format!("{kw}    ::{sym}({lead});\n{kw}}}\n"));
            }
            _ => {
                s.push_str(&format!("{kw}{rty} {name}({params}) {{\n"));
                s.push_str(&format!("{kw}    return ::{sym}({lead});\n{kw}}}\n"));
            }
        }
        return s;
    }

    match &ret {
        Cross::Void => {
            s.push_str(&format!("{kw}void {name}({params}) {{\n"));
            s.push_str(&format!("{kw}    char* err = nullptr;\n"));
            s.push_str(&format!(
                "{kw}    if (::{sym}({lead}{sep}&err)) {{ throw Error(err); }}\n{kw}}}\n"
            ));
        }
        Cross::Str | Cross::StrEnum | Cross::Union => {
            s.push_str(&format!("{kw}std::string {name}({params}) {{\n"));
            s.push_str(&format!(
                "{kw}    char* out = nullptr;\n{kw}    char* err = nullptr;\n"
            ));
            s.push_str(&format!(
                "{kw}    if (::{sym}({lead}{sep}&out, &err)) {{ throw Error(err); }}\n"
            ));
            s.push_str(&format!(
                "{kw}    std::string r(out ? out : \"\");\n{kw}    fl_string_free(out);\n{kw}    return r;\n{kw}}}\n"
            ));
        }
        Cross::Nullable(inner) => {
            let inner_cpp = cpp_ty(inner);
            let out_c = c_item_type(inner);
            s.push_str(&format!(
                "{kw}std::optional<{inner_cpp}> {name}({params}) {{\n"
            ));
            s.push_str(&format!("{kw}    bool has = false;\n{kw}    {out_c} out{{}};\n{kw}    char* err = nullptr;\n"));
            s.push_str(&format!(
                "{kw}    if (::{sym}({lead}{sep}&has, &out, &err)) {{ throw Error(err); }}\n"
            ));
            s.push_str(&format!("{kw}    if (!has) {{ return std::nullopt; }}\n"));
            s.push_str(&format!("{kw}    return out;\n{kw}}}\n"));
        }
        _ => {
            // scalar / enum / model / bytes / list: single out-param.
            let out_c = c_item_type(&ret);
            s.push_str(&format!("{kw}{rty} {name}({params}) {{\n"));
            s.push_str(&format!(
                "{kw}    {out_c} out{{}};\n{kw}    char* err = nullptr;\n"
            ));
            s.push_str(&format!(
                "{kw}    if (::{sym}({lead}{sep}&out, &err)) {{ throw Error(err); }}\n"
            ));
            s.push_str(&format!("{kw}    return out;\n{kw}}}\n"));
        }
    }
    s
}

/// A stream method returning a `…Cursor`.
fn emit_stream_method(api: &ApiDoc, iface: &str, op: &ApiOp, member: bool) -> String {
    let sym = op_symbol(iface, op);
    let cur = c_stream_name(iface, op);
    let params = cpp_params(api, op);
    let args = cpp_call_args(api, op);
    let recv = if member {
        "h_".to_string()
    } else {
        String::new()
    };
    let mut call_args = Vec::new();
    if member {
        call_args.push(recv);
    }
    if !args.is_empty() {
        call_args.push(args);
    }
    let lead = call_args.join(", ");
    let sep = if lead.is_empty() { "" } else { ", " };
    let kw = if member { "    " } else { "inline " };
    let name = snake(&op.name);
    let mut s = String::new();
    if let Some(doc) = &op.doc {
        for line in doc.lines() {
            s.push_str(&format!("{kw}/// {line}\n"));
        }
    }
    s.push_str(&format!("{kw}{cur}Cursor {name}({params}) {{\n"));
    s.push_str(&format!(
        "{kw}    ::{cur}* out = nullptr;\n{kw}    char* err = nullptr;\n"
    ));
    s.push_str(&format!(
        "{kw}    if (::{sym}({lead}{sep}&out, &err)) {{ throw Error(err); }}\n"
    ));
    s.push_str(&format!("{kw}    return {cur}Cursor(out);\n{kw}}}\n"));
    s
}
