//! The C++ RAII wrapper (`.hpp`) — `#include`s the C header, wraps opaque
//! handles in move-only classes, maps `std::string`/`std::vector`, and throws
//! `fluessig::Error` on fallible failure. NOT Rust; not run through rustfmt.
//!
//! straitjacket-allow-file:duplication — the per-language generators are
//! DELIBERATELY parallel: the (language × shape) template grid is the design
//! (see /translation.md); the truly shared pieces live in the parent module.

use crate::api::{ApiDoc, ApiOp, ApiType, Shape};

use super::cpp::{
    c_enum_name, c_list_name, c_model_name, c_stream_name, classify, classify_param,
    cpp_value_type, list_elem_token, op_symbol, Cross,
};
use super::*;

/// The C++ value type a return/param crossing surfaces as.
fn cpp_ty(c: &Cross) -> String {
    cpp_value_type(c)
}

/// Convert a C++ argument expression `name` into the C call argument(s).
fn cpp_arg(c: &Cross, name: &str) -> String {
    match c {
        Cross::Str | Cross::StrEnum | Cross::Union => format!("{name}.c_str()"),
        Cross::Bytes => format!("FlBytes{{const_cast<uint8_t*>({name}.data()), {name}.size()}}"),
        Cross::Model(_) => format!("&{name}"),
        Cross::List(_) => format!("{name}.data(), {name}.size()"),
        Cross::Nullable(inner) => match inner.as_ref() {
            Cross::Str | Cross::StrEnum | Cross::Union => {
                format!("{name} ? {name}->c_str() : nullptr")
            }
            Cross::Model(_) => format!("{name} ? &*{name} : nullptr"),
            _ => format!("{name} ? &*{name} : nullptr"),
        },
        _ => name.to_string(),
    }
}

/// Generate the C++ header string.
pub fn cpp_hpp(api: &ApiDoc, _enums: &[EnumDesc], banner_note: Option<&str>) -> String {
    // A `single_threaded` interface is a thread-confined `!Send` handle — node-only
    // today; the C ABI cdylib emits nothing for it, so this C++ wrapper header must
    // not declare its handle class either. Split it out + note it honestly.
    let (api_owned, st_note) = crate::bindgen::split_single_threaded(api, "cpp");
    let api = &api_owned;
    let src = api.source.as_deref().unwrap_or("fluessig");
    let guard = format!(
        "FLUESSIG_{}_HPP",
        src.chars()
            .map(|c| if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            })
            .collect::<String>()
    );
    let header = src
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect::<String>();

    let mut s = String::new();
    s.push_str(&format!(
        "// GENERATED by fluessig bindgen from {src} (C++ wrapper). Do not edit.\n"
    ));
    if let Some(n) = banner_note {
        s.push_str(&format!("// {n}\n"));
    }
    s.push_str(&format!("#ifndef {guard}\n#define {guard}\n\n"));
    s.push_str(&format!("#include \"{header}.h\"\n"));
    s.push_str("#include <string>\n#include <vector>\n#include <optional>\n#include <stdexcept>\n#include <utility>\n");
    // A subscription op's C++ method takes a `std::function` listener.
    if api_uses_subscription(api) {
        s.push_str("#include <functional>\n");
    }
    s.push('\n');
    s.push_str("namespace fluessig {\n\n");

    // ── Error ──
    s.push_str("/// A fallible-op failure. Carries the C error message; the C\n");
    s.push_str("/// buffer is freed once copied into this exception.\n");
    s.push_str("struct Error : std::runtime_error {\n");
    s.push_str("    explicit Error(char* msg)\n");
    s.push_str("        : std::runtime_error(msg ? std::string(msg) : std::string()) {\n");
    s.push_str("        if (msg) { fl_error_free(msg); }\n");
    s.push_str("    }\n};\n\n");

    // ── Poll status mirror ──
    s.push_str("/// The pull-cursor poll status (mirrors FlPoll).\n");
    s.push_str("enum class Poll { Item = FL_POLL_ITEM, Idle = FL_POLL_IDLE, Closed = FL_POLL_CLOSED, Failed = FL_POLL_FAILED };\n\n");
    s.push_str(
        "// Unions cross as their JSON envelope text — the C++ surface exposes std::string.\n\n",
    );

    // ── Subscription RAII wrapper (once, gated) ──
    if api_uses_subscription(api) {
        s.push_str(&subscription_class());
        s.push('\n');
    }

    // ── stream cursor classes ──
    for i in &api.interfaces {
        for op in i.ops.iter().filter(|o| o.shape == Shape::Stream) {
            s.push_str(&emit_cursor_class(api, &i.name, op));
            s.push('\n');
        }
    }

    // ── per-interface class / free-function surface ──
    for i in &api.interfaces {
        // A FACTORY-BORN (ctor-less) interface's handle is minted node/python only
        // today — no C++ wrapper emitted for it yet (deferred).
        if super::is_factory_born(api, &i.name) {
            s.push_str(&format!(
                "{}\n\n",
                super::factory_born_interface_skip_note(&i.name)
            ));
            continue;
        }
        let has_ctor = i.ops.iter().any(|o| o.shape == Shape::Ctor);
        if has_ctor {
            s.push_str(&emit_handle_class(api, i));
        } else {
            s.push_str(&emit_stateless(api, i));
        }
        s.push('\n');
    }

    s.push_str("} // namespace fluessig\n\n");
    s.push_str(&format!("#endif // {guard}\n"));
    s.push_str(&st_note);
    s
}

/// A move-only `Cursor` wrapping the C stream handle.
fn emit_cursor_class(api: &ApiDoc, iface: &str, op: &ApiOp) -> String {
    let cur = c_stream_name(iface, op);
    let item = classify(api, &op.returns);
    let item_c = c_item_type(&item);
    let item_cpp = cpp_ty(&item);
    let mut s = String::new();
    s.push_str(&format!(
        "/// RAII pull cursor for `{iface}.{}`.\n",
        op.name
    ));
    s.push_str(&format!("class {cur}Cursor {{\npublic:\n"));
    s.push_str(&format!(
        "    explicit {cur}Cursor(::{cur}* h) : h_(h) {{}}\n"
    ));
    s.push_str(&format!(
        "    {cur}Cursor({cur}Cursor&& o) noexcept : h_(o.h_) {{ o.h_ = nullptr; }}\n"
    ));
    s.push_str(&format!("    {cur}Cursor(const {cur}Cursor&) = delete;\n"));
    s.push_str(&format!(
        "    {cur}Cursor& operator=(const {cur}Cursor&) = delete;\n"
    ));
    s.push_str(&format!(
        "    ~{cur}Cursor() {{ if (h_) {{ ::{cur}_close(h_); }} }}\n\n"
    ));
    // poll: returns Poll status, sets out on ITEM
    s.push_str(&format!(
        "    Poll poll({item_cpp}& out, uint32_t timeout_ms) {{\n"
    ));
    s.push_str(&format!("        {item_c} item{{}};\n"));
    s.push_str("        char* err = nullptr;\n");
    s.push_str(&format!(
        "        FlPoll p = ::{cur}_next(h_, timeout_ms, &item, &err);\n"
    ));
    s.push_str("        if (p == FL_POLL_FAILED) { throw Error(err); }\n");
    s.push_str(&format!(
        "        if (p == FL_POLL_ITEM) {{ out = {}; }}\n",
        item_from_c(&item)
    ));
    s.push_str("        return static_cast<Poll>(p);\n    }\n\n");
    // next: optional sugar
    s.push_str(&format!(
        "    std::optional<{item_cpp}> next(uint32_t timeout_ms = 500) {{\n"
    ));
    s.push_str(&format!("        {item_cpp} out{{}};\n"));
    s.push_str("        Poll p = poll(out, timeout_ms);\n");
    s.push_str("        if (p == Poll::Item) { return out; }\n");
    s.push_str("        return std::nullopt; // Idle or Closed\n    }\n\n");
    s.push_str("private:\n");
    s.push_str(&format!("    ::{cur}* h_;\n}};\n"));
    s
}

/// The C item type used in the cursor's `_next` out-param.
fn c_item_type(c: &Cross) -> String {
    match c {
        Cross::I32 | Cross::Enum(_) => "int32_t".into(),
        Cross::I64 => "int64_t".into(),
        Cross::F64 => "double".into(),
        Cross::Bool => "bool".into(),
        Cross::Str | Cross::StrEnum | Cross::Union => "char*".into(),
        Cross::Bytes => "FlBytes".into(),
        Cross::Model(m) => c_model_name(m),
        Cross::List(inner) => c_list_name(&list_elem_token(inner)),
        _ => "int32_t".into(),
    }
}

/// Expression converting a C stream item `item` into the C++ value.
fn item_from_c(c: &Cross) -> String {
    match c {
        Cross::Str | Cross::StrEnum | Cross::Union => {
            "[&]{ std::string r(item ? item : \"\"); fl_string_free(item); return r; }()".into()
        }
        _ => "item".into(),
    }
}

/// A move-only class wrapping a stateful interface's opaque handle.
fn emit_handle_class(api: &ApiDoc, i: &crate::api::ApiInterface) -> String {
    let iface = &i.name;
    let mut s = String::new();
    if let Some(doc) = &i.doc {
        for line in doc.lines() {
            s.push_str(&format!("/// {line}\n"));
        }
    }
    s.push_str(&format!("class {iface} {{\npublic:\n"));

    // constructor from the ctor op
    if let Some(ctor) = i.ops.iter().find(|o| o.shape == Shape::Ctor) {
        let params = cpp_params(api, ctor);
        let (prep, args) = cpp_args_prep(api, ctor);
        let arg_sep = if args.is_empty() { "" } else { ", " };
        s.push_str(&format!("    explicit {iface}({params}) {{\n"));
        s.push_str("        char* err = nullptr;\n");
        for line in &prep {
            s.push_str(&format!("        {line}\n"));
        }
        s.push_str(&format!(
            "        if (::{iface}_new({args}{arg_sep}&h_, &err)) {{ throw Error(err); }}\n"
        ));
        s.push_str("    }\n");
    }
    // lifecycle
    s.push_str(&format!(
        "    {iface}({iface}&& o) noexcept : h_(o.h_) {{ o.h_ = nullptr; }}\n"
    ));
    s.push_str(&format!("    {iface}(const {iface}&) = delete;\n"));
    s.push_str(&format!(
        "    {iface}& operator=(const {iface}&) = delete;\n"
    ));
    s.push_str(&format!(
        "    ~{iface}() {{ if (h_) {{ ::{iface}_free(h_); }} }}\n\n"
    ));

    // methods
    for op in &i.ops {
        // A FACTORY op (returns an interface handle) is minted node/python only today.
        if let Some(tgt) = crate::api::returned_interface(api, &op.returns) {
            s.push_str(&format!(
                "    {}\n",
                super::interface_return_skip_note(iface, &op.name, tgt.iface())
            ));
            continue;
        }
        match op.shape {
            Shape::Ctor => {}
            Shape::Manual => s.push_str(&format!(
                "    // @manual {iface}::{} — hand-written by the consumer.\n",
                op.name
            )),
            Shape::Stream => s.push_str(&emit_stream_method(api, iface, op, true)),
            // A subscription op registers a `std::function` listener and returns an
            // RAII `Subscription` (its destructor frees + unsubscribes).
            Shape::Subscription => s.push_str(&emit_subscription_method(api, iface, op)),
            Shape::Unary => s.push_str(&emit_unary_method(api, iface, op, true)),
        }
    }

    s.push_str("\nprivate:\n");
    s.push_str(&format!("    ::{iface}* h_ = nullptr;\n}};\n"));
    s
}

/// A stateless interface → a namespace of free functions.
fn emit_stateless(api: &ApiDoc, i: &crate::api::ApiInterface) -> String {
    let iface = &i.name;
    let mut s = String::new();
    if let Some(doc) = &i.doc {
        for line in doc.lines() {
            s.push_str(&format!("/// {line}\n"));
        }
    }
    s.push_str(&format!("namespace {} {{\n", snake(iface)));
    for op in &i.ops {
        // A FACTORY op (returns an interface handle) is minted node/python only today.
        if let Some(tgt) = crate::api::returned_interface(api, &op.returns) {
            s.push_str(&format!(
                "{}\n",
                super::interface_return_skip_note(iface, &op.name, tgt.iface())
            ));
            continue;
        }
        match op.shape {
            Shape::Manual => s.push_str(&format!(
                "// @manual {iface}::{} — hand-written by the consumer.\n",
                op.name
            )),
            Shape::Stream => s.push_str(&emit_stream_method(api, iface, op, false)),
            // Subscription lowering deferred (a subscription op is `&self` on a
            // stateful interface, so it never reaches this stateless arm).
            Shape::Subscription => s.push_str(&format!(
                "// subscription {iface}::{} — register/unsubscribe lowering deferred.\n",
                op.name
            )),
            Shape::Unary => s.push_str(&emit_unary_method(api, iface, op, false)),
            Shape::Ctor => {}
        }
    }
    s.push_str(&format!("}} // namespace {}\n", snake(iface)));
    s
}

/// The C++ parameter list for an op.
fn cpp_params(api: &ApiDoc, op: &ApiOp) -> String {
    op.params
        .iter()
        .map(|p| format!("{} {}", cpp_ty(&classify_param(api, p)), snake(&p.name)))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Whether a list element crosses on the string (`char*`) carrier.
fn is_string_carrier(c: &Cross) -> bool {
    matches!(c, Cross::Str | Cross::StrEnum | Cross::Union)
}

/// The prep statements + comma-joined C call arguments for an op's params. A
/// `list<string>` param needs a `std::vector<const char*>` staging temp
/// (`.data()` on a `std::vector<std::string>` is `std::string*`, not `char**`),
/// so it emits prep lines; every other param converts inline. The prep lines
/// carry NO indentation — the caller prefixes each with its method indent.
fn cpp_args_prep(api: &ApiDoc, op: &ApiOp) -> (Vec<String>, String) {
    let mut prep = Vec::new();
    let mut args = Vec::new();
    for p in &op.params {
        let c = classify_param(api, p);
        let name = snake(&p.name);
        match &c {
            Cross::List(inner) if is_string_carrier(inner) => {
                prep.push(format!("std::vector<const char*> {name}_c;"));
                prep.push(format!("{name}_c.reserve({name}.size());"));
                prep.push(format!(
                    "for (const auto& s : {name}) {{ {name}_c.push_back(s.c_str()); }}"
                ));
                args.push(format!("{name}_c.data(), {name}_c.size()"));
            }
            _ => args.push(cpp_arg(&c, &name)),
        }
    }
    (prep, args.join(", "))
}

/// A unary method — throws `Error` on failure (fallible) or returns directly
/// (infallible). `member` toggles the `::<Iface>_<op>(h_, …)` receiver.
fn emit_unary_method(api: &ApiDoc, iface: &str, op: &ApiOp, member: bool) -> String {
    let sym = op_symbol(iface, op);
    let ret = classify(api, &op.returns);
    let rty = cpp_ty(&ret);
    let params = cpp_params(api, op);
    let (prep, args) = cpp_args_prep(api, op);
    let recv = if member {
        "h_".to_string()
    } else {
        String::new()
    };
    let mut call_args = Vec::new();
    if member {
        call_args.push(recv);
    }
    if !args.is_empty() {
        call_args.push(args);
    }
    let lead = call_args.join(", ");
    let sep = if lead.is_empty() { "" } else { ", " };
    let kw = if member { "    " } else { "inline " };
    let name = snake(&op.name);
    let mut s = String::new();
    if let Some(doc) = &op.doc {
        for line in doc.lines() {
            s.push_str(&format!("{kw}/// {line}\n"));
        }
    }
    // The prep lines (list-of-string staging temps) prefixed with the body indent.
    let prep_block = |s: &mut String| {
        for line in &prep {
            s.push_str(&format!("{kw}    {line}\n"));
        }
    };

    if op.infallible {
        // Infallible op — value returned directly, no err channel. Scalars come
        // back by value; a compound (string / list / bytes / model) rides a
        // single out-param.
        match &ret {
            Cross::Void => {
                s.push_str(&format!("{kw}void {name}({params}) {{\n"));
                prep_block(&mut s);
                s.push_str(&format!("{kw}    ::{sym}({lead});\n{kw}}}\n"));
            }
            Cross::I32 | Cross::I64 | Cross::F64 | Cross::Bool | Cross::Enum(_) => {
                s.push_str(&format!("{kw}{rty} {name}({params}) {{\n"));
                prep_block(&mut s);
                s.push_str(&format!("{kw}    return ::{sym}({lead});\n{kw}}}\n"));
            }
            Cross::Str | Cross::StrEnum | Cross::Union => {
                s.push_str(&format!("{kw}std::string {name}({params}) {{\n"));
                prep_block(&mut s);
                s.push_str(&format!("{kw}    char* out = ::{sym}({lead});\n"));
                s.push_str(&format!(
                    "{kw}    std::string r(out ? out : \"\");\n{kw}    fl_string_free(out);\n{kw}    return r;\n{kw}}}\n"
                ));
            }
            Cross::List(inner) => {
                let out_c = c_item_type(&ret);
                s.push_str(&format!("{kw}{rty} {name}({params}) {{\n"));
                prep_block(&mut s);
                s.push_str(&format!("{kw}    {out_c} out{{}};\n"));
                s.push_str(&format!("{kw}    ::{sym}({lead}{sep}&out);\n"));
                s.push_str(&list_out_to_cpp(inner, "out", kw));
                s.push_str(&format!("{kw}}}\n"));
            }
            Cross::Bytes => {
                s.push_str(&format!("{kw}{rty} {name}({params}) {{\n"));
                prep_block(&mut s);
                s.push_str(&format!("{kw}    FlBytes out{{}};\n"));
                s.push_str(&format!("{kw}    ::{sym}({lead}{sep}&out);\n"));
                s.push_str(&bytes_out_to_cpp("out", kw));
                s.push_str(&format!("{kw}}}\n"));
            }
            _ => {
                // model: the C struct is returned by value via a single out-param.
                let out_c = c_item_type(&ret);
                s.push_str(&format!("{kw}{rty} {name}({params}) {{\n"));
                prep_block(&mut s);
                s.push_str(&format!("{kw}    {out_c} out{{}};\n"));
                s.push_str(&format!("{kw}    ::{sym}({lead}{sep}&out);\n"));
                s.push_str(&format!("{kw}    return out;\n{kw}}}\n"));
            }
        }
        return s;
    }

    match &ret {
        Cross::Void => {
            s.push_str(&format!("{kw}void {name}({params}) {{\n"));
            s.push_str(&format!("{kw}    char* err = nullptr;\n"));
            prep_block(&mut s);
            s.push_str(&format!(
                "{kw}    if (::{sym}({lead}{sep}&err)) {{ throw Error(err); }}\n{kw}}}\n"
            ));
        }
        Cross::Str | Cross::StrEnum | Cross::Union => {
            s.push_str(&format!("{kw}std::string {name}({params}) {{\n"));
            s.push_str(&format!(
                "{kw}    char* out = nullptr;\n{kw}    char* err = nullptr;\n"
            ));
            prep_block(&mut s);
            s.push_str(&format!(
                "{kw}    if (::{sym}({lead}{sep}&out, &err)) {{ throw Error(err); }}\n"
            ));
            s.push_str(&format!(
                "{kw}    std::string r(out ? out : \"\");\n{kw}    fl_string_free(out);\n{kw}    return r;\n{kw}}}\n"
            ));
        }
        Cross::List(inner) => {
            let out_c = c_item_type(&ret);
            s.push_str(&format!("{kw}{rty} {name}({params}) {{\n"));
            s.push_str(&format!(
                "{kw}    {out_c} out{{}};\n{kw}    char* err = nullptr;\n"
            ));
            prep_block(&mut s);
            s.push_str(&format!(
                "{kw}    if (::{sym}({lead}{sep}&out, &err)) {{ throw Error(err); }}\n"
            ));
            s.push_str(&list_out_to_cpp(inner, "out", kw));
            s.push_str(&format!("{kw}}}\n"));
        }
        Cross::Bytes => {
            s.push_str(&format!("{kw}{rty} {name}({params}) {{\n"));
            s.push_str(&format!(
                "{kw}    FlBytes out{{}};\n{kw}    char* err = nullptr;\n"
            ));
            prep_block(&mut s);
            s.push_str(&format!(
                "{kw}    if (::{sym}({lead}{sep}&out, &err)) {{ throw Error(err); }}\n"
            ));
            s.push_str(&bytes_out_to_cpp("out", kw));
            s.push_str(&format!("{kw}}}\n"));
        }
        Cross::Nullable(inner) => {
            let inner_cpp = cpp_ty(inner);
            let out_c = c_item_type(inner);
            s.push_str(&format!(
                "{kw}std::optional<{inner_cpp}> {name}({params}) {{\n"
            ));
            s.push_str(&format!("{kw}    bool has = false;\n{kw}    {out_c} out{{}};\n{kw}    char* err = nullptr;\n"));
            prep_block(&mut s);
            s.push_str(&format!(
                "{kw}    if (::{sym}({lead}{sep}&has, &out, &err)) {{ throw Error(err); }}\n"
            ));
            s.push_str(&format!("{kw}    if (!has) {{ return std::nullopt; }}\n"));
            s.push_str(&format!("{kw}    return out;\n{kw}}}\n"));
        }
        _ => {
            // scalar / enum / model: single out-param returned by value.
            let out_c = c_item_type(&ret);
            s.push_str(&format!("{kw}{rty} {name}({params}) {{\n"));
            s.push_str(&format!(
                "{kw}    {out_c} out{{}};\n{kw}    char* err = nullptr;\n"
            ));
            prep_block(&mut s);
            s.push_str(&format!(
                "{kw}    if (::{sym}({lead}{sep}&out, &err)) {{ throw Error(err); }}\n"
            ));
            s.push_str(&format!("{kw}    return out;\n{kw}}}\n"));
        }
    }
    s
}

/// The C++ statements converting a C list out-param (a `Fl<T>List` bound as
/// `out_var`) into the returned `std::vector<…> r`, freeing the C buffer. Covers
/// the flat element kinds the demo + tests exercise; a `list<model>` element is a
/// documented gap (its per-element free isn't woven in here).
fn list_out_to_cpp(inner: &Cross, out_var: &str, kw: &str) -> String {
    let token = list_elem_token(inner);
    let free = format!("fl_{}_list_free", snake(&token));
    let elem_cpp = cpp_ty(inner);
    let read = match inner {
        Cross::Str | Cross::StrEnum | Cross::Union => {
            format!("r.emplace_back({out_var}.data[i] ? {out_var}.data[i] : \"\");")
        }
        Cross::Enum(e) => format!(
            "r.push_back(static_cast<{}>({out_var}.data[i]));",
            c_enum_name(e)
        ),
        _ => format!("r.push_back({out_var}.data[i]);"),
    };
    format!(
        "{kw}    std::vector<{elem_cpp}> r;\n{kw}    r.reserve({out_var}.len);\n{kw}    for (size_t i = 0; i < {out_var}.len; ++i) {{ {read} }}\n{kw}    ::{free}(&{out_var});\n{kw}    return r;\n"
    )
}

/// The C++ statements copying a C `FlBytes` out-param (`out_var`) into the
/// returned `std::vector<uint8_t> r`, freeing the C buffer.
fn bytes_out_to_cpp(out_var: &str, kw: &str) -> String {
    format!(
        "{kw}    std::vector<uint8_t> r({out_var}.data, {out_var}.data + {out_var}.len);\n{kw}    fl_bytes_free(&{out_var});\n{kw}    return r;\n"
    )
}

/// A stream method returning a `…Cursor`.
fn emit_stream_method(api: &ApiDoc, iface: &str, op: &ApiOp, member: bool) -> String {
    let sym = op_symbol(iface, op);
    let cur = c_stream_name(iface, op);
    let params = cpp_params(api, op);
    let (prep, args) = cpp_args_prep(api, op);
    let recv = if member {
        "h_".to_string()
    } else {
        String::new()
    };
    let mut call_args = Vec::new();
    if member {
        call_args.push(recv);
    }
    if !args.is_empty() {
        call_args.push(args);
    }
    let lead = call_args.join(", ");
    let sep = if lead.is_empty() { "" } else { ", " };
    let kw = if member { "    " } else { "inline " };
    let name = snake(&op.name);
    let mut s = String::new();
    if let Some(doc) = &op.doc {
        for line in doc.lines() {
            s.push_str(&format!("{kw}/// {line}\n"));
        }
    }
    s.push_str(&format!("{kw}{cur}Cursor {name}({params}) {{\n"));
    s.push_str(&format!(
        "{kw}    ::{cur}* out = nullptr;\n{kw}    char* err = nullptr;\n"
    ));
    for line in &prep {
        s.push_str(&format!("{kw}    {line}\n"));
    }
    s.push_str(&format!(
        "{kw}    if (::{sym}({lead}{sep}&out, &err)) {{ throw Error(err); }}\n"
    ));
    s.push_str(&format!("{kw}    return {cur}Cursor(out);\n{kw}}}\n"));
    s
}

/// The move-only `Subscription` RAII class (emitted once). It owns the C
/// `::Subscription*` handle AND the heap `std::function` listener behind the C
/// `void* ctx`; its destructor frees the handle (which unsubscribes) and then
/// deletes the listener via a type-erased deleter. `unsubscribe()` runs the
/// unsubscribe early.
fn subscription_class() -> String {
    let mut s = String::new();
    s.push_str("/// RAII subscription handle: unsubscribe()/destroy removes the listener.\n");
    s.push_str("class Subscription {\npublic:\n");
    s.push_str(
        "    Subscription(::Subscription* h, void* ctx, void (*deleter)(void*))\n        : h_(h), ctx_(ctx), deleter_(deleter) {}\n",
    );
    s.push_str("    Subscription(Subscription&& o) noexcept\n        : h_(o.h_), ctx_(o.ctx_), deleter_(o.deleter_) { o.h_ = nullptr; o.ctx_ = nullptr; o.deleter_ = nullptr; }\n");
    s.push_str("    Subscription(const Subscription&) = delete;\n");
    s.push_str("    Subscription& operator=(const Subscription&) = delete;\n");
    s.push_str("    ~Subscription() {\n        if (h_) { ::Subscription_free(h_); }\n        if (ctx_ && deleter_) { deleter_(ctx_); }\n    }\n");
    s.push_str("    /// Remove the listener early (idempotent).\n");
    s.push_str("    void unsubscribe() { if (h_) { ::Subscription_unsubscribe(h_); } }\n\n");
    s.push_str("private:\n");
    s.push_str("    ::Subscription* h_ = nullptr;\n    void* ctx_ = nullptr;\n    void (*deleter_)(void*) = nullptr;\n};\n");
    s
}

/// A subscription method on a handle class: takes a `std::function<void(Args)>`
/// listener, heap-copies it, passes a captureless thunk + the heap ptr as the C
/// fn-ptr + ctx, and returns an owning `Subscription`. Fallible ⇒ throws (freeing
/// the heap listener first); infallible ⇒ no error channel.
fn emit_subscription_method(api: &ApiDoc, iface: &str, op: &ApiOp) -> String {
    let sym = op_symbol(iface, op);
    let name = snake(&op.name);
    let (cbname, sig) = op
        .params
        .iter()
        .find_map(|p| match &p.ty {
            ApiType::Callback { callback } => Some((snake(&p.name), callback)),
            _ => None,
        })
        .expect("a subscription op has exactly one callback param (loader-enforced)");
    let arg_tys: Vec<String> = sig
        .params
        .iter()
        .map(|p| cpp_value_type(&classify(api, p)))
        .collect();
    let fnty = format!("std::function<void({})>", arg_tys.join(", "));
    let vars = callback_arg_vars(arg_tys.len());
    let thunk_params = std::iter::once("void* c".to_string())
        .chain(vars.iter().zip(&arg_tys).map(|(v, t)| format!("{t} {v}")))
        .collect::<Vec<_>>()
        .join(", ");
    let thunk_call = vars.join(", ");
    let mut s = String::new();
    if let Some(doc) = &op.doc {
        for line in doc.lines() {
            s.push_str(&format!("    /// {line}\n"));
        }
    }
    s.push_str(&format!("    Subscription {name}({fnty} {cbname}) {{\n"));
    s.push_str(&format!(
        "        auto* ctx = new {fnty}(std::move({cbname}));\n"
    ));
    s.push_str(&format!(
        "        auto thunk = []({thunk_params}) {{ (*static_cast<{fnty}*>(c))({thunk_call}); }};\n"
    ));
    s.push_str(&format!(
        "        auto deleter = [](void* c) {{ delete static_cast<{fnty}*>(c); }};\n"
    ));
    s.push_str("        ::Subscription* out = nullptr;\n");
    if op.infallible {
        s.push_str(&format!("        ::{sym}(h_, thunk, ctx, &out);\n"));
    } else {
        s.push_str("        char* err = nullptr;\n");
        s.push_str(&format!(
            "        if (::{sym}(h_, thunk, ctx, &out, &err)) {{ deleter(ctx); throw Error(err); }}\n"
        ));
    }
    s.push_str("        return Subscription(out, ctx, deleter);\n");
    s.push_str("    }\n");
    s
}
