//! A self-contained plain-Rust projection of the op surface: the `<Interface>Core`
//! traits (the shared spine every language backend already embeds) PLUS the DTO
//! models and enums they reference, emitted as ordinary `pub struct`/`pub enum`
//! with no FFI attributes. The output is a single module that compiles against
//! nothing but `anyhow` — the "Rust API skeleton" a consumer implements over its
//! engine, without pulling in napi/pyo3/ext-php-rs.
//!
//! Where [`node`](super::node)/[`php`](super::php) wrap the core traits in a
//! language's binding glue, this backend emits ONLY the language-neutral core:
//! the traits come verbatim from the shared [`emit_core_traits_with`], and the
//! models/enums are the same shapes the other backends carry, minus the derives
//! and rename attributes a real FFI needs. It is the honest floor of the
//! pipeline — proof that an extracted API round-trips to compilable Rust.
//!
//! straitjacket-allow-file:duplication — the model/enum emission here is a
//! deliberately-plain twin of the attribute-carrying versions in the per-language
//! backends; the shared trait spine it reuses ([`emit_core_traits_with`]) is the
//! non-duplicated half.

use genco::prelude::*;

use crate::api::{ApiDoc, Shape};

use super::*;

/// Emit the self-contained core module: `Bytes` alias + `PollStream` stub (when
/// used), enums, DTO structs, and the `<Interface>Core` traits. `enums` is the
/// shared per-variant enum form (`bindgen::EnumDesc`) the binary already derives
/// from the catalog.
pub fn rust_core_binding(api: &ApiDoc, enums: &[EnumDesc], banner_note: Option<&str>) -> String {
    // The module needs no `use` prelude — every op's fallible seam spells
    // `anyhow::Result` fully-qualified, so `anyhow` is the one external crate.
    let mut t: rust::Tokens = quote! {};

    if api_uses_bytes(api) {
        quote_in! { t =>
            $("/// Bulk bytes ride as an owned buffer in the neutral core surface.")
            pub type Bytes = Vec<u8>;
            $['\n']
        };
    }

    if api_has_stream(api) {
        quote_in! { t =>
            $("/// The streaming contract a `stream`-shaped op returns. In a real")
            $("/// binding this is fluessig-runtime's `PollStream`; the standalone")
            $("/// core stubs it so the trait signatures resolve.")
            pub trait PollStream<T> {
                fn poll_next(&mut self) -> anyhow::Result<Option<T>>;
            }
            $['\n']
        };
    }

    // ── enums: plain Rust (no serde/napi derives) ──
    for (name, variants) in enums {
        if is_string_enum(api, name) {
            // A value-carrying enum rides as a `String` in the shared `ty`, so no
            // Rust type is needed (and none is referenced).
            continue;
        }
        let arms: Vec<String> = variants.iter().map(|v| pascal(&v.name)).collect();
        quote_in! { t =>
            #[derive(Debug, Clone, PartialEq, Eq)]
            pub enum $name {
                $(for a in &arms join (, ) => $a)
            }
            $['\n']
        };
    }

    // ── models: plain DTO structs ──
    for m in &api.models {
        let fields: Vec<String> = m
            .fields
            .iter()
            .map(|f| {
                let (rust_ty, _) = ty(api, &f.ty);
                let rust_ty = if f.nullable {
                    format!("Option<{rust_ty}>")
                } else {
                    rust_ty
                };
                format!("pub {}: {rust_ty}", field_ident(&f.name))
            })
            .collect();
        let doc = m.doc.as_deref().map(doc_line).unwrap_or_default();
        quote_in! { t =>
            $(&doc)#[derive(Debug, Clone)]
            pub struct $(&m.name) {
                $(for f in &fields join (, ) => $f)
            }
            $['\n']
        };
    }

    // ── the shared core traits (verbatim from the language-neutral spine) ──
    emit_core_traits_with(&mut t, api, |op| ty(api, &op.returns).0);

    let src = api.source.as_deref().unwrap_or("the fluessig catalog");
    let body = t.to_file_string().expect("rust renders");
    crate::rustfmt::format(format!(
        "//! GENERATED by fluessig bindgen from {src} (rust-core). Do not edit.\n\
         //! A self-contained Rust API skeleton: DTO models/enums + `<Interface>Core`\n\
         //! traits. Depends only on `anyhow`.\n{}#![allow(dead_code)]\n#![allow(clippy::all)]\n\n{body}",
        note_line(banner_note)
    ))
}

/// Does any interface carry a `stream`-shaped op? Gates the `PollStream` stub so
/// a stream-free surface emits nothing referencing it.
fn api_has_stream(api: &ApiDoc) -> bool {
    api.interfaces
        .iter()
        .flat_map(|i| &i.ops)
        .any(|op| op.shape == Shape::Stream)
}

/// A field name as a valid Rust ident: raw-escape a keyword (`type` → `r#type`),
/// or suffix the handful of keywords that cannot be raw identifiers.
fn field_ident(name: &str) -> String {
    // Keywords that CANNOT be spelled `r#…`.
    const HARD: &[&str] = &["self", "Self", "super", "crate"];
    // Reserved words legal as raw identifiers.
    const RAW: &[&str] = &[
        "as", "break", "const", "continue", "dyn", "else", "enum", "extern", "false", "fn", "for",
        "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
        "static", "struct", "trait", "true", "type", "unsafe", "use", "where", "while", "async",
        "await", "box",
    ];
    if HARD.contains(&name) {
        format!("{name}_")
    } else if RAW.contains(&name) {
        format!("r#{name}")
    } else if is_valid_ident(name) {
        name.to_string()
    } else {
        // A rendered destructured/odd name; make it a stable placeholder.
        format!("field_{}", snake(name))
    }
}

fn is_valid_ident(s: &str) -> bool {
    let mut cs = s.chars();
    matches!(cs.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
        && cs.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// A doc comment as `///` lines (first line only, trimmed) — enough to carry the
/// model's intent without risking a multi-line rendering hazard.
fn doc_line(doc: &str) -> String {
    let first = doc.lines().next().unwrap_or("").trim();
    if first.is_empty() {
        String::new()
    } else {
        format!("/// {first}\n")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::api::load_api;

    /// A small api.json → a self-contained module: DTO struct (with a keyword
    /// field raw-escaped), a plain enum, and a `<Interface>Core` trait whose
    /// method returns the DTO. rustfmt accepting the output is itself a proof the
    /// emitted Rust parses.
    fn sample() -> crate::api::ApiDoc {
        let json = r#"{
          "fluessig": {"format": 1, "emitter": "t", "compiler": "t"},
          "models": [
            {"name": "Summary", "fields": [
              {"name": "id", "type": "string", "nullable": false},
              {"name": "type", "type": "string", "nullable": false},
              {"name": "status", "type": {"enum": "Status"}, "nullable": false},
              {"name": "label", "type": "string", "nullable": true}
            ]}
          ],
          "unions": [],
          "interfaces": [
            {"name": "Api", "ops": [
              {"name": "getSummary", "shape": "unary", "async": true,
               "params": [{"name": "id", "type": "string"}],
               "returns": {"model": "Summary"}}
            ]}
          ]
        }"#;
        load_api(json).unwrap()
    }

    #[test]
    fn emits_self_contained_module() {
        let enums: Vec<EnumDesc> = vec![(
            "Status".to_string(),
            vec![
                EnumVariant {
                    name: "open".to_string(),
                    value: None,
                    bindings: Default::default(),
                },
                EnumVariant {
                    name: "closed".to_string(),
                    value: None,
                    bindings: Default::default(),
                },
            ],
        )];
        let out = rust_core_binding(&sample(), &enums, None);

        // The plain enum and struct are present, with the `type` field escaped.
        assert!(out.contains("pub enum Status"));
        assert!(out.contains("pub struct Summary"));
        assert!(out.contains("pub r#type: String"));
        assert!(out.contains("pub label: Option<String>"));
        assert!(out.contains("pub status: Status"));
        // The core trait spine, with the DTO return.
        assert!(out.contains("pub trait ApiCore"));
        assert!(out.contains("fn get_summary(id: String) -> anyhow::Result<Summary>"));
        // Only `anyhow` is referenced — no FFI crates leak in.
        assert!(!out.contains("napi"));
        assert!(!out.contains("pyo3"));
        assert!(!out.contains("ext_php_rs"));
    }

    #[test]
    fn keyword_field_idents_are_safe() {
        assert_eq!(field_ident("type"), "r#type");
        assert_eq!(field_ident("self"), "self_");
        assert_eq!(field_ident("normal"), "normal");
    }
}
