//! A self-contained plain-Rust projection of the op surface: the `<Interface>Core`
//! traits (the shared spine every language backend already embeds) PLUS the DTO
//! models and enums they reference, emitted as ordinary `pub struct`/`pub enum`
//! with no FFI attributes. The output is a single module that compiles against
//! nothing but `anyhow` — the "Rust API skeleton" a consumer implements over its
//! engine, without pulling in napi/pyo3/ext-php-rs.
//!
//! Where [`node`](super::node)/[`php`](super::php) wrap the core traits in a
//! language's binding glue, this backend emits ONLY the language-neutral core:
//! the traits come verbatim from the shared [`emit_core_traits_with`], and the
//! models/enums are the same shapes the other backends carry, minus the derives
//! and rename attributes a real FFI needs. It is the honest floor of the
//! pipeline — proof that an extracted API round-trips to compilable Rust.
//!
//! straitjacket-allow-file:duplication — the model/enum emission here is a
//! deliberately-plain twin of the attribute-carrying versions in the per-language
//! backends; the shared trait spine it reuses ([`emit_core_traits_with`]) is the
//! non-duplicated half.

use genco::prelude::*;

use crate::api::{ApiConst, ApiDoc, ApiType, ConstValue, ForeignType, Shape};

use super::*;

/// Emit the self-contained core module: `Bytes` alias + `PollStream` stub (when
/// used), enums, DTO structs, and the `<Interface>Core` traits. `enums` is the
/// shared per-variant enum form (`bindgen::EnumDesc`) the binary already derives
/// from the catalog.
pub fn rust_core_binding(api: &ApiDoc, enums: &[EnumDesc], banner_note: Option<&str>) -> String {
    // The module needs no `use` prelude — every op's fallible seam spells
    // `anyhow::Result` fully-qualified, so `anyhow` is the one external crate.
    let mut t: rust::Tokens = quote! {};

    if api_uses_bytes(api) {
        quote_in! { t =>
            $("/// Bulk bytes ride as an owned buffer in the neutral core surface.")
            pub type Bytes = Vec<u8>;
            $['\n']
        };
    }

    if api_has_stream(api) {
        quote_in! { t =>
            $("/// The streaming contract a `stream`-shaped op returns. In a real")
            $("/// binding this is fluessig-runtime's `PollStream`; the standalone")
            $("/// core stubs it so the trait signatures resolve.")
            pub trait PollStream<T> {
                fn poll_next(&mut self) -> anyhow::Result<Option<T>>;
            }
            $['\n']
        };
    }

    // ── top-level exported consts: `pub const` (or a runtime-value note) ──
    emit_consts(&mut t, api);

    // ── enums: plain Rust (no serde/napi derives) ──
    for (name, variants) in enums {
        if is_string_enum(api, name) {
            // A value-carrying enum rides as a `String` in the shared `ty`, so no
            // Rust type is needed (and none is referenced).
            continue;
        }
        let arms: Vec<String> = variants.iter().map(|v| pascal(&v.name)).collect();
        quote_in! { t =>
            #[derive(Debug, Clone, PartialEq, Eq)]
            pub enum $name {
                $(for a in &arms join (, ) => $a)
            }
            $['\n']
        };
    }

    // ── foreign opaque handles: one newtype per distinct foreign type ──
    emit_foreign_handles(&mut t, api);

    // ── models: plain DTO structs ──
    for m in &api.models {
        let fields: Vec<String> = m
            .fields
            .iter()
            .map(|f| {
                let (rust_ty, _) = ty(api, &f.ty);
                let rust_ty = if f.nullable {
                    format!("Option<{rust_ty}>")
                } else {
                    rust_ty
                };
                format!("pub {}: {rust_ty}", field_ident(&f.name))
            })
            .collect();
        let doc = m.doc.as_deref().map(doc_line).unwrap_or_default();
        quote_in! { t =>
            $(&doc)#[derive(Debug, Clone)]
            pub struct $(&m.name) {
                $(for f in &fields join (, ) => $f)
            }
            $['\n']
        };
    }

    // ── the shared core traits (verbatim from the language-neutral spine) ──
    emit_core_traits_with(&mut t, api, |op| ty(api, &op.returns).0);

    let src = api.source.as_deref().unwrap_or("the fluessig catalog");
    let body = t.to_file_string().expect("rust renders");
    crate::rustfmt::format(format!(
        "//! GENERATED by fluessig bindgen from {src} (rust-core). Do not edit.\n\
         //! A self-contained Rust API skeleton: DTO models/enums + `<Interface>Core`\n\
         //! traits. Depends only on `anyhow`.\n{}#![allow(dead_code)]\n#![allow(clippy::all)]\n\n{body}",
        note_line(banner_note)
    ))
}

/// Does any interface carry a `stream`-shaped op? Gates the `PollStream` stub so
/// a stream-free surface emits nothing referencing it.
fn api_has_stream(api: &ApiDoc) -> bool {
    api.interfaces
        .iter()
        .flat_map(|i| &i.ops)
        .any(|op| op.shape == Shape::Stream)
}

/// Emit one plain-Rust OPAQUE HANDLE struct per DISTINCT foreign type the surface
/// references. A truly-foreign type (Node's `http.Server`, a `ChildProcess`, an OS
/// file descriptor, …) is one fluessig has no model for; instead of silently
/// collapsing it to a `String`/JSON carrier, rust-core generates a typed handle the
/// boundary can carry WITHOUT the real external type in scope.
///
/// Representation: a newtype over an engine-assigned `u64` token — the honest
/// "engine-owned integer handle" idiom the cpp/java backends already use for
/// stateful values. The real foreign value lives behind the boundary; the core
/// only carries the token and never interprets it (hence OPAQUE). The handle type
/// name is derived deterministically from the source type name (see
/// [`foreign_handle_name`]), so a foreign type used at N sites collapses to exactly
/// ONE struct and every reference (via the shared [`ty`]) resolves to it.
fn emit_foreign_handles(t: &mut rust::Tokens, api: &ApiDoc) {
    for (name, f) in foreign_handles(api) {
        let doc = format!(
            "Opaque handle for the foreign type `{}` (Rust path: `{}`).",
            f.name, f.rust_path
        );
        quote_in! { *t =>
            $(format!("/// {doc}"))
            $("/// Engine-owned: the real foreign value lives behind the boundary; the")
            $("/// core carries this handle as an opaque token and never inspects it.")
            #[derive(Debug, Clone)]
            pub struct $(&name)(pub u64);
            $['\n']
        };
    }
}

/// The DISTINCT foreign types the surface references, as `(handle name, foreign)`
/// pairs in first-appearance order, deduped by handle name. Walks every reference
/// site — model fields and op params/returns, recursing through `List`/`Nullable`.
fn foreign_handles(api: &ApiDoc) -> Vec<(String, ForeignType)> {
    let mut refs: Vec<&ForeignType> = Vec::new();
    for m in &api.models {
        for field in &m.fields {
            collect_foreign(&field.ty, &mut refs);
        }
    }
    for i in &api.interfaces {
        for op in &i.ops {
            collect_foreign(&op.returns, &mut refs);
            for p in &op.params {
                collect_foreign(&p.ty, &mut refs);
            }
        }
    }
    let mut seen: Vec<String> = Vec::new();
    let mut out: Vec<(String, ForeignType)> = Vec::new();
    for f in refs {
        let name = foreign_handle_name(f);
        if !seen.contains(&name) {
            seen.push(name.clone());
            out.push((name, f.clone()));
        }
    }
    out
}

/// Collect every [`ForeignType`] reachable from `t`, recursing through the
/// `List`/`Nullable` wrappers (the only shapes that nest a type).
fn collect_foreign<'a>(t: &'a ApiType, out: &mut Vec<&'a ForeignType>) {
    match t {
        ApiType::Foreign { foreign } => out.push(foreign),
        ApiType::List { list } => collect_foreign(list, out),
        ApiType::Nullable { nullable } => collect_foreign(nullable, out),
        _ => {}
    }
}

/// Emit the surface's TOP-LEVEL exported constants as `pub const` items, sorted
/// by name for deterministic output.
///
/// Const-representability policy: a const lowers to a real `pub const NAME: T =
/// LITERAL;` ONLY when its declared `type` is a const-constructible SCALAR
/// (`string`/`boolean`/`int32`/`int64`/`float64`) AND it carries a statically-known
/// literal `value`. A `string` rides as `&str` (a `String` const is not
/// const-constructible); the other scalars reuse the shared [`ty`] Rust mapping
/// verbatim. Anything else — a model/union/foreign/`Json`/`bytes` type, or a const
/// with no literal value (a runtime expression the extractor could not fold) — is
/// NOT forced into a broken `pub const`. Instead it is skipped and recorded as a
/// `// const NAME: <ty> — not const-representable (runtime value)` doc comment, so
/// the const's existence is visible in the skeleton without emitting code that
/// would not compile.
fn emit_consts(t: &mut rust::Tokens, api: &ApiDoc) {
    let mut consts: Vec<&ApiConst> = api.consts.iter().collect();
    consts.sort_by(|a, b| a.name.cmp(&b.name));
    for c in consts {
        match const_literal(api, c) {
            Some((rust_ty, literal)) => {
                let doc = c.doc.as_deref().map(doc_line).unwrap_or_default();
                quote_in! { *t =>
                    $(&doc)pub const $(&c.name): $(rust_ty) = $(literal);
                    $['\n']
                };
            }
            None => {
                let label = ty(api, &c.ty).0;
                quote_in! { *t =>
                    $(format!("// const {}: {label} — not const-representable (runtime value)", c.name))
                    $['\n']
                };
            }
        }
    }
}

/// The `(Rust type, Rust literal)` a const lowers to, or `None` when it is not
/// const-representable (non-scalar type, no literal value, or a value whose form
/// does not match a const-constructible scalar). See [`emit_consts`] for policy.
fn const_literal(api: &ApiDoc, c: &ApiConst) -> Option<(String, String)> {
    let ApiType::Scalar(scalar) = &c.ty else {
        return None;
    };
    let value = c.value.as_ref()?;
    let out = match (scalar.as_str(), value) {
        // A string const rides as `&str` (deviating from `ty()`'s `String`, which
        // is not const-constructible); `{:?}` renders an escaped Rust string literal.
        ("string", ConstValue::Str(s)) => ("&str".to_string(), format!("{s:?}")),
        ("boolean", ConstValue::Bool(b)) => (ty(api, &c.ty).0, b.to_string()),
        ("int32" | "int64", ConstValue::Int(i)) => (ty(api, &c.ty).0, i.to_string()),
        // A float const accepts an integer JSON number too (the untagged carrier
        // lands whole numbers on `Int`); either way it renders as an `f64` literal.
        ("float64", ConstValue::Float(f)) => (ty(api, &c.ty).0, float_lit(*f)),
        ("float64", ConstValue::Int(i)) => (ty(api, &c.ty).0, float_lit(*i as f64)),
        _ => return None,
    };
    Some(out)
}

/// Render an `f64` as a valid Rust float literal — ensure a decimal point (or
/// exponent) so `2` becomes `2.0` (a bare `2` is not a valid `f64` const value).
fn float_lit(f: f64) -> String {
    let s = format!("{f}");
    if s.contains(['.', 'e', 'E']) || !s.bytes().all(|b| b.is_ascii_digit() || b == b'-') {
        s
    } else {
        format!("{s}.0")
    }
}

/// A field name as a valid Rust ident: raw-escape a keyword (`type` → `r#type`),
/// or suffix the handful of keywords that cannot be raw identifiers.
fn field_ident(name: &str) -> String {
    // Keywords that CANNOT be spelled `r#…`.
    const HARD: &[&str] = &["self", "Self", "super", "crate"];
    // Reserved words legal as raw identifiers.
    const RAW: &[&str] = &[
        "as", "break", "const", "continue", "dyn", "else", "enum", "extern", "false", "fn", "for",
        "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
        "static", "struct", "trait", "true", "type", "unsafe", "use", "where", "while", "async",
        "await", "box",
    ];
    if HARD.contains(&name) {
        format!("{name}_")
    } else if RAW.contains(&name) {
        format!("r#{name}")
    } else if is_valid_ident(name) {
        name.to_string()
    } else {
        // A rendered destructured/odd name; make it a stable placeholder.
        format!("field_{}", snake(name))
    }
}

fn is_valid_ident(s: &str) -> bool {
    let mut cs = s.chars();
    matches!(cs.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
        && cs.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// A doc comment as `///` lines (first line only, trimmed) — enough to carry the
/// model's intent without risking a multi-line rendering hazard.
fn doc_line(doc: &str) -> String {
    let first = doc.lines().next().unwrap_or("").trim();
    if first.is_empty() {
        String::new()
    } else {
        format!("/// {first}\n")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::api::load_api;

    /// A small api.json → a self-contained module: DTO struct (with a keyword
    /// field raw-escaped), a plain enum, and a `<Interface>Core` trait whose
    /// method returns the DTO. rustfmt accepting the output is itself a proof the
    /// emitted Rust parses.
    fn sample() -> crate::api::ApiDoc {
        let json = r#"{
          "fluessig": {"format": 1, "emitter": "t", "compiler": "t"},
          "models": [
            {"name": "Summary", "fields": [
              {"name": "id", "type": "string", "nullable": false},
              {"name": "type", "type": "string", "nullable": false},
              {"name": "status", "type": {"enum": "Status"}, "nullable": false},
              {"name": "label", "type": "string", "nullable": true}
            ]}
          ],
          "unions": [],
          "interfaces": [
            {"name": "Api", "ops": [
              {"name": "getSummary", "shape": "unary", "async": true,
               "params": [{"name": "id", "type": "string"}],
               "returns": {"model": "Summary"}}
            ]}
          ]
        }"#;
        load_api(json).unwrap()
    }

    #[test]
    fn emits_self_contained_module() {
        let enums: Vec<EnumDesc> = vec![(
            "Status".to_string(),
            vec![
                EnumVariant {
                    name: "open".to_string(),
                    value: None,
                    bindings: Default::default(),
                },
                EnumVariant {
                    name: "closed".to_string(),
                    value: None,
                    bindings: Default::default(),
                },
            ],
        )];
        let out = rust_core_binding(&sample(), &enums, None);

        // The plain enum and struct are present, with the `type` field escaped.
        assert!(out.contains("pub enum Status"));
        assert!(out.contains("pub struct Summary"));
        assert!(out.contains("pub r#type: String"));
        assert!(out.contains("pub label: Option<String>"));
        assert!(out.contains("pub status: Status"));
        // The core trait spine, with the DTO return.
        assert!(out.contains("pub trait ApiCore"));
        assert!(out.contains("fn get_summary(id: String) -> anyhow::Result<Summary>"));
        // Only `anyhow` is referenced — no FFI crates leak in.
        assert!(!out.contains("napi"));
        assert!(!out.contains("pyo3"));
        assert!(!out.contains("ext_php_rs"));
    }

    #[test]
    fn keyword_field_idents_are_safe() {
        assert_eq!(field_ident("type"), "r#type");
        assert_eq!(field_ident("self"), "self_");
        assert_eq!(field_ident("normal"), "normal");
    }

    /// The handle type name is derived deterministically from the source name:
    /// dotted/mixed-case foreign names collapse to one PascalCase `…Handle` ident.
    #[test]
    fn foreign_handle_names_are_deterministic() {
        let mk = |name: &str| ForeignType {
            name: name.to_string(),
            rust_path: String::new(),
        };
        assert_eq!(foreign_handle_name(&mk("http.Server")), "HttpServerHandle");
        assert_eq!(
            foreign_handle_name(&mk("ChildProcess")),
            "ChildProcessHandle"
        );
        assert_eq!(
            foreign_handle_name(&mk("fs.ReadStream")),
            "FsReadStreamHandle"
        );
    }

    /// A `Foreign` type in an op param, an op return, AND a model field all lower
    /// to the SAME generated opaque handle — emitted once, referenced everywhere,
    /// and never silently collapsed to `String`/`Json`. This is the orchestrator's
    /// driving case: `startIpcServer` returns Node's `http.Server`.
    #[test]
    fn foreign_type_lowers_to_opaque_handle() {
        let json = r#"{
          "fluessig": {"format": 1, "emitter": "t", "compiler": "t"},
          "models": [
            {"name": "IpcServer", "fields": [
              {"name": "server", "type": {"foreign": {"name": "http.Server", "rustPath": "http::Server"}}, "nullable": false}
            ]}
          ],
          "unions": [],
          "interfaces": [
            {"name": "Ipc", "ops": [
              {"name": "startServer", "shape": "unary",
               "params": [{"name": "existing", "type": {"foreign": {"name": "http.Server", "rustPath": "http::Server"}}}],
               "returns": {"foreign": {"name": "http.Server", "rustPath": "http::Server"}}}
            ]}
          ]
        }"#;
        let api = load_api(json).unwrap();
        let out = rust_core_binding(&api, &[], None);

        // The opaque handle struct is emitted — a typed newtype, not a String/Json.
        assert!(out.contains("pub struct HttpServerHandle(pub u64);"));
        // Emitted EXACTLY once even though the foreign type appears at three sites.
        assert_eq!(out.matches("pub struct HttpServerHandle").count(), 1);
        // The model field references the handle, NOT a String/Json carrier.
        assert!(out.contains("pub server: HttpServerHandle"));
        assert!(!out.contains("pub server: String"));
        assert!(!out.contains("pub server: Json"));
        // The core trait method takes and returns the handle — no String seam.
        assert!(out.contains(
            "fn start_server(existing: HttpServerHandle) -> anyhow::Result<HttpServerHandle>"
        ));
        // The foreign type name/path is carried into the handle's doc comment.
        assert!(out.contains("Opaque handle for the foreign type `http.Server`"));
    }

    /// Distinct foreign types each get their own handle struct — the mechanism is
    /// general, not hardcoded to `http.Server`.
    #[test]
    fn distinct_foreign_types_get_distinct_handles() {
        let json = r#"{
          "fluessig": {"format": 1, "emitter": "t", "compiler": "t"},
          "models": [],
          "unions": [],
          "interfaces": [
            {"name": "Proc", "ops": [
              {"name": "spawn", "shape": "unary", "params": [],
               "returns": {"foreign": {"name": "ChildProcess", "rustPath": "std::process::Child"}}},
              {"name": "listen", "shape": "unary", "params": [],
               "returns": {"list": {"foreign": {"name": "http.Server", "rustPath": "http::Server"}}}}
            ]}
          ]
        }"#;
        let api = load_api(json).unwrap();
        let out = rust_core_binding(&api, &[], None);

        assert!(out.contains("pub struct ChildProcessHandle(pub u64);"));
        assert!(out.contains("pub struct HttpServerHandle(pub u64);"));
        // Nested through `List`, the return is `Vec<HttpServerHandle>`, not `Vec<String>`.
        assert!(out.contains("-> anyhow::Result<Vec<HttpServerHandle>>"));
    }

    /// A string / int / bool / float exported const lowers to a real `pub const`,
    /// with `string` riding as `&str`; consts are emitted sorted by name and the
    /// whole module still round-trips through rustfmt (proof it parses).
    #[test]
    fn representable_consts_lower_to_pub_const() {
        let json = r#"{
          "fluessig": {"format": 1, "emitter": "t", "compiler": "t"},
          "models": [], "unions": [],
          "consts": [
            {"name": "VERSION", "type": "string", "value": "0.80.10"},
            {"name": "MAX_RETRIES", "type": "int64", "value": 5},
            {"name": "DEBUG", "type": "boolean", "value": true},
            {"name": "RATIO", "type": "float64", "value": 1.5}
          ],
          "interfaces": [{"name": "Api", "ops": []}]
        }"#;
        let api = load_api(json).unwrap();
        let out = rust_core_binding(&api, &[], None);

        assert!(out.contains(r#"pub const VERSION: &str = "0.80.10";"#));
        assert!(out.contains("pub const MAX_RETRIES: i64 = 5;"));
        assert!(out.contains("pub const DEBUG: bool = true;"));
        assert!(out.contains("pub const RATIO: f64 = 1.5;"));
        // Deterministic: sorted by name (DEBUG < MAX_RETRIES < RATIO < VERSION).
        let pos = |n: &str| out.find(n).unwrap();
        assert!(pos("DEBUG") < pos("MAX_RETRIES"));
        assert!(pos("MAX_RETRIES") < pos("RATIO"));
        assert!(pos("RATIO") < pos("VERSION"));
    }

    /// A whole-number float const still renders a valid `f64` literal (`2` → `2.0`),
    /// tolerating the untagged carrier landing it on `Int`.
    #[test]
    fn whole_number_float_const_gets_decimal() {
        let json = r#"{
          "fluessig": {"format": 1, "emitter": "t", "compiler": "t"},
          "models": [], "unions": [],
          "consts": [{"name": "SCALE", "type": "float64", "value": 2}],
          "interfaces": [{"name": "Api", "ops": []}]
        }"#;
        let api = load_api(json).unwrap();
        let out = rust_core_binding(&api, &[], None);
        assert!(out.contains("pub const SCALE: f64 = 2.0;"));
    }

    /// A const that is NOT const-representable — a model-typed const, and a
    /// scalar const with no literal value (a runtime expression the extractor
    /// could not fold) — is SKIPPED with a doc-comment note, never a broken
    /// `pub const`.
    #[test]
    fn non_representable_consts_are_skipped_with_note() {
        let json = r#"{
          "fluessig": {"format": 1, "emitter": "t", "compiler": "t"},
          "models": [
            {"name": "Config", "fields": [
              {"name": "id", "type": "string", "nullable": false}
            ]}
          ],
          "unions": [],
          "consts": [
            {"name": "DEFAULT_CONFIG", "type": {"model": "Config"}, "value": null},
            {"name": "BUILD_STAMP", "type": "string"}
          ],
          "interfaces": [{"name": "Api", "ops": []}]
        }"#;
        let api = load_api(json).unwrap();
        let out = rust_core_binding(&api, &[], None);

        // No broken `pub const` for either.
        assert!(!out.contains("pub const DEFAULT_CONFIG"));
        assert!(!out.contains("pub const BUILD_STAMP"));
        // Both recorded as runtime-value notes.
        assert!(out
            .contains("// const DEFAULT_CONFIG: Config — not const-representable (runtime value)"));
        assert!(
            out.contains("// const BUILD_STAMP: String — not const-representable (runtime value)")
        );
    }

    /// A const-free surface is byte-identical to before this slot existed: the
    /// emitter adds nothing.
    #[test]
    fn no_consts_emits_nothing() {
        let out = rust_core_binding(&sample(), &[], None);
        assert!(!out.contains("pub const"));
        assert!(!out.contains("not const-representable"));
    }
}
