//! GENERATED by fluessig bindgen from callback_demo_wasm (api layer). Do not edit.
//! straitjacket-allow-file:duplication — the generated wasm-bindgen surface mirrors the sibling node/python/ruby demos' by design (one uniform core shape per backend).
#![allow(clippy::all)]
#![allow(unused_imports)]

// The fixed prelude — wasm-bindgen glue; core calls are fully-qualified.
use wasm_bindgen::prelude::*;

/// A core-layer failure becomes a rejected JS value (wasm-bindgen throws it):
/// a fallible op returns `Result<_, JsValue>` and raises on `Err`.
fn err(e: impl std::fmt::Display) -> JsValue {
    JsValue::from_str(&e.to_string())
}

/// A JS callback (`js_sys::Function`), marshalled into the uniform core `Box<dyn
/// Fn>`. A `js_sys::Function` is `!Send`/`!Sync`, but wasm32 is single-threaded, so
/// it is asserted `Send`/`Sync` here: the boxed closure this wraps is only ever
/// invoked on the one JS thread, and the closure owns the `WasmCb`, keeping the JS
/// `Function` alive for the callback's lifetime.
struct WasmCb(js_sys::Function);
// SAFETY: wasm32-unknown-unknown is single-threaded; the wrapped `Function` is only
// ever touched on the one JS thread, so asserting `Send`/`Sync` is sound.
unsafe impl Send for WasmCb {}
unsafe impl Sync for WasmCb {}
impl WasmCb {
    /// The JS `Function`, read through a method so a `move` closure captures the
    /// WHOLE `WasmCb` (which is `Send + Sync`). Reaching `self.0` directly would,
    /// under RFC 2229 disjoint capture, capture only the non-`Send` `Function`.
    fn func(&self) -> &js_sys::Function {
        &self.0
    }
}

/// The `Ticker` contract — implement over the engine in `crate::core_impl`.
pub trait TickerCore: Sized + Send + Sync + 'static {
    fn new() -> anyhow::Result<Self>;
    fn on_tick(&self, listener: Box<dyn Fn(i32) + Send + Sync>) -> Box<dyn Fn() + Send + Sync>;
    fn tick(&self) -> ();
}

/// A subscription handle wrapping the core's returned unsubscribe closure.
/// `unsubscribe()` removes the registered listener (idempotent — a second call is
/// a no-op). The wrapped JS callback stays alive via the core's listener
/// registration until the subscription is removed.
#[wasm_bindgen]
pub struct Subscription {
    unsub: std::sync::Mutex<Option<Box<dyn Fn() + Send + Sync>>>,
}
#[wasm_bindgen]
impl Subscription {
    /// Run the unsubscribe closure early (idempotent — a second call is a no-op).
    #[wasm_bindgen(js_name = "unsubscribe")]
    pub fn unsubscribe(&self) {
        if let Some(f) = self.unsub.lock().unwrap().take() {
            f();
        }
    }
}

/// A stateful ticker that fires registered listeners with an incrementing
/// counter. `on_tick` is a `Shape::Subscription` op — it REGISTERS a host
/// callback (a JS `Function`) and hands back an owning `Subscription` handle whose
/// unsubscribe() removes the listener; `tick` fires every live listener.
/// This is the callback + subscription slice's wasm-bindgen round-trip proof.
#[wasm_bindgen]
pub struct Ticker {
    inner: crate::core_impl::TickerImpl,
}

#[wasm_bindgen]
impl Ticker {
    /// Open a fresh ticker with no listeners and the counter at 0.
    #[wasm_bindgen(constructor)]
    pub fn new() -> Result<Ticker, JsValue> {
        Ok(Ticker {
            inner: <crate::core_impl::TickerImpl as TickerCore>::new().map_err(err)?,
        })
    }

    /// Register `listener` to be called on every `tick`; returns a Subscription
    /// handle that removes the listener when unsubscribed.
    #[wasm_bindgen(js_name = "onTick")]
    pub fn on_tick(&self, listener: js_sys::Function) -> Subscription {
        let listener: Box<dyn Fn(i32) + Send + Sync> = {
            let __cb = WasmCb(listener);
            Box::new(move |v: i32| {
                let _ = __cb.func().call1(&JsValue::NULL, &JsValue::from(v));
            })
        };
        let unsub = self.inner.on_tick(listener);
        Subscription {
            unsub: std::sync::Mutex::new(Some(unsub)),
        }
    }

    /// Fire every live listener with the current counter value, then increment it
    /// (infallible — registration/firing never fails).
    #[wasm_bindgen(js_name = "tick")]
    pub fn tick(&self) {
        self.inner.tick();
    }
}
