//! The wasm-bindgen callback demo crate — the compile-to-wasm32 gate for
//! fluessig's `ApiType::Callback` + `Shape::Subscription` lowering on the wasm
//! backend. The generated wasm-bindgen surface (`src/generated.rs`) is compiled
//! INTO this cdylib for `wasm32-unknown-unknown`; that compile IS the proof the
//! generated callback (JS `Function` → unsafe-Send `WasmCb` → uniform core
//! `Box<dyn Fn>`) and subscription (`#[wasm_bindgen]` `Subscription` handle)
//! binding is valid wasm-bindgen code (see `run.sh`).
//!
//! * `src/core_impl.rs`— the hand-written `TickerImpl` engine (the ONE hand file).
//! * `src/generated.rs`— GENERATED by `fluessig-gen` (see `regen.sh`); do not edit.
//! * `run.sh`          — compile the crate to wasm32 (the proof).

// The hand-written engine the generated wasm-bindgen layer routes through.
pub mod core_impl;

// The generated wasm-bindgen surface. Loaded as a FILE module (`#[path]`) so the
// generated file's leading inner attributes (`#![allow(...)]`) stay valid.
#[path = "generated.rs"]
pub mod generated;
