//! The Django read-plane emitter (`codegen::django_models`) against the committed
//! dogfood `catalog.json` — an assertion test (contains-checks over the emitted
//! string), matching how `tests/entl_catalog.rs` exercises the real catalog
//! rather than a brittle full-file golden (the ORM emitters carry no golden
//! precedent). The catalog exercises every branch: entities, composite keys,
//! single-column FKs (incl. an FK that is itself a composite-PK member),
//! multi-column / polymorphic FKs, and enums (with and without wire `value`s).

use fluessig::load_catalog;

const CATALOG: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/catalog.json"));

#[test]
fn django_models_emits_expected_structures() {
    let c = load_catalog(CATALOG).expect("entl catalog must validate");
    let out = fluessig::codegen::django_models(&c, None);

    // Banner + import + the table roster.
    assert!(out.starts_with("# AUTO-GENERATED by fluessig"));
    assert!(out.contains("from django.db import models"));
    assert!(out.contains("FLUESSIG_TABLES = ["));

    // A model per physical table, read-only via `managed = False` + `db_table`.
    assert!(out.contains("class Commits(models.Model):"));
    assert!(out.contains("class Meta:"));
    assert!(out.contains("managed = False"));
    assert!(out.contains("db_table = \"commits\""));

    // Single-column PK on a concrete leaf.
    assert!(out.contains("oid = models.TextField(primary_key=True"));

    // A single-column, concrete-target to-one relation → a real ForeignKey with a
    // string forward-reference, DO_NOTHING (the sink owns referential integrity),
    // an explicit db_column, and a clash-free related_name.
    assert!(out.contains(
        "repo = models.ForeignKey(\"Repos\", on_delete=models.DO_NOTHING, \
         db_column=\"repo_id\", related_name=\"commits_repo\""
    ));

    // Composite key → Django 5.2 CompositePrimaryKey, members spelled as MODEL
    // field names — including an FK member (FileChanges.commit, whose FK column is
    // commit_oid). The FK is still emitted as a ForeignKey.
    assert!(out.contains("class FileChanges(models.Model):"));
    assert!(out.contains(
        "commit = models.ForeignKey(\"Commits\", on_delete=models.DO_NOTHING, \
         db_column=\"commit_oid\""
    ));
    assert!(out.contains("pk = models.CompositePrimaryKey(\"commit\", \"path\")"));

    // Enum WITH wire values → CharField(choices=[(value, name), …]).
    assert!(out.contains(
        "status = models.CharField(max_length=1, choices=[(\"A\", \"added\"), \
         (\"M\", \"modified\"), (\"D\", \"deleted\"), (\"R\", \"renamed\")]"
    ));
    // Enum WITHOUT values → the name is used as the stored value.
    assert!(out.contains("choices=[(\"branch\", \"branch\")"));

    // Multi-column / polymorphic FK is NOT a ForeignKey: honest note + scalars.
    assert!(out.contains("# NOTE: polymorphic FK to the GhSubject family"));
    assert!(out.contains("subject_number = models.IntegerField"));

    // Nullable non-PK scalars carry null=True, blank=True.
    assert!(out.contains("null=True, blank=True"));

    // No stray unescaped newline landed inside a help_text literal (multi-line
    // docs must be escaped to keep the file parseable).
    for line in out.lines() {
        if let Some(rest) = line.split_once("help_text=\"").map(|(_, r)| r) {
            assert!(
                rest.contains('"'),
                "help_text literal not closed on its line: {line}"
            );
        }
    }
}
