//! The MCP projection gate: the tools manifest over the union fixture and the
//! entl api. (The generated Rust module's compile + runtime behavior is proven
//! by generating into a consumer crate — dispatch round-trips, cursor args,
//! envelope params; here we pin the manifest's shape and the projection rules.)

use fluessig::api::load_api;
use fluessig::bindgen::{mcp_manifest, mcp_module};

const UNION_API: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/api.json"
));
const ENTL_API: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/api.json"));

fn tool<'a>(m: &'a serde_json::Value, name: &str) -> &'a serde_json::Value {
    m["tools"]
        .as_array()
        .unwrap()
        .iter()
        .find(|t| t["name"] == name)
        .unwrap_or_else(|| panic!("tool {name} in manifest"))
}

fn tool_names(m: &serde_json::Value) -> Vec<&str> {
    m["tools"]
        .as_array()
        .unwrap()
        .iter()
        .map(|t| t["name"].as_str().unwrap())
        .collect()
}

#[test]
fn union_fixture_manifest() {
    let api = load_api(UNION_API).unwrap();
    let m = mcp_manifest(&api, &[]);
    // ctor doesn't project; unary + stream do
    assert_eq!(
        tool_names(&m),
        ["watch_events", "watch_emit", "watch_clear", "watch_run"]
    );

    // @readonly / @destructive flow into annotations
    assert_eq!(
        tool(&m, "watch_events")["annotations"]["readOnlyHint"],
        true
    );
    assert_eq!(
        tool(&m, "watch_clear")["annotations"]["destructiveHint"],
        true
    );

    // a stream is a cursor tool: after/limit params + the paging note
    let events = tool(&m, "watch_events");
    assert!(events["inputSchema"]["properties"]["after"].is_object());
    assert!(events["inputSchema"]["properties"]["limit"].is_object());
    assert!(events["description"].as_str().unwrap().contains("Paged"));

    // a union param is the discriminated oneOf envelope, bodies via $defs
    let emit = tool(&m, "watch_emit");
    let one_of = emit["inputSchema"]["properties"]["payload"]["oneOf"]
        .as_array()
        .unwrap();
    assert_eq!(one_of.len(), 3);
    assert_eq!(one_of[0]["properties"]["kind"]["const"], "message");
    assert_eq!(
        one_of[0]["required"],
        serde_json::json!(["kind", "payload"])
    );
    assert!(emit["inputSchema"]["$defs"]["AgentMessage"].is_object());

    // docs port from the tsp
    assert!(events
        .get("description")
        .unwrap()
        .as_str()
        .unwrap()
        .contains("oldest first"));
}

#[test]
fn entl_manifest_skips_binary_carriers() {
    let api = load_api(ENTL_API).unwrap();
    let m = mcp_manifest(&api, &[]);
    let names = tool_names(&m);

    // JSON-speakable ops project…
    for expect in [
        "git_diff_commits",
        "entl_query",
        "entl_sink",
        "entl_driver_plan",
    ] {
        assert!(names.contains(&expect), "{expect} missing: {names:?}");
    }
    // …binary carriers don't: queryArrow returns bytes; changes returns a
    // ChangeBatch holding an ArrowBatch. ctor/manual don't either.
    for absent in [
        "entl_query_arrow",
        "entl_changes",
        "entl_open",
        "entl_watch",
    ] {
        assert!(!names.contains(&absent), "{absent} should not project");
    }

    // optional model-bag params stay optional (sink's options is required,
    // driverPlan's is optional)
    let dp = tool(&m, "entl_driver_plan");
    assert!(dp["inputSchema"].get("required").is_none_or(|r| !r
        .as_array()
        .unwrap()
        .iter()
        .any(|v| v == "options")));
}

#[test]
fn generated_module_has_the_surface() {
    let api = load_api(UNION_API).unwrap();
    let module = mcp_module(&api, &[], Some("test-note"));
    // banner + note
    assert!(module.starts_with("//! GENERATED by fluessig mcp from union.tsp"));
    assert!(module.contains("//! test-note"));
    // serde DTOs, trait, dispatch, embedded manifest
    assert!(module.contains("pub struct Event"));
    assert!(module.contains("pub trait WatchMcp"));
    assert!(module.contains("pub fn dispatch<T0: WatchMcp>"));
    assert!(module.contains("pub const TOOLS_JSON"));
    // the embedded manifest is real JSON
    let start = module.find("r###\"").unwrap() + 5;
    let end = module.rfind("\"###").unwrap();
    let embedded: serde_json::Value = serde_json::from_str(&module[start..end]).unwrap();
    assert_eq!(embedded["tools"].as_array().unwrap().len(), 4);
}

#[test]
fn entities_cross_the_op_layer_flat() {
    // issue #10: relations lower to FK fields, to-many is omitted — so the
    // generated Rust DTO is finite (no Option<Run> self-embed, E0072-free).
    let api = load_api(UNION_API).unwrap();
    let run = api.models.iter().find(|m| m.name == "Run").unwrap();
    let names: Vec<&str> = run.fields.iter().map(|f| f.name.as_str()).collect();
    assert_eq!(
        names,
        ["id", "startedAt", "prevId", "lastSessionUid", "lastIdx"],
        "self-ref -> prevId; compound FK -> two key fields; to-many omitted"
    );
    let module = mcp_module(&api, &[], None);
    assert!(module.contains("pub prev_id: Option<String>"), "{module}");
    assert!(
        module.contains("pub last_idx: Option<i64>"),
        "typed by the target key"
    );
    // no recursive embed as a FIELD (`run()` returning Option<Run> is fine)
    assert!(!module.contains(": Option<Run>,"), "no recursive embed");
    assert!(
        module.contains("-> anyhow::Result<Option<Run>>"),
        "nullable return survives"
    );
}
