//! GENERATED by fluessig bindgen from cpp_demo (C ABI export layer). Do not edit.
//! straitjacket-allow-file:duplication — the generated per-op C ABI shims repeat a fixed marshalling shape by design.
#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unused_imports)]

// The fixed prelude — generated code uses fully-qualified paths elsewhere.
use std::ffi::{CStr, CString};
use std::os::raw::{c_char, c_int};
use std::time::Duration;
// The shared streaming contract — Poll/PollStream live in the fluessig-runtime crate.
use fluessig_runtime::{Poll, PollStream};

/// Convert an incoming C string (UTF-8, NUL-terminated) into an owned `String`.
unsafe fn fl_str_in(p: *const c_char) -> String {
    if p.is_null() {
        String::new()
    } else {
        CStr::from_ptr(p).to_string_lossy().into_owned()
    }
}

/// Hand an owned string back to C (the caller frees it with `fl_string_free`).
fn fl_str_out(s: String) -> *mut c_char {
    CString::new(s).unwrap_or_default().into_raw()
}

/// Free a string (or error message) handed out across the ABI.
#[no_mangle]
pub unsafe extern "C" fn fl_string_free(p: *mut c_char) {
    if !p.is_null() {
        drop(CString::from_raw(p));
    }
}

/// Free an error message handed out through a trailing `err_out`.
#[no_mangle]
pub unsafe extern "C" fn fl_error_free(p: *mut c_char) {
    if !p.is_null() {
        drop(CString::from_raw(p));
    }
}

/// The pull-cursor poll result across the C ABI (mirrors `Poll<T>`).
#[repr(C)]
pub enum FlPoll {
    Item = 0,
    Idle = 1,
    Closed = 2,
    Failed = 3,
}

/// The `list<String>` carrier across the C ABI (free with `fl_string_list_free`).
#[repr(C)]
pub struct FlStringList {
    pub data: *mut *mut c_char,
    pub len: usize,
}

impl Default for FlStringList {
    fn default() -> Self {
        FlStringList {
            data: std::ptr::null_mut(),
            len: 0,
        }
    }
}

unsafe fn string_list_in(ptr: *const *mut c_char, len: usize) -> Vec<String> {
    if ptr.is_null() {
        return Vec::new();
    }
    (0..len)
        .map(|i| {
            let p = ptr.add(i);
            fl_str_in(*p)
        })
        .collect()
}

fn string_list_out(v: Vec<String>) -> FlStringList {
    let mut items: Vec<*mut c_char> = v.into_iter().map(|x| fl_str_out(x)).collect();
    items.shrink_to_fit();
    let len = items.len();
    let data = items.as_mut_ptr();
    std::mem::forget(items);
    FlStringList { data, len }
}

#[no_mangle]
pub unsafe extern "C" fn fl_string_list_free(p: *mut FlStringList) {
    if p.is_null() {
        return;
    }
    let p = &mut *p;
    if !p.data.is_null() {
        let items = Vec::from_raw_parts(p.data, p.len, p.len);
        for e in items {
            fl_string_free(e);
        }
        p.data = std::ptr::null_mut();
        p.len = 0;
    }
}

/// The `Store` contract — implement over the engine in `crate::core_impl`.
pub trait StoreCore: Sized + Send + Sync + 'static {
    fn open(capacity: i32) -> anyhow::Result<Self>;
    fn put(&self, key: String, value: String) -> anyhow::Result<i32>;
    fn get(&self, key: String) -> anyhow::Result<String>;
    fn keys(&self) -> Vec<String>;
    fn remove_all(&self, keys: Vec<String>) -> i32;
    fn count(&self) -> i32;
    fn contains(&self, key: String) -> bool;
}

/// An in-memory key/value store. `put`/`get` are fallible (the error seam); the
/// observers (`keys`/`count`/`contains`/`remove_all`) are synchronous +
/// infallible (a bare `T` return, no `Result`).
// Stateful `Store` handle → `Box<crate::core_impl::StoreImpl>` behind a raw pointer.
/// Open a store with room for `capacity` entries.
/// Construct a `Store` (ctor `open`).
#[no_mangle]
pub unsafe extern "C" fn Store_new(
    capacity: i32,
    out: *mut *mut crate::core_impl::StoreImpl,
    err_out: *mut *mut c_char,
) -> c_int {
    match <crate::core_impl::StoreImpl as StoreCore>::open(capacity) {
        Ok(v) => {
            *out = Box::into_raw(Box::new(v));
            if !err_out.is_null() {
                *err_out = std::ptr::null_mut();
            }
            0
        }
        Err(e) => {
            if !err_out.is_null() {
                *err_out = fl_str_out(e.to_string());
            }
            1
        }
    }
}

/// Insert or replace `key` → `value`; returns the store's new size. Fails
/// when the store is at capacity and `key` is new.
#[no_mangle]
pub unsafe extern "C" fn Store_put(
    self_: *mut crate::core_impl::StoreImpl,
    key: *const c_char,
    value: *const c_char,
    out: *mut i32,
    err_out: *mut *mut c_char,
) -> c_int {
    let this = &*self_;
    let key = fl_str_in(key);
    let value = fl_str_in(value);
    match this.put(key, value) {
        Ok(v) => {
            *out = v;
            if !err_out.is_null() {
                *err_out = std::ptr::null_mut();
            }
            0
        }
        Err(e) => {
            if !err_out.is_null() {
                *err_out = fl_str_out(e.to_string());
            }
            1
        }
    }
}

/// Fetch the value for `key`. Fails (the reachable error path) when `key` is
/// absent.
#[no_mangle]
pub unsafe extern "C" fn Store_get(
    self_: *mut crate::core_impl::StoreImpl,
    key: *const c_char,
    out: *mut *mut c_char,
    err_out: *mut *mut c_char,
) -> c_int {
    let this = &*self_;
    let key = fl_str_in(key);
    match this.get(key) {
        Ok(v) => {
            *out = fl_str_out(v);
            if !err_out.is_null() {
                *err_out = std::ptr::null_mut();
            }
            0
        }
        Err(e) => {
            if !err_out.is_null() {
                *err_out = fl_str_out(e.to_string());
            }
            1
        }
    }
}

/// Every key currently stored, in sorted order (infallible `list<string>`).
// TODO(#69): infallible op — value returned directly, no err_out.
#[no_mangle]
pub unsafe extern "C" fn Store_keys(
    self_: *mut crate::core_impl::StoreImpl,
    out: *mut FlStringList,
) {
    let this = &*self_;
    let v = this.keys();
    *out = string_list_out(v);
}

/// Remove every key in `keys`; returns how many were actually removed
/// (infallible, `list<string>` IN + `int` out).
// TODO(#69): infallible op — value returned directly, no err_out.
#[no_mangle]
pub unsafe extern "C" fn Store_remove_all(
    self_: *mut crate::core_impl::StoreImpl,
    keys_ptr: *const *mut c_char,
    keys_len: usize,
) -> i32 {
    let this = &*self_;
    let keys = string_list_in(keys_ptr, keys_len);
    let v = this.remove_all(keys);
    v
}

/// The number of entries (infallible `int`).
// TODO(#69): infallible op — value returned directly, no err_out.
#[no_mangle]
pub unsafe extern "C" fn Store_count(self_: *mut crate::core_impl::StoreImpl) -> i32 {
    let this = &*self_;
    let v = this.count();
    v
}

/// Whether `key` is present (infallible `bool`).
// TODO(#69): infallible op — value returned directly, no err_out.
#[no_mangle]
pub unsafe extern "C" fn Store_contains(
    self_: *mut crate::core_impl::StoreImpl,
    key: *const c_char,
) -> bool {
    let this = &*self_;
    let key = fl_str_in(key);
    let v = this.contains(key);
    v
}

/// Release the `Store` handle.
#[no_mangle]
pub unsafe extern "C" fn Store_free(p: *mut crate::core_impl::StoreImpl) {
    if !p.is_null() {
        drop(Box::from_raw(p));
    }
}
