//! The C/C++ bindgen demo crate — the compile+run gate for fluessig's cpp
//! backend. The generated `extern "C"` ABI layer (`src/generated.rs`) is compiled
//! INTO this cdylib and driven by a real C (`consumer.c`) and C++
//! (`consumer.cpp`) round-trip through the committed `cpp_demo.h` / `cpp_demo.hpp`.
//!
//! * `src/schema.rs`   — the derive-authored op surface (prints catalog/api JSON).
//! * `src/core_impl.rs`— the hand-written `StoreImpl` engine (the ONE hand file).
//! * `src/generated.rs`— GENERATED by `fluessig-gen` (see `regen.sh`); do not edit.
//! * `run.sh`          — build the cdylib + compile & run both consumers.

pub mod schema;

// The hand-written engine the generated ABI layer routes through.
mod core_impl;

// The generated `extern "C"` surface. Loaded as a FILE module (`#[path]`) so the
// generated file's leading inner attributes (`#![allow(...)]`) stay valid; its
// `#[no_mangle]` exports are still hoisted into the cdylib regardless of nesting.
#[path = "generated.rs"]
mod generated;
