//! GENERATED by fluessig bindgen from the fluessig catalog (api layer). Do not edit.
//! straitjacket-allow-file:duplication — the generated napi surface mirrors the sibling python demo's by design (one uniform core shape per backend).
#![allow(unused_imports)]
#![allow(clippy::all)]

// The fixed prelude — generated code uses fully-qualified paths elsewhere.
use napi::bindgen_prelude::Result;
use napi::threadsafe_function::{ErrorStrategy, ThreadsafeFunction, ThreadsafeFunctionCallMode};
use napi_derive::napi;

fn err(e: impl std::fmt::Display) -> napi::Error {
    napi::Error::from_reason(e.to_string())
}

/// The `Ticker` contract — implement over the engine in `crate::core_impl`.
pub trait TickerCore: Sized + Send + Sync + 'static {
    fn each_tick(count: i32, listener: Box<dyn Fn(i32) + Send + Sync>) -> anyhow::Result<()>;
}

#[napi]
pub fn each_tick(
    count: i32,
    listener: ThreadsafeFunction<i32, ErrorStrategy::Fatal>,
) -> Result<()> {
    let listener_cb: Box<dyn Fn(i32) + Send + Sync> = {
        let tsfn = listener.clone();
        Box::new(move |v: i32| {
            tsfn.call(v, ThreadsafeFunctionCallMode::NonBlocking);
        })
    };
    <crate::core_impl::TickerImpl as TickerCore>::each_tick(count, listener_cb).map_err(err)
}
