//! The node (napi) callback demo crate — the compile+run gate for fluessig's
//! `ApiType::Callback` lowering on the node backend. The generated napi surface
//! (`src/generated.rs`) is compiled INTO this cdylib and driven by a real JS
//! round-trip (`consumer.mjs`), which passes a host closure into `eachTick` and
//! asserts it fired with `[0, 1, 2]` — a JS closure invoked from Rust through a
//! napi `ThreadsafeFunction`.
//!
//! * `src/core_impl.rs`— the hand-written `TickerImpl` engine (the ONE hand file).
//! * `src/generated.rs`— GENERATED by `fluessig-gen` (see `regen.sh`); do not edit.
//! * `run.sh`          — build the addon + run the JS consumer.

// The hand-written engine the generated napi layer routes through.
mod core_impl;

// The generated napi surface. Loaded as a FILE module (`#[path]`) so the
// generated file's leading inner attributes (`#![allow(...)]`) stay valid; its
// `#[napi]` exports are still registered into the addon regardless of nesting.
#[path = "generated.rs"]
mod generated;
