//! GENERATED by fluessig bindgen from callback_demo_ruby (api layer). Do not edit.
//! straitjacket-allow-file:duplication — the generated magnus surface mirrors the sibling node/python/java demos' by design (one uniform core shape per backend).
#![allow(clippy::all)]

use magnus::{function, method, prelude::*, Error, Ruby};
use std::sync::Arc;
use std::time::Duration;
// The shared streaming contract — Poll/PollStream live in the fluessig-runtime crate.
use fluessig_runtime::{Poll, PollStream};

fn rberr(e: impl std::fmt::Display) -> Error {
    let ruby = magnus::Ruby::get().expect("ticker called outside the Ruby GVL");
    Error::new(ruby.exception_runtime_error(), e.to_string())
}

/// The `Ticker` contract — implement over the engine in `crate::core_impl`.
pub trait TickerCore: Sized + Send + Sync + 'static {
    fn new() -> anyhow::Result<Self>;
    fn on_tick(&self, listener: Box<dyn Fn(i32) + Send + Sync>) -> Box<dyn Fn() + Send + Sync>;
    fn tick(&self) -> ();
}

/// A Ruby callback (`Proc`), marshalled into the uniform core `Box<dyn Fn>`. A
/// `Value` is `!Send`/`!Sync` (bound to the Ruby VM thread under the GVL); it is
/// asserted `Send`/`Sync` here because the boxed closure this wraps is only ever
/// invoked on the Ruby thread under the GVL, and the `BoxValue` pins the `Proc`
/// against GC for the subscription's lifetime.
struct RubyCb(magnus::value::BoxValue<magnus::block::Proc>);
unsafe impl Send for RubyCb {}
unsafe impl Sync for RubyCb {}
impl RubyCb {
    /// The pinned `Proc`, read through a method so a `move` closure captures the
    /// WHOLE `RubyCb` (which is `Send + Sync`). Reaching `self.0` directly would,
    /// under RFC 2229 disjoint capture, capture only the non-`Send` `BoxValue`.
    fn proc(&self) -> magnus::block::Proc {
        *self.0
    }
}

/// An opaque subscription handle owning the core's returned unsubscribe closure.
/// `unsubscribe` removes the listener early (idempotent); `Drop` removes it on GC
/// (also unsubscribing if still live). Returned by a `Shape::Subscription` op.
#[magnus::wrap(class = "Ticker::Subscription", free_immediately, size)]
struct Subscription {
    unsub: std::sync::Mutex<Option<Box<dyn Fn() + Send + Sync>>>,
}
impl Subscription {
    /// Run the unsubscribe closure early (idempotent — a second call is a no-op).
    fn unsubscribe(&self) {
        let taken = self.unsub.lock().unwrap().take();
        if let Some(f) = taken {
            f();
        }
    }
}
/// Backstop: dropping the handle (Ruby GC) unsubscribes if still live.
impl Drop for Subscription {
    fn drop(&mut self) {
        let taken = self.unsub.lock().unwrap().take();
        if let Some(f) = taken {
            f();
        }
    }
}

/// A stateful ticker that fires registered listeners with an incrementing
/// counter. `on_tick` is a `Shape::Subscription` op — it REGISTERS a host
/// callback (a Ruby `Proc`) and hands back an owning `Subscription` handle whose
/// unsubscribe()/drop removes the listener; `tick` fires every live listener.
/// This is the callback + subscription slice's Ruby (magnus) round-trip proof.
#[magnus::wrap(class = "Ticker", free_immediately, size)]
pub struct Ticker {
    core: Arc<crate::core_impl::TickerImpl>,
}

impl Ticker {
    /// Open a fresh ticker with no listeners and the counter at 0.
    fn new() -> Result<Self, Error> {
        Ok(Self {
            core: Arc::new(<crate::core_impl::TickerImpl as TickerCore>::new().map_err(rberr)?),
        })
    }
    /// Register `listener` to be called on every `tick`; returns a Subscription
    /// handle that removes the listener when unsubscribed or dropped.
    fn on_tick(&self, listener: magnus::block::Proc) -> Result<Subscription, Error> {
        let listener: Box<dyn Fn(i32) + Send + Sync> = {
            let __cb = RubyCb(magnus::value::BoxValue::new(listener));
            Box::new(move |v: i32| {
                // Invoked on the Ruby thread under the GVL (the core fires listeners
                // synchronously from a Ruby method call); re-acquiring the `Ruby` handle
                // proves the GVL, so calling the `Proc` here is sound.
                let __p = __cb.proc();
                let _: Result<magnus::Value, magnus::Error> = __p.call((v,));
            })
        };

        let unsub = self.core.on_tick(listener);
        Ok(Subscription {
            unsub: std::sync::Mutex::new(Some(unsub)),
        })
    }
    /// Fire every live listener with the current counter value, then increment it
    /// (infallible — registration/firing never fails).
    fn tick(&self) -> () {
        self.core.tick()
    }
}

/// Register the Ticker class + every generated method (called from #[magnus::init]).
pub fn register(ruby: &Ruby) -> Result<(), Error> {
    let class = ruby.define_class("Ticker", ruby.class_object())?;
    let subscription = class.define_class("Subscription", ruby.class_object())?;
    subscription.define_method("unsubscribe", method!(Subscription::unsubscribe, 0))?;
    class.define_singleton_method("new", function!(Ticker::new, 0))?;
    class.define_method("on_tick", method!(Ticker::on_tick, 1))?;
    class.define_method("tick", method!(Ticker::tick, 0))?;
    Ok(())
}
