//! The Ruby (magnus) callback demo crate — the compile+run gate for fluessig's
//! `ApiType::Callback` + `Shape::Subscription` lowering on the Ruby backend. The
//! generated magnus surface (`src/generated.rs`) is compiled INTO this cdylib and
//! driven by a real Ruby round-trip (`consumer.rb`), which subscribes a host
//! `Proc` via `on_tick`, ticks twice → sees `[0, 1]`, unsubscribes, ticks again →
//! still `[0, 1]` — a Ruby closure invoked from Rust under the GVL, then removed.
//!
//! * `src/core_impl.rs`— the hand-written `TickerImpl` engine (the ONE hand file).
//! * `src/generated.rs`— GENERATED by `fluessig-gen` (see `regen.sh`); do not edit.
//! * `run.sh`          — build the extension + run the Ruby consumer.

// The hand-written engine the generated magnus layer routes through.
pub mod core_impl;

// The generated magnus surface. Loaded as a FILE module (`#[path]`) so the
// generated file's leading inner attributes (`#![allow(...)]`) stay valid.
#[path = "generated.rs"]
pub mod generated;

/// The extension entry point. magnus emits `Init_callback_demo_ruby` from this,
/// which Ruby calls on `require "callback_demo_ruby"` (run.sh renames the built
/// cdylib to that name). Delegates to the generated `register` (defines the
/// `Ticker` class + its `Subscription` handle and every method).
#[magnus::init]
fn init(ruby: &magnus::Ruby) -> Result<(), magnus::Error> {
    generated::register(ruby)
}
