/* GENERATED by fluessig bindgen from cpp_demo (C header). Do not edit. */
/* straitjacket-allow-file:duplication — the generated per-op C ABI shims repeat a fixed marshalling shape by design. */
#ifndef FLUESSIG_CPP_DEMO_H
#define FLUESSIG_CPP_DEMO_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The pull-cursor poll result. */
typedef enum FlPoll {
    FL_POLL_ITEM = 0,
    FL_POLL_IDLE = 1,
    FL_POLL_CLOSED = 2,
    FL_POLL_FAILED = 3
} FlPoll;

typedef struct FlStringList {
    char** data;
    size_t len;
} FlStringList;

typedef struct Store Store;
typedef struct Ticker Ticker;
typedef struct Subscription Subscription;

/* Store */
int Store_new(int32_t capacity, Store** out, char** err_out);
int Store_put(Store* self, const char* key, const char* value, int32_t* out, char** err_out);
int Store_get(Store* self, const char* key, char** out, char** err_out);
void Store_keys(Store* self, FlStringList* out);
int32_t Store_remove_all(Store* self, const char** keys, size_t keys_len);
int32_t Store_count(Store* self);
bool Store_contains(Store* self, const char* key);

/* Ticker */
int Ticker_new(Ticker** out, char** err_out);
int Ticker_on_tick(Ticker* self, void (*listener)(void* ctx, int32_t v), void* listener_ctx, Subscription** out, char** err_out);
void Ticker_tick(Ticker* self);

/* memory management */
void fl_string_free(char* p);
void fl_error_free(char* p);
void fl_string_list_free(FlStringList* p);
void Store_free(Store* self);
void Ticker_free(Ticker* self);
void Subscription_unsubscribe(Subscription* s);
void Subscription_free(Subscription* s);

#ifdef __cplusplus
}
#endif
#endif /* FLUESSIG_CPP_DEMO_H */
