// GENERATED by fluessig bindgen from cpp_demo (C++ wrapper). Do not edit.
// straitjacket-allow-file:duplication — the generated per-op C ABI shims repeat a fixed marshalling shape by design.
#ifndef FLUESSIG_CPP_DEMO_HPP
#define FLUESSIG_CPP_DEMO_HPP

#include "cpp_demo.h"
#include <string>
#include <vector>
#include <optional>
#include <stdexcept>
#include <utility>
#include <functional>

namespace fluessig {

/// A fallible-op failure. Carries the C error message; the C
/// buffer is freed once copied into this exception.
struct Error : std::runtime_error {
    explicit Error(char* msg)
        : std::runtime_error(msg ? std::string(msg) : std::string()) {
        if (msg) { fl_error_free(msg); }
    }
};

/// The pull-cursor poll status (mirrors FlPoll).
enum class Poll { Item = FL_POLL_ITEM, Idle = FL_POLL_IDLE, Closed = FL_POLL_CLOSED, Failed = FL_POLL_FAILED };

// Unions cross as their JSON envelope text — the C++ surface exposes std::string.

/// RAII subscription handle: unsubscribe()/destroy removes the listener.
class Subscription {
public:
    Subscription(::Subscription* h, void* ctx, void (*deleter)(void*))
        : h_(h), ctx_(ctx), deleter_(deleter) {}
    Subscription(Subscription&& o) noexcept
        : h_(o.h_), ctx_(o.ctx_), deleter_(o.deleter_) { o.h_ = nullptr; o.ctx_ = nullptr; o.deleter_ = nullptr; }
    Subscription(const Subscription&) = delete;
    Subscription& operator=(const Subscription&) = delete;
    ~Subscription() {
        if (h_) { ::Subscription_free(h_); }
        if (ctx_ && deleter_) { deleter_(ctx_); }
    }
    /// Remove the listener early (idempotent).
    void unsubscribe() { if (h_) { ::Subscription_unsubscribe(h_); } }

private:
    ::Subscription* h_ = nullptr;
    void* ctx_ = nullptr;
    void (*deleter_)(void*) = nullptr;
};

/// An in-memory key/value store. `put`/`get` are fallible (the error seam); the
/// observers (`keys`/`count`/`contains`/`remove_all`) are synchronous +
/// infallible (a bare `T` return, no `Result`).
class Store {
public:
    explicit Store(int32_t capacity) {
        char* err = nullptr;
        if (::Store_new(capacity, &h_, &err)) { throw Error(err); }
    }
    Store(Store&& o) noexcept : h_(o.h_) { o.h_ = nullptr; }
    Store(const Store&) = delete;
    Store& operator=(const Store&) = delete;
    ~Store() { if (h_) { ::Store_free(h_); } }

    /// Insert or replace `key` → `value`; returns the store's new size. Fails
    /// when the store is at capacity and `key` is new.
    int32_t put(std::string key, std::string value) {
        int32_t out{};
        char* err = nullptr;
        if (::Store_put(h_, key.c_str(), value.c_str(), &out, &err)) { throw Error(err); }
        return out;
    }
    /// Fetch the value for `key`. Fails (the reachable error path) when `key` is
    /// absent.
    std::string get(std::string key) {
        char* out = nullptr;
        char* err = nullptr;
        if (::Store_get(h_, key.c_str(), &out, &err)) { throw Error(err); }
        std::string r(out ? out : "");
        fl_string_free(out);
        return r;
    }
    /// Every key currently stored, in sorted order (infallible `list<string>`).
    std::vector<std::string> keys() {
        FlStringList out{};
        ::Store_keys(h_, &out);
        std::vector<std::string> r;
        r.reserve(out.len);
        for (size_t i = 0; i < out.len; ++i) { r.emplace_back(out.data[i] ? out.data[i] : ""); }
        ::fl_string_list_free(&out);
        return r;
    }
    /// Remove every key in `keys`; returns how many were actually removed
    /// (infallible, `list<string>` IN + `int` out).
    int32_t remove_all(std::vector<std::string> keys) {
        std::vector<const char*> keys_c;
        keys_c.reserve(keys.size());
        for (const auto& s : keys) { keys_c.push_back(s.c_str()); }
        return ::Store_remove_all(h_, keys_c.data(), keys_c.size());
    }
    /// The number of entries (infallible `int`).
    int32_t count() {
        return ::Store_count(h_);
    }
    /// Whether `key` is present (infallible `bool`).
    bool contains(std::string key) {
        return ::Store_contains(h_, key.c_str());
    }

private:
    ::Store* h_ = nullptr;
};

/// A stateful ticker that fires registered listeners with an incrementing
/// counter. `on_tick` is a `Shape::Subscription` op — it REGISTERS a host
/// callback and hands back an owning `Subscription` handle whose
/// unsubscribe()/drop removes the listener; `tick` fires every live listener.
/// This is the callback + subscription slice's real C/C++ round-trip proof.
class Ticker {
public:
    explicit Ticker() {
        char* err = nullptr;
        if (::Ticker_new(&h_, &err)) { throw Error(err); }
    }
    Ticker(Ticker&& o) noexcept : h_(o.h_) { o.h_ = nullptr; }
    Ticker(const Ticker&) = delete;
    Ticker& operator=(const Ticker&) = delete;
    ~Ticker() { if (h_) { ::Ticker_free(h_); } }

    /// Register `listener` to be called on every `tick`; returns a Subscription
    /// handle that removes the listener when unsubscribed or dropped.
    Subscription on_tick(std::function<void(int32_t)> listener) {
        auto* ctx = new std::function<void(int32_t)>(std::move(listener));
        auto thunk = [](void* c, int32_t v) { (*static_cast<std::function<void(int32_t)>*>(c))(v); };
        auto deleter = [](void* c) { delete static_cast<std::function<void(int32_t)>*>(c); };
        ::Subscription* out = nullptr;
        char* err = nullptr;
        if (::Ticker_on_tick(h_, thunk, ctx, &out, &err)) { deleter(ctx); throw Error(err); }
        return Subscription(out, ctx, deleter);
    }
    /// Fire every live listener with the current counter value, then increment it
    /// (infallible — registration/firing never fails).
    void tick() {
        ::Ticker_tick(h_);
    }

private:
    ::Ticker* h_ = nullptr;
};

} // namespace fluessig

#endif // FLUESSIG_CPP_DEMO_HPP
