// GENERATED by fluessig bindgen from cpp_demo (C++ wrapper). Do not edit.
// straitjacket-allow-file:duplication — the generated per-op C ABI shims repeat a fixed marshalling shape by design.
#ifndef FLUESSIG_CPP_DEMO_HPP
#define FLUESSIG_CPP_DEMO_HPP

#include "cpp_demo.h"
#include <string>
#include <vector>
#include <optional>
#include <stdexcept>
#include <utility>

namespace fluessig {

/// A fallible-op failure. Carries the C error message; the C
/// buffer is freed once copied into this exception.
struct Error : std::runtime_error {
    explicit Error(char* msg)
        : std::runtime_error(msg ? std::string(msg) : std::string()) {
        if (msg) { fl_error_free(msg); }
    }
};

/// The pull-cursor poll status (mirrors FlPoll).
enum class Poll { Item = FL_POLL_ITEM, Idle = FL_POLL_IDLE, Closed = FL_POLL_CLOSED, Failed = FL_POLL_FAILED };

// Unions cross as their JSON envelope text — the C++ surface exposes std::string.

/// An in-memory key/value store. `put`/`get` are fallible (the error seam); the
/// observers (`keys`/`count`/`contains`/`remove_all`) are synchronous +
/// infallible (a bare `T` return, no `Result`).
class Store {
public:
    explicit Store(int32_t capacity) {
        char* err = nullptr;
        if (::Store_new(capacity, &h_, &err)) { throw Error(err); }
    }
    Store(Store&& o) noexcept : h_(o.h_) { o.h_ = nullptr; }
    Store(const Store&) = delete;
    Store& operator=(const Store&) = delete;
    ~Store() { if (h_) { ::Store_free(h_); } }

    /// Insert or replace `key` → `value`; returns the store's new size. Fails
    /// when the store is at capacity and `key` is new.
    int32_t put(std::string key, std::string value) {
        int32_t out{};
        char* err = nullptr;
        if (::Store_put(h_, key.c_str(), value.c_str(), &out, &err)) { throw Error(err); }
        return out;
    }
    /// Fetch the value for `key`. Fails (the reachable error path) when `key` is
    /// absent.
    std::string get(std::string key) {
        char* out = nullptr;
        char* err = nullptr;
        if (::Store_get(h_, key.c_str(), &out, &err)) { throw Error(err); }
        std::string r(out ? out : "");
        fl_string_free(out);
        return r;
    }
    /// Every key currently stored, in sorted order (infallible `list<string>`).
    std::vector<std::string> keys() {
        FlStringList out{};
        ::Store_keys(h_, &out);
        std::vector<std::string> r;
        r.reserve(out.len);
        for (size_t i = 0; i < out.len; ++i) { r.emplace_back(out.data[i] ? out.data[i] : ""); }
        ::fl_string_list_free(&out);
        return r;
    }
    /// Remove every key in `keys`; returns how many were actually removed
    /// (infallible, `list<string>` IN + `int` out).
    int32_t remove_all(std::vector<std::string> keys) {
        std::vector<const char*> keys_c;
        keys_c.reserve(keys.size());
        for (const auto& s : keys) { keys_c.push_back(s.c_str()); }
        return ::Store_remove_all(h_, keys_c.data(), keys_c.size());
    }
    /// The number of entries (infallible `int`).
    int32_t count() {
        return ::Store_count(h_);
    }
    /// Whether `key` is present (infallible `bool`).
    bool contains(std::string key) {
        return ::Store_contains(h_, key.c_str());
    }

private:
    ::Store* h_ = nullptr;
};

} // namespace fluessig

#endif // FLUESSIG_CPP_DEMO_HPP
