//! GENERATED by fluessig bindgen from java_demo (api layer, Rust JNI glue). Do not edit.
#![allow(clippy::all)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(non_snake_case)]
#![allow(dead_code)]

use fluessig_runtime::{Poll, PollStream};
use jni::objects::{JByteArray, JClass, JObject, JString, JValue};
use jni::sys::{jboolean, jbyteArray, jdouble, jfloat, jint, jlong, jobject, jstring};
use jni::JNIEnv;
use std::sync::Arc;
use std::time::Duration;

/// A core-layer failure becomes a thrown Java `RuntimeException` (JNI is
/// synchronous; a fallible op raises and returns the JNI zero value). An
/// `#[fluessig(async)]` op wraps this same blocking call in a Java
/// `CompletableFuture`, so a rejected future rides the same seam.
fn throw(env: &mut JNIEnv, e: impl std::fmt::Display) {
    let _ = env.throw_new("java/lang/RuntimeException", e.to_string());
}

/// An opaque subscription handle owning the core's returned unsubscribe closure.
struct Subscription {
    unsub: std::sync::Mutex<Option<Box<dyn Fn() + Send + Sync>>>,
}

/// Run the unsubscribe closure early (idempotent — a second call is a no-op).
#[no_mangle]
pub extern "system" fn Java_fluessig_Subscription_nativeUnsubscribe<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
) {
    if handle == 0 {
        return;
    }
    let s = unsafe { &*(handle as *const Subscription) };
    let __taken = s.unsub.lock().unwrap().take();
    if let Some(__f) = __taken {
        __f();
    }
}

/// Free the subscription handle, unsubscribing if still live (idempotent).
#[no_mangle]
pub extern "system" fn Java_fluessig_Subscription_nativeFree<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
) {
    if handle == 0 {
        return;
    }
    let s = unsafe { Box::from_raw(handle as *mut Subscription) };
    let __taken = s.unsub.lock().unwrap().take();
    if let Some(__f) = __taken {
        __f();
    }
}

/// One streamed record — a flat scalar DTO the `items` stream yields.
#[derive(Clone)]
pub struct Item {
    pub id: i64,
    pub label: String,
}

/// Construct a Java `fluessig/Item` from its Rust value.
fn Item_to_j<'a>(env: &mut JNIEnv<'a>, v: Item) -> JObject<'a> {
    let __f_label = env
        .new_string(&v.label)
        .map(JObject::from)
        .unwrap_or_default();
    let __cls = env.find_class("fluessig/Item").expect("find Item");
    env.new_object(
        &__cls,
        "(JLjava/lang/String;)V",
        &[JValue::Long(v.id), JValue::Object(&__f_label)],
    )
    .expect("new Item")
}

/// Read a Rust `Item` back out of a Java `fluessig/Item`.
fn Item_from_j<'a>(env: &mut JNIEnv<'a>, o: &JObject<'a>) -> Item {
    let id = env
        .call_method(o, "getId", "()J", &[])
        .unwrap()
        .j()
        .unwrap();
    let label = {
        let __s = env
            .call_method(o, "getLabel", "()Ljava/lang/String;", &[])
            .unwrap()
            .l()
            .unwrap();
        env.get_string(&JString::from(__s))
            .map(Into::into)
            .unwrap_or_default()
    };
    Item { id, label }
}

/// The `Store` contract — implement over the engine in `crate::core_impl`.
pub trait StoreCore: Sized + Send + Sync + 'static {
    fn open(seed: i64) -> anyhow::Result<Self>;
    fn version(&self) -> String;
    fn checked(&self, key: String) -> anyhow::Result<i64>;
    fn count(&self, prefix: String) -> anyhow::Result<i64>;
    fn items(&self) -> anyhow::Result<Box<dyn PollStream<Item>>>;
}

/// The `Ticker` contract — implement over the engine in `crate::core_impl`.
pub trait TickerCore: Sized + Send + Sync + 'static {
    fn new() -> anyhow::Result<Self>;
    fn on_tick(&self, listener: Box<dyn Fn(i32) + Send + Sync>) -> Box<dyn Fn() + Send + Sync>;
    fn tick(&self) -> ();
}

/// Poll the `Store.items` cursor once: an item (as its Java object),
/// null on clean close, or a thrown exception on a terminal failure.
#[no_mangle]
pub extern "system" fn Java_fluessig_Items_poll<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    cursor: jlong,
) -> jobject {
    let env = &mut env;
    let __stream = unsafe { &*(cursor as *const Box<dyn PollStream<Item>>) };
    loop {
        match __stream.poll(Duration::from_millis(500)) {
            Poll::Item(__v) => return Item_to_j(env, __v).into_raw(),
            Poll::Idle => continue,
            Poll::Closed => return std::ptr::null_mut(),
            Poll::Failed(__e) => {
                throw(env, __e);
                return std::ptr::null_mut();
            }
        }
    }
}

/// Release the `Store.items` cursor (idempotent on the Java side).
#[no_mangle]
pub extern "system" fn Java_fluessig_Items_free<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    cursor: jlong,
) {
    if cursor != 0 {
        unsafe {
            drop(Box::from_raw(cursor as *mut Box<dyn PollStream<Item>>));
        }
    }
}

/// Construct the `Store` core and hand Java an opaque `long` handle
/// (a leaked `Box<Arc<StoreImpl>>`); `free` reclaims it.
#[no_mangle]
pub extern "system" fn Java_fluessig_Store_init<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    seed_j: jlong,
) -> jlong {
    let env = &mut env;
    let seed = seed_j as i64;
    match <crate::core_impl::StoreImpl as StoreCore>::open(seed) {
        Ok(__c) => Box::into_raw(Box::new(Arc::new(__c))) as jlong,
        Err(__e) => {
            throw(env, __e);
            0
        }
    }
}

/// Drop the `Store` handle (idempotent on the Java side).
#[no_mangle]
pub extern "system" fn Java_fluessig_Store_free<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
) {
    if handle != 0 {
        unsafe {
            drop(Box::from_raw(
                handle as *mut Arc<crate::core_impl::StoreImpl>,
            ));
        }
    }
}

#[no_mangle]
pub extern "system" fn Java_fluessig_Store_version<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
) -> jstring {
    let env = &mut env;
    let core = unsafe { &*(handle as *const Arc<crate::core_impl::StoreImpl>) };
    let __v = core.version();
    env.new_string(&__v)
        .map(|s| s.into_raw())
        .unwrap_or(std::ptr::null_mut())
}

#[no_mangle]
pub extern "system" fn Java_fluessig_Store_checked<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
    key_j: JString<'local>,
) -> jlong {
    let env = &mut env;
    let key: String = env.get_string(&key_j).map(Into::into).unwrap_or_default();
    let core = unsafe { &*(handle as *const Arc<crate::core_impl::StoreImpl>) };
    match core.checked(key) {
        Ok(__v) => __v as jlong,
        Err(__e) => {
            throw(env, __e);
            0
        }
    }
}

#[no_mangle]
pub extern "system" fn Java_fluessig_Store_nativeCount<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
    prefix_j: JString<'local>,
) -> jlong {
    let env = &mut env;
    let prefix: String = env
        .get_string(&prefix_j)
        .map(Into::into)
        .unwrap_or_default();
    let core = unsafe { &*(handle as *const Arc<crate::core_impl::StoreImpl>) };
    match core.count(prefix) {
        Ok(__v) => __v as jlong,
        Err(__e) => {
            throw(env, __e);
            0
        }
    }
}

/// Open the `Store.items` stream: returns an opaque cursor handle
/// (a leaked `Box<Box<dyn PollStream<Item>>>`) the `Items` class polls.
#[no_mangle]
pub extern "system" fn Java_fluessig_Store_nativeItems<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
) -> jlong {
    let env = &mut env;
    match {
        let core = unsafe { &*(handle as *const Arc<crate::core_impl::StoreImpl>) };
        core.items()
    } {
        Ok(__s) => Box::into_raw(Box::new(__s)) as jlong,
        Err(__e) => {
            throw(env, __e);
            0
        }
    }
}

/// Construct the `Ticker` core and hand Java an opaque `long` handle
/// (a leaked `Box<Arc<TickerImpl>>`); `free` reclaims it.
#[no_mangle]
pub extern "system" fn Java_fluessig_Ticker_init<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
) -> jlong {
    let env = &mut env;
    match <crate::core_impl::TickerImpl as TickerCore>::new() {
        Ok(__c) => Box::into_raw(Box::new(Arc::new(__c))) as jlong,
        Err(__e) => {
            throw(env, __e);
            0
        }
    }
}

/// Drop the `Ticker` handle (idempotent on the Java side).
#[no_mangle]
pub extern "system" fn Java_fluessig_Ticker_free<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
) {
    if handle != 0 {
        unsafe {
            drop(Box::from_raw(
                handle as *mut Arc<crate::core_impl::TickerImpl>,
            ));
        }
    }
}

/// Register a listener on `Ticker.on_tick`; returns an opaque `long` handle
/// (a leaked `Box<Subscription>`) the `Subscription` class owns.
#[no_mangle]
pub extern "system" fn Java_fluessig_Ticker_nativeOnTick<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
    listener_j: JObject<'local>,
) -> jlong {
    let env = &mut env;
    let listener: Box<dyn Fn(i32) + Send + Sync> = {
        let __global = env
            .new_global_ref(&listener_j)
            .expect("callback `listener`: new_global_ref");
        let __vm = env.get_java_vm().expect("callback `listener`: get_java_vm");
        Box::new(move |v: i32| {
            let mut __guard = match __vm.attach_current_thread() {
                Ok(g) => g,
                Err(_) => return,
            };
            let env = &mut *__guard;
            let __a0 = env
                .new_object("java/lang/Integer", "(I)V", &[JValue::Int(v)])
                .expect("box Integer");
            let _ = env.call_method(
                __global.as_obj(),
                "accept",
                "(Ljava/lang/Object;)V",
                &[JValue::Object(&__a0)],
            );
        })
    };
    let __unsub = {
        let core = unsafe { &*(handle as *const Arc<crate::core_impl::TickerImpl>) };
        core.on_tick(listener)
    };
    Box::into_raw(Box::new(Subscription {
        unsub: std::sync::Mutex::new(Some(__unsub)),
    })) as jlong
}

#[no_mangle]
pub extern "system" fn Java_fluessig_Ticker_tick<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
) {
    let env = &mut env;
    let core = unsafe { &*(handle as *const Arc<crate::core_impl::TickerImpl>) };
    let __v = core.tick();
    ()
}
