//! The Java (JNI) round-trip harness cdylib.
//!
//! `generated.rs` is produced by `fluessig-gen --java` from the `java-demo-schema`
//! schema (regenerated by `run.sh`, committed so the crate builds standalone). It
//! defines the `#[no_mangle] extern "system"` JNI entry points, the `StoreCore`
//! trait, and the `Item` DTO. `core_impl` hand-implements `StoreCore` over a
//! trivial deterministic engine — the seam the generated glue routes into.
//!
//! Building this crate emits `libfluessig.so`, the library `Store.java` /
//! `Items.java` load via `System.loadLibrary("fluessig")`.

pub mod core_impl;

#[path = "generated.rs"]
pub mod generated;
