//! ORM read-plane codegen (notes/plan.txt Step 5) — the catalog projected into
//! committed language artifacts, via **genco** (whitespace-aware quasi-quoting
//! with automatic import management):
//!
//! - [`python_models`] → `entl.models` (SQLAlchemy, read-only guards included) —
//!   replaces entl-python's hand-written `gen_models.py`.
//! - [`ts_tables`] → `tables.gen.ts` (the typed `EntlTables` enum) and
//! - [`ts_drizzle`] → `schema.gen.ts` (the Drizzle pg-core schema) — replace
//!   entl-node's introspection-driven `gen-tables.ts`.
//!
//! All three read the same physical projection the DDL back-end uses
//! ([`crate::sql::tables`]), so models/types/DDL agree by construction.

use genco::prelude::*;

use crate::ir::{camel, Catalog};
use crate::sql::{tables, Dialect, TableDef};

/// snake_case → PascalCase (`gh_pull_requests` → `GhPullRequests`).
fn pascal(s: &str) -> String {
    let c = camel(s);
    let mut it = c.chars();
    it.next()
        .map(|f| f.to_ascii_uppercase().to_string() + it.as_str())
        .unwrap_or_default()
}

/// The generic banner (named after the catalog's own `source`, e.g. `entl.tsp`)
/// plus the caller's optional extra note line (e.g. a lint-suppression marker or
/// a regenerate hint) — fluessig itself bakes no consumer-specific paths or
/// prose into its output; that all arrives via the note.
fn banner_with(source: Option<&str>, note: Option<&str>) -> String {
    let src = source.unwrap_or("the fluessig catalog");
    let banner = format!("AUTO-GENERATED by fluessig from {src}. Do not edit by hand.");
    match note {
        Some(n) => format!("{banner}\n{n}"),
        None => banner,
    }
}

/// `entl.models` — the SQLAlchemy read-plane. Typed generically so the same
/// models work against any store the data was sunk into (SQLite/Postgres):
/// object-ids come back as hex strings, timestamps as RFC3339 strings. The
/// models are READ-ONLY: `create_all`/`drop_all` are guarded — the sink owns
/// the schema.
pub fn python_models(c: &Catalog, banner_note: Option<&str>) -> String {
    let defs = tables(c, Dialect::Postgres);
    let column = &python::import("sqlalchemy", "Column");
    let event = &python::import("sqlalchemy", "event");
    let declarative_base = &python::import("sqlalchemy.orm", "declarative_base");

    // the Postgres projection's type → the generic SQLAlchemy read type
    let py_type = |ty: &str| match ty {
        "boolean" => python::import("sqlalchemy", "Boolean"),
        "integer" | "bigint" => python::import("sqlalchemy", "Integer"),
        _ => python::import("sqlalchemy", "String"), // text / hex oids / RFC3339 timestamps / json
    };

    let classes: Vec<python::Tokens> = defs
        .iter()
        .map(|(name, def)| {
            let cols: Vec<python::Tokens> = def
                .columns
                .iter()
                .map(|col| {
                    let ty = py_type(&col.ty);
                    let pk = def.pk.contains(&col.name);
                    let n = &col.name;
                    match (pk, col.not_null) {
                        (true, _) => quote!($n = $column($ty, primary_key=True)),
                        (false, true) => quote!($n = $column($ty, nullable=False)),
                        (false, false) => quote!($n = $column($ty)),
                    }
                })
                .collect();
            let cls = pascal(name);
            quote! {
                class $cls(Base):
                    __tablename__ = $(quoted(name.as_str()))
                    $(for c in cols join ($['\r']) => $c)
            }
        })
        .collect();

    let table_names: Vec<&String> = defs.keys().collect();
    let t: python::Tokens = quote! {
        Base = $declarative_base()


        def _read_only(action):
            $(quoted("entl owns the schema via its sink; the ORM is a pure read projection."))
            def _guard(*_args, **_kw):
                raise RuntimeError(
                    "entl.models are read-only: the entl sink owns the schema, so " + action + " is "
                    "disallowed here. Create tables by sinking data with entl, not through SQLAlchemy."
                )
            return _guard


        $("# Abort any attempt to emit DDL from these models (create_all / drop_all) before it")
        $("# runs, so the models can never author a schema that drifts from what the sink writes.")
        $event.listen(Base.metadata, "before_create", _read_only("create_all()"))
        $event.listen(Base.metadata, "before_drop", _read_only("drop_all()"))

        $("#: Every table entl writes, by table name.")
        ENTL_TABLES = [
            $(for n in table_names join ($['\r']) => $(quoted(n.as_str())),)
        ]

        $(for cls in classes join ($['\n']) => $cls)
    };
    let body = t.to_file_string().expect("python renders");
    format!(
        "# {}\n\n{}",
        banner_with(c.source.as_deref(), banner_note).replace('\n', "\n# "),
        body
    )
}

/// `tables.gen.ts` — the typed `EntlTables` enum + `ENTL_TABLES`. Excludes
/// `sync_state` (internal bookkeeping, never mirrored — matching introspect.ts).
pub fn ts_tables(c: &Catalog, banner_note: Option<&str>) -> String {
    let defs = mirrored(c);
    let entries: Vec<js::Tokens> = defs
        .iter()
        .map(|(name, _)| quote!($(camel(name)): $(quoted(name.as_str())),))
        .collect();
    let t: js::Tokens = quote! {
        $("/** The entl tables, as a typed enum. Pass `EntlTables.ghPullRequests` to syncInto. */")
        export const EntlTables = {
            $(for e in entries join ($['\r']) => $e)
        } as const;

        export type EntlTable = (typeof EntlTables)[keyof typeof EntlTables];

        $("/** Every entl table name (the values of EntlTables). */")
        export const ENTL_TABLES = Object.values(EntlTables) as EntlTable[];
    };
    format!(
        "// {}\n\n{}",
        banner_with(c.source.as_deref(), banner_note).replace('\n', "\n// "),
        t.to_file_string().expect("ts renders")
    )
}

/// `schema.gen.ts` — the Drizzle (pg-core) schema for every mirrored table:
/// the typed read contract for the Postgres/PGlite mirror.
pub fn ts_drizzle(c: &Catalog, banner_note: Option<&str>) -> String {
    let defs = mirrored(c);
    let pg_schema = &js::import("drizzle-orm/pg-core", "pgSchema");
    let primary_key = &js::import("drizzle-orm/pg-core", "primaryKey");

    let table_defs: Vec<js::Tokens> = defs
        .iter()
        .map(|(name, def)| {
            let cols: Vec<js::Tokens> = def
                .columns
                .iter()
                .map(|col| {
                    let n = camel(&col.name);
                    let q = quoted(col.name.as_str());
                    let base: js::Tokens = match col.ty.as_str() {
                        "boolean" => {
                            let f = &js::import("drizzle-orm/pg-core", "boolean");
                            quote!($n: $f($q))
                        }
                        "integer" => {
                            let f = &js::import("drizzle-orm/pg-core", "integer");
                            quote!($n: $f($q))
                        }
                        "bigint" => {
                            let f = &js::import("drizzle-orm/pg-core", "bigint");
                            quote!($n: $f($q, { mode: "number" }))
                        }
                        "timestamptz" => {
                            let f = &js::import("drizzle-orm/pg-core", "timestamp");
                            quote!($n: $f($q, { withTimezone: true }))
                        }
                        "real" | "double precision" => {
                            let f = &js::import("drizzle-orm/pg-core", "doublePrecision");
                            quote!($n: $f($q))
                        }
                        "numeric" => {
                            let f = &js::import("drizzle-orm/pg-core", "numeric");
                            quote!($n: $f($q))
                        }
                        _ => {
                            // text, hex oids, RFC3339-as-timestamptz never lands here, jsonb → text
                            let f = &js::import("drizzle-orm/pg-core", "text");
                            quote!($n: $f($q))
                        }
                    };
                    if col.not_null {
                        quote!($base.notNull(),)
                    } else {
                        quote!($base,)
                    }
                })
                .collect();
            let pk_cols: Vec<String> = def.pk.iter().map(|p| format!("t.{}", camel(p))).collect();
            let pk = pk_cols.join(", ");
            quote! {
                export const $(camel(name)) = entl.table($(quoted(name.as_str())), {
                    $(for cl in cols join ($['\r']) => $cl)
                },
                    (t) => [$primary_key({ columns: [$pk] })]);
            }
        })
        .collect();

    let t: js::Tokens = quote! {
        $("/** The Postgres schema entl's tables are mirrored into by `syncInto`. */")
        export const entl = $pg_schema("entl");

        $(for d in table_defs join ($['\n']) => $d)
    };
    format!(
        "// {}\n\n{}",
        banner_with(c.source.as_deref(), banner_note).replace('\n', "\n// "),
        t.to_file_string().expect("ts renders")
    )
}

/// The mirrored table set: everything except internal bookkeeping.
fn mirrored(c: &Catalog) -> Vec<(String, TableDef)> {
    tables(c, Dialect::Postgres)
        .into_iter()
        .filter(|(name, _)| name != "sync_state")
        .collect()
}
