//! GENERATED by fluessig bindgen from callback_demo_php (api layer). Do not edit.
//! straitjacket-allow-file:duplication — the generated ext-php-rs surface mirrors the sibling node/python/java/ruby/wasm demos' by design (one uniform core shape per backend). PHP callbacks are documented SYNC-ONLY — see the PhpCb marker.
#![allow(clippy::all)]
#![allow(unused_imports)]

// The fixed prelude — generated code uses fully-qualified paths elsewhere.
use ext_php_rs::prelude::*;
use std::sync::Arc;
use std::time::Duration;
// The shared streaming contract — Poll/PollStream live in the fluessig-runtime crate.
use fluessig_runtime::{Poll, PollStream};

/// A core-layer failure becomes a thrown PHP exception (PHP is synchronous,
/// so a fallible op returns `PhpResult` and ext-php-rs raises on `Err`).
fn err(e: impl std::fmt::Display) -> PhpException {
    PhpException::default(e.to_string())
}
/// A PHP callback (a `callable`/`Closure` `Zval`), marshalled into the uniform
/// core `Box<dyn Fn>`.
///
/// # SYNC-ONLY — off-thread invocation is undefined behaviour
///
/// A PHP callable is `!Send`/`!Sync`: it is bound to the PHP request thread, and
/// PHP's single-thread request model CANNOT invoke it from a background thread.
/// `PhpCb` asserts `Send`/`Sync` so the callable can ride the uniform
/// `Box<dyn Fn(..) + Send + Sync>` core shape, but that assertion is SOUND ONLY
/// when the boxed closure is invoked SYNCHRONOUSLY on the SAME PHP request thread
/// that supplied the callable (e.g. a `Shape::Subscription` op whose core fires
/// its listeners synchronously from a PHP method call). Invoking it from any other
/// thread is UNSUPPORTED and undefined behaviour. This is pidgin's one backend
/// where the forward-only callback contract genuinely fights the runtime; the
/// restriction is surfaced here explicitly (see notes/callback-function-types.md)
/// rather than silently mis-lowered.
///
/// The owned `ZendCallable<'static>` keeps the underlying callable alive for the
/// subscription's whole lifetime (the callable `Zval` was `shallow_clone`d, which
/// bumps its refcount, before being handed to `new_owned`).
struct PhpCb(ext_php_rs::types::ZendCallable<'static>);
// SAFETY: sound ONLY under the sync-only contract above — the wrapped callable is
// only ever invoked on the PHP request thread that supplied it. Off-thread
// invocation is undefined behaviour.
unsafe impl Send for PhpCb {}
unsafe impl Sync for PhpCb {}
impl PhpCb {
    /// The owned callable, read through a method so a `move` closure captures the
    /// WHOLE `PhpCb` (which is `Send + Sync`). Reaching `self.0` directly would,
    /// under RFC 2229 disjoint capture, capture only the non-`Send` `ZendCallable`.
    fn callable(&self) -> &ext_php_rs::types::ZendCallable<'static> {
        &self.0
    }
}

/// An opaque subscription handle owning the core's returned unsubscribe closure.
/// `unsubscribe()` removes the registered listener early (idempotent — a second
/// call is a no-op). Returned by a `Shape::Subscription` op. The wrapped PHP
/// callable stays alive via the core's listener registration until the
/// subscription is removed (dropping the handle releases it on the PHP request
/// thread — see the sync-only contract on `PhpCb`).
#[php_class]
pub struct Subscription {
    unsub: std::sync::Mutex<Option<Box<dyn Fn() + Send + Sync>>>,
}
#[php_impl]
impl Subscription {
    /// Run the unsubscribe closure early (idempotent — a second call is a no-op).
    pub fn unsubscribe(&self) {
        let taken = self.unsub.lock().unwrap().take();
        if let Some(f) = taken {
            f();
        }
    }
}

/// The `Ticker` contract — implement over the engine in `crate::core_impl`.
pub trait TickerCore: Sized + Send + Sync + 'static {
    fn new() -> anyhow::Result<Self>;
    fn on_tick(&self, listener: Box<dyn Fn(i32) + Send + Sync>) -> Box<dyn Fn() + Send + Sync>;
    fn tick(&self) -> ();
}

/// A stateful ticker that fires registered listeners with an incrementing
/// counter. `on_tick` is a `Shape::Subscription` op — it REGISTERS a host
/// callback (a PHP `callable`/`Closure`) and hands back an owning `Subscription`
/// handle whose unsubscribe() removes the listener; `tick` fires every live
/// listener SYNCHRONOUSLY on the PHP request thread. This is the callback +
/// subscription slice's PHP (ext-php-rs) round-trip proof. PHP callbacks are
/// documented SYNC-ONLY: the callable is only ever invoked on the request thread
/// that supplied it (off-thread invocation is unsupported) — see the PhpCb marker.
#[php_class]
pub struct Ticker {
    // pub(crate): the @manual ops in lib.rs extend this class and need the core
    pub(crate) core: Arc<crate::core_impl::TickerImpl>,
}

#[php_impl]
impl Ticker {
    /// Open a fresh ticker with no listeners and the counter at 0.
    /// PHP: Ticker::new(): void
    pub fn __construct() -> PhpResult<Self> {
        Ok(Self {
            core: Arc::new(<crate::core_impl::TickerImpl as TickerCore>::new().map_err(err)?),
        })
    }
    /// Register `listener` to be called on every `tick`; returns a Subscription
    /// handle that removes the listener when unsubscribed. The listener is invoked
    /// synchronously on the PHP request thread (the sync-only contract).
    /// PHP: Ticker::on_tick(callable $listener): void
    pub fn on_tick(&self, listener: &ext_php_rs::types::Zval) -> PhpResult<Subscription> {
        let listener: Box<dyn Fn(i32) + Send + Sync> = {
            // The callable `Zval` is `shallow_clone`d (bumping its refcount so it
            // outlives this call) and pinned as an owned `ZendCallable<'static>`.
            let __cb = PhpCb(
                ext_php_rs::types::ZendCallable::new_owned(listener.shallow_clone())
                    .map_err(err)?,
            );
            Box::new(move |v: i32| {
                // SYNC-ONLY: invoked synchronously on the PHP request thread (the core
                // fires listeners from a PHP method call). Off-thread invocation is UB —
                // see the `PhpCb` doc marker / notes/callback-function-types.md.
                let _ = __cb.callable().try_call(vec![&v]);
            })
        };
        let unsub = self.core.on_tick(listener);
        Ok(Subscription {
            unsub: std::sync::Mutex::new(Some(unsub)),
        })
    }
    /// Fire every live listener with the current counter value, then increment it
    /// (infallible — registration/firing never fails).
    /// PHP: Ticker::tick(): void
    pub fn tick(&self) -> () {
        self.core.tick()
    }
}

/// Registers the extension's surface with PHP.
#[php_module]
pub fn module(module: ModuleBuilder) -> ModuleBuilder {
    module
}
