//! The PHP (ext-php-rs) callback demo crate — the compile+run gate for fluessig's
//! `ApiType::Callback` + `Shape::Subscription` lowering on the PHP backend. The
//! generated ext-php-rs surface (`src/generated.rs`) is compiled INTO this cdylib
//! and driven by a real PHP round-trip (`consumer.php`), which subscribes a host
//! `Closure` via `onTick`, ticks twice → sees `[0, 1]`, unsubscribes, ticks again
//! → still `[0, 1]` — a PHP closure invoked from Rust SYNCHRONOUSLY on the request
//! thread, then removed.
//!
//! PHP is DOCUMENTED SYNC-ONLY (the coordinator ruling): the generated `PhpCb`
//! newtype asserts `Send`/`Sync` over a `!Send` PHP callable, sound only because
//! the demo invokes the listener synchronously on the same PHP request thread that
//! supplied it (off-thread invocation is UB). See the LOUD marker on `PhpCb` in the
//! generated file and notes/callback-function-types.md.
//!
//! * `src/core_impl.rs`— the hand-written `TickerImpl` engine (the ONE hand file).
//! * `src/generated.rs`— GENERATED by `fluessig-gen` (see `regen.sh`); do not edit.
//! * `run.sh`          — build the extension + run the PHP consumer.

// The hand-written engine the generated ext-php-rs layer routes through.
pub mod core_impl;

// The generated ext-php-rs surface. Loaded as a FILE module (`#[path]`) so the
// generated file's leading inner attributes (`#![allow(...)]`) stay valid. Its
// `#[php_module]` fn exports the `get_module` symbol PHP calls on extension load,
// and every `#[php_class]` (Ticker, Subscription) auto-registers through it.
#[path = "generated.rs"]
pub mod generated;
