//! GENERATED by fluessig bindgen from the fluessig catalog (api layer). Do not edit.
//! straitjacket-allow-file:duplication — the generated pyo3 surface mirrors the sibling node demo's by design (one uniform core shape per backend).
#![allow(clippy::all)]

use pyo3::exceptions::PyRuntimeError;
use pyo3::exceptions::PyStopAsyncIteration;
use pyo3::prelude::*;
use std::sync::Arc;
use std::time::Duration;
// The shared streaming contract — Poll/PollStream live in the fluessig-runtime crate.
use fluessig_runtime::{Poll, PollStream};

fn err(e: impl std::fmt::Display) -> PyErr {
    PyRuntimeError::new_err(e.to_string())
}

/// The `Ticker` contract — implement over the engine in `crate::core_impl`.
pub trait TickerCore: Sized + Send + Sync + 'static {
    fn each_tick(count: i32, listener: Box<dyn Fn(i32) + Send + Sync>) -> anyhow::Result<()>;
}

#[pyfunction]
#[pyo3(signature = (count, listener))]
fn each_tick(py: Python<'_>, count: i32, listener: PyObject) -> PyResult<()> {
    let listener_cb: Box<dyn Fn(i32) + Send + Sync> = {
        let cb = listener.clone_ref(py);
        Box::new(move |v: i32| {
            Python::with_gil(|py| {
                let _ = cb.call1(py, (v,));
            });
        })
    };

    <crate::core_impl::TickerImpl as TickerCore>::each_tick(count, listener_cb).map_err(err)
}

/// Register every generated class + function on the `#[pymodule]`.
pub(crate) fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(each_tick, m)?)?;
    Ok(())
}
