//! The python (pyo3) callback demo crate — the compile+run gate for fluessig's
//! `ApiType::Callback` lowering on the python backend. The generated pyo3 surface
//! (`src/generated.rs`) is compiled INTO this cdylib and driven by a real Python
//! round-trip (`consumer.py`), which passes a host callable into `each_tick` and
//! asserts it fired with `[0, 1, 2]` — a Python callable invoked from Rust inline
//! under the GIL.
//!
//! * `src/core_impl.rs`— the hand-written `TickerImpl` engine (the ONE hand file).
//! * `src/generated.rs`— GENERATED by `fluessig-gen` (see `regen.sh`); do not edit.
//! * `run.sh`          — build the extension module + run the Python consumer.

use pyo3::prelude::*;

// The hand-written engine the generated pyo3 layer routes through.
mod core_impl;

// The generated pyo3 surface. Loaded as a FILE module (`#[path]`) so the
// generated file's leading inner attributes (`#![allow(...)]`) stay valid.
#[path = "generated.rs"]
mod generated;

/// The extension module. `import callback_demo` after run.sh renames the built
/// cdylib to `callback_demo.so`. Delegates registration to the generated
/// `register` (adds the `each_tick` free function).
#[pymodule]
fn callback_demo(m: &Bound<'_, PyModule>) -> PyResult<()> {
    generated::register(m)
}
